### ISSUE TITLE
send_keys中文无输入

### ISSUE THREAD

**Issue by erjinzhi2333** [openatx/uiautomator2#100]
```
d.set_fastinput_ime(True)
d.send_keys(u"中文")
```

## Versions (版本)
0.1.1.dev34

## Issue and steps to reproduce (复现步骤)
- 设备: mumu模拟器
- 异常日志:Warning: set FastInputIME failed. use "d(focused=True).set_text instead"
异常日志这样显示，但是能看到模拟器中已经选择为fastinputIME输入法

## Screenshots （相关截图）
暂无

## Additional Details （其他信息）
输入英文没问题，雷电模拟器测试可以输入中文。mumu模拟器用pc搜狗输入中文可以，当输入框存在文本时，会占用几个字符。示例：输入框存在 hello，当send_keys(u"中文")，输入框内容会变为 llo.

**Comment by codeskyblue** [comment]
这个呢是因为，模拟器上没有办法使用我们给自动化设计的输入法。所以只能用 `adb shell input text`代替了。而这种方法只能输入英文。并没有什么别的好办法
