### ISSUE TITLE
screenshot出来的是白屏

### ISSUE THREAD

**Issue by liaoxuewei** [openatx/uiautomator2#1000]
screenshot出来的是白屏，有可能是什么原因引起？前几天我记得还是可以的，然后不知道为什么过了一段时间看就不行了

- 手机型号[逍遥模拟器]
- uiautomator2的版本号(`pip show uiautomator2`)[3.1.0]
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。
        d = u2.connect()
        print(d.info)
        d.screenshot("home.jpg")

**Comment by liaoxuewei** [comment]
截屏没有任何错误

**Comment by liaoxuewei** [comment]
adb shell screencap -p /sdcard/screen.png运行这个adb目录，截屏也是白屏

**Comment by liaoxuewei** [comment]
adb shell screencap -p /sdcard/screen.png运行这个adb目录，截屏也是白屏

**Comment by codeskyblue** [comment]
try uiautomator2 3.2.0

**Comment by codeskyblue** [comment]
暂时先关闭了，如果还有问题再reopen
