### ISSUE TITLE
core.py代码里面关于报错检查的bug

### ISSUE THREAD

**Issue by fuhao666** [openatx/uiautomator2#1001]
![image](https://github.com/openatx/uiautomator2/assets/42905609/6f9001fd-5d81-4e15-8105-cdadd627d7d1)
这里没有in message，会导致下面的检测完全不运行吧。
if "uiautomator.UiObjectNotFoundException" in message:
            raise UiObjectNotFoundError(code, message, params)
if "java.lang.StackOverflowError" in message:
    raise RPCStackOverflowError(f"StackOverflowError: {message}", params, stacktrace[:1000] + "..." + stacktrace[-1000:])

**Comment by codeskyblue** [comment]
thanks @fuhao666
