### ISSUE TITLE
packaging版本冲突

### ISSUE THREAD

**Issue by Huayahg** [openatx/uiautomator2#1003]
当使用python 3.7.9 的时候
安装最新的uiautomator2 2.16.7
当在安装pyinstaller的时候提示packaging版本冲突
 以下是冲突内容：
pyinstaller-hooks-contrib 2024.7 requires packaging>=22.0, but you have packaging 20.9 which is incompatible.
uiautomator2 2.16.7 requires packaging~=20.3, but you have packaging 24.0 which is incompatible.
麻烦帮忙看下，如何解决，感谢

**Comment by codeskyblue** [comment]
请更换python 3.8+,没这个问题了，应为没有packaging这个依赖了
