### ISSUE TITLE
主线程和watcher线程有交互吗？

### ISSUE THREAD

**Issue by lzus** [openatx/uiautomator2#1007]
主线程正在进行正常UI自动化，此时出现一个被watcher监控的弹窗，如果watcher线程没来得及检测，主线程接着运行是不是就会出错了？ 我不知道这两个线程有没有交互和协调，如果有，在哪个文件源码文件里实现的？

**Comment by codeskyblue** [comment]
目前是开了一个子线程去监控的，主线程运行时的时候会有等待逻辑的
