### ISSUE TITLE
监测app crash的session报错requests.exceptions.HTTPError: 410 Client Error: Gone for url: http://127.0.0.1:62710/session/com.netease.cloudmusic

### ISSUE THREAD

**Issue by GBwuka** [openatx/uiautomator2#101]
d = u2.connect('8FS5T16801009856')
sess = d.session("com.netease.cloudmusic") # start 网易云音乐
执行报错：
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: http://127.0.0.1:62710/session/com.tencent.qqmusictv
是现在这个方法不可用么？

**Comment by codeskyblue** [comment]
怎么冒出来一个qq音乐
