### ISSUE TITLE
README中wait_stable()有.close()，但实际代码中没有了，期望加回来

### ISSUE THREAD

**Issue by TonyGao2527** [openatx/uiautomator2#1019]
uiautomator2 == 3.2.1
使用时报错
AttributeError: 'WatchContext' object has no attribute 'close'
![QQ_1722484192307](https://github.com/user-attachments/assets/65bf66e1-a19f-40ec-b9b2-52cbac9724eb)
![QQ_1722490707658](https://github.com/user-attachments/assets/0c4ed5ec-3c18-468e-af8d-1c82b2ad662a)

**Comment by codeskyblue** [comment]
added
