### ISSUE TITLE
3.2.1版本中依然留有app-uiautomator.apk

### ISSUE THREAD

**Issue by ivercan** [openatx/uiautomator2#1020]
use u2.jar instead of test apk (#1004)中core.py代码修改已经把下面2个apk的内容删除了。但pip上安装的3.2.1版本中的库中还是有assets/app-uiautomator.apk文件.

com.github.uiautomator.test
com.github.uiautomator

**Comment by codeskyblue** [comment]
这个uiautomator.apk主要是里面包含了一个输入法程序，输入中文的时候，还用得到它

**Comment by codeskyblue** [comment]
观察的真仔细

**Comment by Yan0789** [comment]
> 观察的真仔细
没有了ATX-agent，weditor电脑端怎么用呢？
![微信截图_20240812170147](https://github.com/user-attachments/assets/76168a1c-3032-407c-932f-6242dcf9bff2)

**Comment by hashqueue** [comment]
> > 观察的真仔细
> > 没有了ATX-agent，weditor电脑端怎么用呢？
> > ![微信截图_20240812170147](https://private-user-images.githubusercontent.com/124667564/356991240-76168a1c-3032-407c-932f-6242dcf9bff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzMTMsIm5iZiI6MTcyMzcxNTAxMywicGF0aCI6Ii8xMjQ2Njc1NjQvMzU2OTkxMjQwLTc2MTY4YTFjLTMwMzItNDA3Yy05MzJmLTYyNDJkY2Y5YmZmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwOTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTE2NTMyMzRmNDZhYmZjMDNhMzgyYTExN2YzNTQyM2U3OTliNDQxYjY2ZDljMTFkNzI4ODc2NjI0Y2YwZTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4OkxmLogC4tAYqWpxF-tTAX1s-VEzcbAO9pyXcFoXiA)

https://github.com/codeskyblue/uiautodev

**Comment by zuiailaoda** [comment]
> 这个uiautomator.apk主要是里面包含了一个输入法程序，输入中文的时候，还用得到它

这个输入法有什么办法删除吗？
