### ISSUE TITLE
dump_hierarchy dump 下来的视图树不完整

### ISSUE THREAD

**Issue by ohmerhe** [openatx/uiautomator2#103]
我使用dump_hierarchy去dump当前页面的视图树，但是得到的试图树并不完整，也就是说只有一部分视图节点被dump下来

**Comment by codeskyblue** [comment]
那么有哪些没有呢？

**Comment by ohmerhe** [comment]
[resources.zip](https://github.com/openatx/uiautomator2/files/2008386/resources.zip)

这里面少的的那个是用uiautomator2 dump下来的

**Comment by codeskyblue** [comment]
能不能截图说明下，看起来实在费劲

**Comment by mingyuan-xia** [comment]
我记得有compress模式，默认好像是开的

**Comment by codeskyblue** [comment]
compress模式下 图像信息都不会包含

**Comment by codeskyblue** [comment]
但是u2里面compress默认是关闭的

**Comment by ohmerhe** [comment]
跟compress模式没有关系，压缩包里面的两个文件里面元素的数量差别比较大
现在现场没有了，等我有机会再处理这一块我截个图试试

**Comment by codeskyblue** [comment]
en

**Comment by codeskyblue** [comment]
下次遇到了，重新reopen
