### ISSUE TITLE
u2.jar source code

### ISSUE THREAD

**Issue by dude123333** [openatx/uiautomator2#1031]
version 3.2.0 uses u2.jar #1004 
please add source code to [jar](https://public.uiauto.devsleep.com/u2jar/) updates

**Comment by codeskyblue** [comment]
not open sourced for now.

**Comment by NextAlone** [comment]
Will you provide an estimated timeline? I need to modify the source code to add a multi-finger gesture feature for my study. Thank you.

**Comment by momochenxx** [comment]
@codeskyblue  Hi, Is there a plan to open-source this U2.jar?

**Comment by codeskyblue** [comment]
not going to be opensource. But if you would like to contribute, I
will.add.you.as member of the private repo.

孙圣翔 - codeskyblue [码出一片蓝天白云] - Tel: 15695711039


momochen ***@***.***>于2025年7月27日 周日09:02写道：

**Comment by momochenxx** [comment]
@codeskyblue  If I can become a member, I would be very willing to support.
