### ISSUE TITLE
dump_hierarchy not capturing element

### ISSUE THREAD

**Issue by mscottwvc** [openatx/uiautomator2#1041]
I have the latest version installed, but I still cant get dump_hierarchy to capture the orange bubble on the screen.  It seems to be some kind of popup window, but it is part of the app.  Everything else on the screen is read correctly.  Anything I can do to try and read that element?
![b](https://github.com/user-attachments/assets/4e49bfd1-b536-49fd-81d2-8f2ce23b87e9)

**Comment by graysuit** [comment]
@mscottwvc uiautomator2 doesn't supports webview
You have to get screenshot and extract text (OCR)
I use tesseract in vb net
