### ISSUE TITLE
Uiautomator2 with Pyinstaller

### ISSUE THREAD

**Issue by kschepps** [openatx/uiautomator2#1060]
I'm trying to create an executable with Uiautomator2 using Pyinstaller. The app runs just fine as a python script, but I get the error below from the exe. This appears to be similar to this (closed) issue: #1038 

How do I get this script with Uiautomator2 to work as an exe using Pyinstaller?

Script: test.py
```
import uiautomator2 as u2

d = u2.connect() # connect to device
xml = d.dump_hierarchy()
print(xml)
```

Pyinstaller command:
```
pyinstaller -c -F test.py
```

Error:
```
test.exe
Traceback (most recent call last):
  File "test.py", line 3, in <module>
  File "uiautomator2\__init__.py", line 1103, in connect
  File "uiautomator2\__init__.py", line 1119, in connect_usb
  File "uiautomator2\__init__.py", line 69, in __init__
  File "uiautomator2\core.py", line 170, in __init__
  File "uiautomator2\core.py", line 189, in start_uiautomator
  File "uiautomator2\core.py", line 201, in _setup_jar
  File "uiautomator2\core.py", line 210, in _check_device_file_hash
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KCEB0~1.SCH\\AppData\\Local\\Temp\\_MEI50042\\uiautomator2\\assets\\u2.jar'
[PYI-21080:ERROR] Failed to execute script 'test' due to unhandled exception!
```

**Comment by kschepps** [comment]
I was also able to overcome this issue by following the below steps without editing my actual script
1. Uninstalled uiautomator2 from Windows PC using 'pip uninstall uiautomator2'
2. Using Linux, performed 'git clone https://github.com/openatx/uiautomator2.git'
3. Ran the sync.sh under uiautomator2/uiautomator2/assets to get the u2.jar file downloaded
4. On another PC, I also needed to run 'pip install adbutils' since it never had uiautomator2 installed
5. Copied uiautomator2/uiautomator2 folder to the same folder as my script in Windows
6. Ran pyinstaller with the added value '--add-data "uiautomator2:uiautomator2"

**Comment by ao-zz** [comment]
> I was also able to overcome this issue by following the below steps without editing my actual script
> 
> 1. Uninstalled uiautomator2 from Windows PC using 'pip uninstall uiautomator2'
> 2. Using Linux, performed 'git clone https://github.com/openatx/uiautomator2.git'
> 3. Ran the sync.sh under uiautomator2/uiautomator2/assets to get the u2.jar file downloaded
> 4. On another PC, I also needed to run 'pip install adbutils' since it never had uiautomator2 installed
> 5. Copied uiautomator2/uiautomator2 folder to the same folder as my script in Windows
> 6. Ran pyinstaller with the added value '--add-data "uiautomator2:uiautomator2"'

Great work!
But Linux is not neccesary indeed.
For those who may confuse about these steps, following are my steps:
1. `pip uninstall uiautomator2`
2. `git clone https://github.com/openatx/uiautomator2.git`
3. open `uiautomator2/uiautomator2/assets/sync.sh`, find the URL in function `download_jar`. At the time I write this comment, the URL is `https://public.uiauto.devsleep.com/u2jar/0.1.5/u2.jar`
4. open the URL in any browser, and u2.jar will be downloaded automaticlly
5. move u2.jar into `uiautomator2/uiautomator2/assets`
6. Copy the folder `uiautomator2/uiautomator2` to the location where your script is.
7. `pyinstaller --add-data="uiautomator2:uiautomator2" -F xxx.py`

中文版本：
很有用！但其实 Linux 并不是必须的。
可能大家对某些步骤会有疑惑，下面是我理解的版本：
1. `pip uninstall uiautomator2`
2. `git clone https://github.com/openatx/uiautomator2.git`
3. 下载完成以后，就会有一个uiautomator2目录。打开`uiautomator2/uiautomator2/assets/sync.sh`这个文件，找到`download_jar`函数，里面有一个URL变量，找到它的值。在我写的时候，最新的 URL 是 `https://public.uiauto.devsleep.com/u2jar/0.1.5/u2.jar`
4. 在浏览器上打开上面的 URL，会开始自动下载 u2.jar 这个文件
5. 把 u2.jar 移动到 `uiautomator2/uiautomator2/assets` 目录下
6. 把 `uiautomator2/uiautomator2` 这个目录，移动到你想打包的脚本的同级目录。比如你的脚本位置是 a/xxx.py，那么移动后就有 a/uiautomator2/uiautomator2
7. 执行 `pyinstaller --add-data="uiautomator2:uiautomator2" -F xxx.py`
