### ISSUE TITLE
init doesn't start service as reliable as d.connect, attempts to start on already started phones

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#112]
Is the 'python -m uiautomator2 init' meant to start connect the daemon on multiple devices, or just do install?  It's not doing it all the time.  We should be connect manually?  That works better.

It also attempts to run init on phones it has just recently done init and start daemon successfully on.

An easier way to stop the service would be cool too, usually continues running on phone after test has ended

Thanks for the great work

**Comment by codeskyblue** [comment]
能看懂中文吗

**Comment by gamesguru** [comment]
No but I can translate it.

I'm not sure this issue is as serious as I'm making it, feel free to close it.  I've had a few small other issues, but will open up a issue when (if) I'm more confident about things (mostly with WiFi).

We have setups with 20+ phones that we will be starting to use your service on for our in house testing if all goes well.  Looking forward to your cooperation.

**Comment by codeskyblue** [comment]
Sorry for the lack of English version of readme. init do install and launch atx-agent. and you only need to do it once until you restart your phone

**Comment by gamesguru** [comment]
How often are you using this with 2 or 3, or more phones?  Is there a way to send the init command to one device when you have many attached?  Is there a way to check if init needs to be run at all, or if that device has the service running?  It can be hard to keep things going and managed.

I would like to make a script that is always running in the background checking for "uninitialized" devices and ready to send them the init command if need be.  I realize over wifi that presents more difficulties but one step at a time.

This might be easier than making the service start automatically after phone reboots.

**Comment by codeskyblue** [comment]
are you offen reboot phones?

**Comment by gamesguru** [comment]
not very often.  But maybe the battery reports false and empties.  Even if I just leave a phone to sit a few days, it doesn't reboot, but might need init.  It needs more than just restarting the uiautomator service.

**Comment by codeskyblue** [comment]
You can use function `d.alive # True or False` to check if ready to use.

**Comment by gamesguru** [comment]
okay, and i can target a specific device with this command?

`python -m uiautomator2 init --server <device_serial>`

**Comment by codeskyblue** [comment]
yes

**Comment by gamesguru** [comment]
okay.  What about WiFi?  Is there some backup server we can put on the phone as a package or script?  Or will it always be easier to re-connect with usb.

We have some phones using WiFi and plugged into the wall because it charges them better than a computer, and those phones are sometimes needing a reinit

**Comment by gamesguru** [comment]
It tries to connect to all devices even when I specify one.

Also, certain devices are giving me problems since a recent update.  I don't think enough time is given for them to connect.  The init command returns a non-success, but if I launch a python shell I can run manual commands, like unlock, click, press.  Here is the error, just one device plugged in for convenience.

> 2018-06-18 11:07:13,964 - __main__.py:269 - INFO - Detect pluged devices: ['03509a46588500000000']
> 2018-06-18 11:07:13,964 - __main__.py:286 - INFO - Device(03509a46588500000000) initialing ...
> 2018-06-18 11:07:15,010 - __main__.py:113 - INFO - install minicap
> 2018-06-18 11:07:15,561 - __main__.py:120 - INFO - install minitouch
> 2018-06-18 11:07:16,437 - __main__.py:137 - INFO - apk(1.1.0) already installed, skip
> 2018-06-18 11:07:16,636 - __main__.py:175 - INFO - atx-agent(0.3.3) already installed, skip
> 2018-06-18 11:07:17,107 - __main__.py:212 - INFO - launch atx-agent daemon
> Traceback (most recent call last):
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
>     httplib_response = conn.getresponse()
>   File "C:\Python36\lib\http\client.py", line 1331, in getresponse
>     response.begin()
>   File "C:\Python36\lib\http\client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "C:\Python36\lib\http\client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "C:\Python36\lib\socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python36\lib\site-packages\requests\adapters.py", line 440, in send
>     timeout=timeout
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "C:\Python36\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=58737): Read timed out. (read timeout=3)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Python36\lib\site-packages\uiautomator2\__main__.py", line 356, in <module>
>     main()
>   File "C:\Python36\lib\site-packages\uiautomator2\__main__.py", line 352, in main
>     fire.Fire(MyFire)
>   File "C:\Python36\lib\site-packages\fire\core.py", line 127, in Fire
>     component_trace = _Fire(component, args, context, name)
>   File "C:\Python36\lib\site-packages\fire\core.py", line 366, in _Fire
>     component, remaining_args)
>   File "C:\Python36\lib\site-packages\fire\core.py", line 542, in _CallCallable
>     result = fn(*varargs, **kwargs)
>   File "C:\Python36\lib\site-packages\uiautomator2\__main__.py", line 273, in init
>     ignore_apk_check)
>   File "C:\Python36\lib\site-packages\uiautomator2\__main__.py", line 295, in _init_with_serial
>     ins.launch_and_check()
>   File "C:\Python36\lib\site-packages\uiautomator2\__main__.py", line 225, in launch_and_check
>     'http://localhost:%d/version' % lport, timeout=3)
>   File "C:\Python36\lib\site-packages\requests\api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "C:\Python36\lib\site-packages\requests\api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Python36\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Python36\lib\site-packages\requests\sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Python36\lib\site-packages\requests\adapters.py", line 521, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=58737): Read timed out. (read timeout=3)

**Comment by codeskyblue** [comment]
To know what happened, fisrtr see uiautomator2 version and log under phone /sdcard/atx-agent.log

**Comment by gamesguru** [comment]
Let me know I am curious.  These are 6.0 touch panels, giving us problems 4.4.2 ones aren't.  Again, d.alive= True, but init prints a stacktrace.

Two machines are having this issue
==> apk@1.0.12 && atx@0.3.0
==> apk@1.1.0 && atx@0.3.3

Full atx log:

> 2018/06/19 20:14:18 main.go:1326: Ignore SIGHUP
> 2018/06/19 20:14:18 main.go:1330: Kill server
> 2018/06/19 20:14:18 main.go:1336: Get http://127.0.0.1:7912/stop: dial tcp 127.0.0.1:7912: connect: connection refused
> atx-agent version 0.3.3
> Internet is not connected.2018/06/19 20:14:24 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
> 2018/06/19 20:14:24 cmdctrl.go:27: DEBUG program pid: 659
> 2018/06/19 20:14:24 main.go:784: rotation change received: 0
> 2018/06/19 20:14:24 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 800x480@800x800/0]
> 2018/06/19 20:14:26 main.go:784: rotation change received: 0
> 2018/06/19 20:14:26 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 800x480@800x800/0]
> INSTRUMENTATION_STATUS: numtests=1
> INSTRUMENTATION_STATUS: stream=
> com.github.uiautomator.stub.Stub:
> INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
> INSTRUMENTATION_STATUS: test=testUIAutomatorStub
> INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
> INSTRUMENTATION_STATUS: current=1
> INSTRUMENTATION_STATUS_CODE: 1
> 2018/06/19 20:19:26 main.go:761: startservice com.github.uiautomator/.Service

**Comment by codeskyblue** [comment]
This you print is normal log not sstacktrace

**Comment by gamesguru** [comment]
Yes, I will delete the log and try again but init should return SUCCESS, not a stacktrace?  Why does it return the http/socket timeout exception when atx is actually started??

**Comment by codeskyblue** [comment]
that is wiered

**Comment by gamesguru** [comment]
it is something we can polish out eventually.  I just started using d.alive instead of parsing the __init__ output.  It works.

I'm more concerned with sending the init command to one device when you have two plugged in.  Have we done that yet?

**Comment by gamesguru** [comment]
very weird.  It is happening on all devices which require special permissions.

Since when did you implement the "wait uiautomator is ready" stuff?

**Comment by codeskyblue** [comment]
using the function call d.service(uiautomator).start() 
to start uiautomator.

**Comment by gamesguru** [comment]
As for the backup server on the phone, so you don't have to run `python -m uiautomator2 init` after each time it crashes or reboots.. I'm told it's not really possible without rooting the device?

**Comment by gamesguru** [comment]
Found out the proper way to init one device:

`python -m uiautomator2 _init_with_serial SERIAL_NO None None None False True`

**Comment by gamesguru** [comment]
ok.  is good.  should also be in readme, for newbies to python

**Comment by gamesguru** [comment]
Why  am I getting this error sometimes with the --serial but it works fine with just init??

```List of devices attached
87681e28689700000000    device

$ python -m uiautomator2 init --serial 87681e28689700000000

2018-08-27 12:31:49,229 - __main__.py:286 - INFO - Device(inf) initialing ...
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\uiautomator2\adbutils.py", line 41, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "C:\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '"C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.EXE" -s inf shell getprop ro.build.version.sdk' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 356, in <module>
    main()
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 352, in main
    fire.Fire(MyFire)
  File "C:\Python37\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Python37\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Python37\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 282, in init
    reinstall, ignore_apk_check)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 287, in _init_with_serial
    ins = Installer(serial)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 95, in __init__
    self.sdk = self.getprop('ro.build.version.sdk')
  File "C:\Python37\lib\site-packages\uiautomator2\adbutils.py", line 102, in getprop
    return self.execute('shell', 'getprop', prop).strip()
  File "C:\Python37\lib\site-packages\uiautomator2\adbutils.py", line 46, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.EXE" -s inf shell getprop ro.build.version.sdk: "error: device 'inf' not found\r\n"````
