### ISSUE TITLE
真机WebView实现 中的Android System Webview  对元素识别的影响

### ISSUE THREAD

**Issue by Archer456** [openatx/uiautomator2#113]
https://github.com/openatx/uiautomator2/issues/109
书接上回,解决了init u2的报错后.  

确认init u2 是最新更新的之后发现:
更新后 模拟器 8.0 可通过脚本
但 真机mix2 8.0 不可通过脚本
用 weditor tap 同样元素 也发现 模拟器可以 真机mix2不可以.

`(ATX365) cmd@TR:~$ adb devices -l
List of devices attached
myno               device usb:3-1 product:chiron model:MIX_2 device:chiron transport_id:33

(ATX365) cmd@TR:~$ pip show uiautomator2 
Name: uiautomator2
Version: 0.1.2.dev18
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /home/cmd/.pyenv/versions/3.6.5/envs/ATX365/lib/python3.6/site-packages
Requires: requests, six, humanize, fire, progress, retry, whichcraft
Required-by: atx`

经过个人排查 ,查看真机与模拟器选项发现
开发者选项中的 WebView实现 中的Android System Webview 版本不一样.
模拟器中是 58.0.3029.125  真机中是66.0.3359.158

另一现象是,其他人的真机8.0 8.1  但Android System Webview < 66.0.3359.158  比如 有人用的WebView实现中的 另一选择 Chrome66.0.3359.158 确是可以通过的.
不明是否 WebView实现 中的Android System Webview 过高版本 对此UI识别有影响.

此UI的,截图:
![image](https://user-images.githubusercontent.com/18392901/40520886-26efaa04-5ffb-11e8-95c7-901da0b5cfc7.png)

**Comment by Archer456** [comment]
也许是这个原因:

后来通过查看appium源码发现了问题 appium找的版本号并不是手机上的android system webview版本号 而是被测app的chrome版本号。
也就是说你要测的app chrome是51版本，那么就应该按照chrome和chromedriver的对应关系对chromedriver进行降级！[个人想法，如有错误还请指出]
也就说当你测试不同app的Webview时 所需要的chromedriver可能是需要变化的。
appium断点内容

**Comment by codeskyblue** [comment]
haha, 2018年的问题
