### ISSUE TITLE
python -m uiautomator2 init提示adb版本不兼容

### ISSUE THREAD

**Issue by xmt328** [openatx/uiautomator2#118]
## Versions (版本)
Name: uiautomator2
Version: 0.1.2.dev20
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\program files\python36\lib\site-packages
Requires: requests, six, humanize, fire, progress, retry, whichcraft
Required-by: atx

## Issue and steps to reproduce (复现步骤)
执行设备初始化时提示
OSError: [Errno subprocess] D:\android-sdk\platform-tools\adb.EXE -s 409c5058 shell getprop ro.build.version.sdk: "adb server version (32) doesn't match this client (39); killing...\r\n* daemon started successfully\r\nerror: device offline\r\n"

## Screenshots （相关截图）
![tim 20180529110804](https://user-images.githubusercontent.com/17491710/40636253-bd44f03a-6330-11e8-9911-b94f2d964ca8.png)

**Comment by codeskyblue** [comment]
电脑上adb版本太多了
