### ISSUE TITLE
shell命令设置超时后仍然60秒超时报错

### ISSUE THREAD

**Issue by hxbjava** [openatx/uiautomator2#121]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到
0.1.2.dev21
## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快
使用d.shell命令设置timeout后仍然60秒超时

## Screenshots （相关截图）
能有尽量有
![image](https://user-images.githubusercontent.com/18526020/40714966-aab7f104-6436-11e8-87e5-a7a951e15f9f.png)
![image](https://user-images.githubusercontent.com/18526020/40714979-b2fb11de-6436-11e8-86da-a6ebbec79948.png)

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
atx-agent还没发布，稍等下

**Comment by codeskyblue** [comment]
atx-agent 0.3.3已更新。试试新版应该没问题了。有问题的话再重新reopen

**Comment by hxbjava** [comment]
基础信息：
手机atx-agent版本已经更新至0.3.3
ui2版本0.1.3.dev1
![image](https://user-images.githubusercontent.com/18526020/41269441-c06e645a-6e37-11e8-94b4-744fc3eb2680.png)
日志信息：
![image](https://user-images.githubusercontent.com/18526020/41271912-98c91fa4-6e45-11e8-8d2d-04553b800770.png)
![image](https://user-images.githubusercontent.com/18526020/41271921-9f4dba74-6e45-11e8-9727-e0d707ecbf20.png)
PS：很奇怪，手机的atx-agent版本 跑着跑着又变成了0.3.2
![image](https://user-images.githubusercontent.com/18526020/41271947-b905775e-6e45-11e8-87b7-2e34e36df93a.png)

**Comment by codeskyblue** [comment]
atx-server的参数里面有指定agent的版本，那个地方也要修改

**Comment by hxbjava** [comment]
如果不用atx-server上查看agent版本 还能从哪查看？
