### ISSUE TITLE
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert protocol version')],)",)

### ISSUE THREAD

**Issue by zhenghengZN** [openatx/uiautomator2#124]
python -m uiautomator2 init之后出现这个问题是什么情况，用usb连接的手机

requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert protocol version')],)",)

**Comment by codeskyblue** [comment]
Answer from https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version

You may need to upgrade pip through

```bash
curl https://bootstrap.pypa.io/get-pip.py | python
```
