### ISSUE TITLE
uiautomator2升级后，print(u.current_app())结果不是期望的页面内容

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#125]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
print(u.current_app())
```
想获取activity等
打印结果：<bound method UIAutomatorServer.current_app of uiautomator2 object for 127.0.0.1:62990>
升级uiautomator2前，是可以用的

## Versions (版本)
通过`pip show uiautomator2`可以获取到
Name: uiautomator2
Version: 0.1.2.dev21

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/41016679-78af8fe4-6983-11e8-9450-626b720b3795.png)

我猜你是把代码写成了 `print(u.current_app)` 

测试了一下没啥问题

**Comment by HeartIsBeat** [comment]
上面打印的确实是```print(u.current_app)```
不过```print(u.current_app())```好像是概率性出现异常的，特别是先startApp，再u.current_app()

**Comment by codeskyblue** [comment]
```
pip install --pre -U uiautomator2
```
升级一下吧，确认可以解决你这个问题

**Comment by HeartIsBeat** [comment]
┭┮﹏┭┮，升级之后还是有问题，特别是点击跳转过去的activity还没加载出来，这时候打印u.current_app()就会出错

**Comment by codeskyblue** [comment]
出错的时候把报错信息也贴上来

**Comment by HeartIsBeat** [comment]
![image](https://user-images.githubusercontent.com/20472976/41092455-81de1ccc-6a7b-11e8-90ad-a5844bd94b00.png)
一样的异常错误

**Comment by codeskyblue** [comment]
升级到 0.1.2
