### ISSUE TITLE
三星note4 android4.4.4  push命令报错

### ISSUE THREAD

**Issue by hxbjava** [openatx/uiautomator2#126]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到
0.1.2.dev21
## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快
三星note4 android4.4.4  push命令报错
- 手机型号?
三星note4 android 4.4.4
- 错误日志?
![image](https://user-images.githubusercontent.com/18526020/41022609-ac5feeb0-699c-11e8-8b8b-d8e92510432f.png)

- 出错的代码片段?
![image](https://user-images.githubusercontent.com/18526020/41022604-a6652f52-699c-11e8-9d9b-006564874c22.png)

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
感觉是写权限不足，换到 `/sdcard/`目录下试试吧
