### ISSUE TITLE
-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.facebook.katana:id/standard_header_title]

### ISSUE THREAD

**Issue by liuhan2014** [openatx/uiautomator2#127]
如题 ，经常有获取不到元素的情况。 但有时候能找到元素？这回是哪些因素影响的那？
我是用的是  d(resourceId="com.facebook.katana:id/standard_header_title")

**Comment by liupeiyu** [comment]
I also meet  this  question,though Google  all the time,I  can  not  get the solutions

**Comment by codeskyblue** [comment]
Can't help.
