### ISSUE TITLE
weditor一直处在加载中

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#128]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

weditor 取元素，tap或sendText一个会自动弹出键盘的输入框，页面就会一直处于加载中，只能ctrl+c才能退出重来了。
![image](https://user-images.githubusercontent.com/20472976/41025131-b648ebf0-69a3-11e8-8251-1216c3dd3a15.png)

## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/20472976/41025096-a045c6b6-69a3-11e8-836f-1b97937c2c3e.png)

**Comment by flyfire100** [comment]
这个我也碰到过很多次，清楚qq浏览器的缓存后，在打开qq浏览器，在首页的位置就抓不到元素，一直在加载

**Comment by codeskyblue** [comment]
测试了一下最新版的weditor，已经没有这个问题了
```
pip install -U --pre weditor
```

可以更新测试下

**Comment by codeskyblue** [comment]
如果还有问题，请Reopen
