### ISSUE TITLE
Direct `children`

### ISSUE THREAD

**Issue by tuanchauict** [openatx/uiautomator2#13]
I see that this supported `parent` but not `children` yet. 

https://developer.android.com/reference/android/support/test/uiautomator/UiObject2.html#getChildren()

**Comment by codeskyblue** [comment]
but you can use uiselector2 child instead of getChildren

**Comment by mingyuan-xia** [comment]
please use selector and then `child_by_` series APIs for this purpose.
see https://github.com/openatx/uiautomator2#children-and-siblings

**Comment by xxxxlr** [comment]
I submited another reference # https://github.com/openatx/android-uiautomator-server/issues/11
