### ISSUE TITLE
夜神安卓模拟器无法连接上报错

### ISSUE THREAD

**Issue by guogene** [openatx/uiautomator2#132]
## Screenshots （相关截图）
![qq 20180610220758](https://user-images.githubusercontent.com/18332496/41202361-b06f016a-6cfa-11e8-924c-35e98b37901c.png)
![qq 20180610220822](https://user-images.githubusercontent.com/18332496/41202365-c06dfd46-6cfa-11e8-8aa6-6719ffd9407d.png)
![qq 20180610220843](https://user-images.githubusercontent.com/18332496/41202396-27a31dc0-6cfb-11e8-8189-4f0be46642bf.png)

![qq 20180610220942](https://user-images.githubusercontent.com/18332496/41202393-0462e034-6cfb-11e8-8aeb-4e369eaac67e.png)

**Comment by guogene** [comment]
是不是安卓模拟器都不行一定要真机啊

**Comment by lovexiaov** [comment]
你 init 成功了没？我用自带模拟器是可以的

**Comment by guogene** [comment]
init成功了，操作都是按流程来都没问题，就连接的时候报错说代理找不到，用模拟器的adb 运行指令能用，就是uiautomator2不能用

**Comment by lovexiaov** [comment]
你把 ip 换成 127.0.0.1:62001 试试
![image](https://user-images.githubusercontent.com/5959755/41203661-d2fa4368-6d0c-11e8-8eb5-879d4a3df30d.png)

**Comment by guogene** [comment]
都尝试过，换了无效，一般这个在真机上对应着设备id，后来我换connect_usb(“127.0.0.1:62001),报错换成了找不到adb_path

**Comment by codeskyblue** [comment]
那adb装了吗

**Comment by guogene** [comment]
已经解决了，不用模拟器自带的ADB，使用SDK的adb可以连接
