### ISSUE TITLE
RuntimeWarning: uiautomator2 raise exception -32001 Jsonrpc error: <android.support.test.uiautomator.StaleObjectException> data: android.support.test.uiautomator.StaleObjectException

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#134]
我自己的脚本没有raise exception，uiautomator2 raise了。
![image](https://user-images.githubusercontent.com/20472976/41279988-76f5c83a-6e60-11e8-9f65-ed2c42d1097b.png)

## Versions (版本)
通过`pip show uiautomator2`可以获取到
![image](https://user-images.githubusercontent.com/20472976/41280061-9be95da0-6e60-11e8-8482-78eb57abcf3f.png)

## Issue and steps to reproduce (复现步骤)
这个，我就是跑脚本中出现的，具体步骤没有太特别，自己的脚本没报错

**Comment by codeskyblue** [comment]
deplicated with https://github.com/openatx/uiautomator2/issues/138
