### ISSUE TITLE
获取child有点歧义

### ISSUE THREAD

**Issue by zzwwws** [openatx/uiautomator2#137]
父布局无法准确知道children的个数，child方法返回的结果不是预期的。
比如父布局是一个ListView，里面有6个item，每个item都是LinearLayout(id= R.id.lly1)通过以下方法：

ListView.child(className='android.widget.LinearLayout')
返回的是第一个LinearLayout而不是一个数组，预期应该是有6个元素的数组。求教正确的使用方法。
@codeskyblue

**Comment by codeskyblue** [comment]
加个index

**Comment by zzwwws** [comment]
ListView.info['childCount']返回的数量并不是6
ListView.child(className='android.widget.LinearLayout').count是1

搞不清这里的逻辑是什么

**Comment by codeskyblue** [comment]
嗯，刚试了是，这里确实是个问题。不错的issue。 fixed in https://github.com/openatx/android-uiautomator-server/commit/babc434581a1bc1947b5a9cccd0eee9de96196dd
apk等下还要重新打个版本号

**Comment by codeskyblue** [comment]
已修复

**Comment by zzwwws** [comment]
问题没有修复
ListView.info['childCount']返回的数量是正确的
但是ListView.child(className='android.widget.LinearLayout', instance=2) instance没有生效，通过日志发现，android-uimonitor-server里拿到的instance总是0。还有个问题，apk升级后，UiObjectNotFoundException出现的概率很高

  麻烦@codeskyblue 再看下

**Comment by codeskyblue** [comment]
not found exception是因为instance不生效的问题吗

**Comment by zzwwws** [comment]
找到问题了，ListView下面的层级是这样的
![image](https://user-images.githubusercontent.com/2063712/42012372-6a46fd0e-7aca-11e8-8b4d-03e5ab7c5a34.png)

ListView.info['childCount']返回的个数不是直系son的个数，而是第一个son下面嵌套的LinearLayout个数，包括grandson。似乎还是xiaocong/uiautomator里的问题

**Comment by zzwwws** [comment]
应该是测的时候没有考虑嵌套这种情况

**Comment by codeskyblue** [comment]
instance就是应该包含grandson的

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/42120222-795ead4c-7c4a-11e8-8437-51a23fa569a5.png)

官方文档说的也不怎么详细，没有说是子层级还是包含子子层级。

**Comment by codeskyblue** [comment]
其实你还可以这么用，最近支持xpath了。

```python
elements = d.xpath("//android.widget.ListView//android.widget.LinearLayout").all()
print(len(elements))
```
