### ISSUE TITLE
shell命令输入路径时，反斜杠被屏蔽

### ISSUE THREAD

**Issue by 404div** [openatx/uiautomator2#139]
d.shell("adb install E:\\\\python\\\\bnn\\\\test.apk"）
提示找不到apk
查看控制台信息是因为反斜杠被删除掉了

请帮忙查看一下

## Versions (版本)
0.1.3.dev5
## Issue and steps to reproduce (复现步骤)

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/28550842/41831982-9980b5f6-787c-11e8-8b23-d3c7d61caaef.png)

![image](https://user-images.githubusercontent.com/28550842/41831960-847eafa0-787c-11e8-9f90-13dddf1050f4.png)

## Additional Details （其他信息）

**Comment by 404div** [comment]
OK，已解决...
原来要\\\转义

**Comment by codeskyblue** [comment]
没有这种操作  d.shell("adb install") 实际上相当于 `adb shell adb install`

**Comment by 404div** [comment]
哈哈哈，好的，谢谢，是我拙计了
