### ISSUE TITLE
uiautomator apk能增加启动uiautomator选项吗？

### ISSUE THREAD

**Issue by zzwwws** [openatx/uiautomator2#141]
给的demo里只有停止uiautomator选项，没有启动选项，希望能加一下方便一点。另外请问下uiautomator应用的项目地址在哪？文档里没有看到

**Comment by codeskyblue** [comment]
细心看

**Comment by zzwwws** [comment]
看到了，在这 [uiautomator-server](https://github.com/openatx/android-uiautomator-server)

**Comment by codeskyblue** [comment]
那个启动的功能你可以提个pr

**Comment by codeskyblue** [comment]
atx-agent进程有权限，给他发个http请求就好了

**Comment by codeskyblue** [comment]
现在这个项目issue太多了，提个pr来弄吧。
