### ISSUE TITLE
scroll滚动有点疑问

### ISSUE THREAD

**Issue by zzwwws** [openatx/uiautomator2#142]
d(scrollable=True).scroll.vert.forward(steps=100)，无论怎么设置step或者max_swipes，滚动的距离都是1200像素左右，唯一的差别就是滑动速度的快慢。
这里steps和max_swipes两个参数比较困惑，不是预期的行为

**Comment by codeskyblue** [comment]
steps相当于滑动的速度，max swipes相当于滑动的次数

**Comment by zzwwws** [comment]
「steps相当于滑动的速度，max swipes相当于滑动的次数」
- - - - - - - - - - - - - - -
滑动一次是多少距离呢？能否以像素为单位。我测试下来，steps越大滑动速度越慢、max_swipes则没有任何作用。

**Comment by codeskyblue** [comment]
说错了 steps相当于一次滑动的总时间 印象中是50ms

**Comment by codeskyblue** [comment]
有专门的scroll接口，另外UiObject和UiObject2使用场景不一样，不是能更换就可以解决的

**Comment by LPVP** [comment]
scroll.to直到某个元素出现，如果给定的元素一直没有出现，已经滑倒底部了，能否实现提示ui object not found异常，有没有办法判断已经滑倒最底部了

**Comment by codeskyblue** [comment]
是否存在你试试可以用exists判断

**Comment by kwdiwt** [comment]
> 了解了，steps一次滑动是5ms，但forward方法按照文档的解释： ` * Performs a forward scroll with the default number of scroll steps (55). If the swipe direction is set to vertical, then the swipes will be performed from bottom to top. If the swipe direction is set to horizontal, then the swipes will be performed from right to left. Make sure to take into account devices configured with right-to-left languages like Arabic and Hebrew.` 滑动的过程是从scrollable控件的bottom滑动到top，耗时steps*5ms，所以steps越大滑的越慢。这个方法不能控制滑动距离，也不知道是否到底部
> 
> `def swipe(self, fx, fy, tx, ty, duration=0.5)` 可以控制滑动距离，但同样也无法知道是否滑动到底部
> 
> AutomatorService实现层是不是考虑用UiObject2好一点？

这文档哪找的，我发现这个项目好像是没有api文档的。。
