### ISSUE TITLE
是否计划对xpath提供完整支持？

### ISSUE THREAD

**Issue by jk234ert** [openatx/uiautomator2#147]
## Versions (版本)
0.1.3dev9

## Issue and steps to reproduce (复现步骤)

首先非常感谢新加入了xpath的支持，目前似乎只实现了wait(),click(),all()等有限的几个功能，后续会继续扩展xpath的支持吗？会的话，是否会支持Selector现在的所有功能？

**Comment by codeskyblue** [comment]
最好把具体的使用场景和需求提出来。目前只要是没有需求进来，就不会扩充了
