### ISSUE TITLE
python -m uiautomator2 init  导致手机上打开一个网页，这个能去掉不？会影响浏览器的自动化测试

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#153]
python -m uiautomator2 init  导致手机上打开一个网页，这个能去掉不？会影响浏览器的自动化测试

**Comment by codeskyblue** [comment]
这个命令只是用来对全新的手机做预处理的。`connect_usb`函数已经可以自动修复atx-agent没启动的问题了

**Comment by flyfire100** [comment]
好的，谢啦
