### ISSUE TITLE
怎么处理弹出窗口和toast？

### ISSUE THREAD

**Issue by jamesding** [openatx/uiautomator2#16]
**怎么处理弹出窗口和toast？**
有什么Api吗
![image](https://user-images.githubusercontent.com/1769770/33983783-625f8ce2-e0f0-11e7-8c8f-72341f0b7daa.png)

**Comment by codeskyblue** [comment]
记录一下： <http://www.dianyue.me/archives/909/0epgkv1j9cbomr83/> UiAutomator2.0抓取和弹出Toast

**Comment by codeskyblue** [comment]
toast已经支持

**Comment by ushang000** [comment]
如果是自动化测试多个app，怎么定位那个“X”号，关闭弹窗呢？ back键是不管用的
