### ISSUE TITLE
为什么现在 初始化后 拔掉usb atx-agent 会停掉 远程wifi连不上

### ISSUE THREAD

**Issue by DevineLiu** [openatx/uiautomator2#160]

**Comment by DevineLiu** [comment]
型号  pixel    8.0.0 发现其他没有

**Comment by codeskyblue** [comment]
荣耀v9 8.0.0也有这问题

**Comment by codeskyblue** [comment]
改成仅充电模式下，重新init就不会被杀掉了。（原因未知，可能系统就是设计成这样的）
![image](https://user-images.githubusercontent.com/3281689/42487181-6bb65646-8432-11e8-82bd-c1a25c8af019.png)

**Comment by DevineLiu** [comment]
pixel没有这个选项

**Comment by DevineLiu** [comment]
不过 理论上是三条链接 线路吧 localhost adb  wifi  前两条断了 wifi也可以用吧 
是什么导致监听wifi的atx挂断了？

**Comment by codeskyblue** [comment]
群里的回答: 仅充电模式 是可以脱机运行脚本和测试apk的 但是MTP模式就不行

**Comment by Cataglyphis** [comment]
我这边的现象是：(机型 Honor 9)
1. 插上 USB 线做完 init 后，atx-agent 可以正常运行
2. 拔掉 USB 线后，也一切正常
3. 再次将 USB 线插到其他设备上，则 atx-agent 会退出

能否设置该 service 一直在后台运行？

**Comment by codeskyblue** [comment]
atx-agent是命令行运行的

**Comment by Cataglyphis** [comment]
@codeskyblue 我这边暂时用如下的方式来workaround：
1. 连接电脑，执行init来安装apk，初始化atx-agent，并设置adb的端口为5555，adb tcpip 5555
2. 将手机插在其他设备上 (目前有这种需求)，此时atx-agent无法运行，相应的weditor同样无法使用
3. 此时手机的ip地址已知，假设为device_ip，利用adb connect device_ip连接设备
4. adb shell /data/local/tmp/atx-agent -d重新运行atx-agent
5. 之后atx-agent则可以正常使用

**Comment by DevineLiu** [comment]
我试着用 nohup  atx-gent -d 忽略 SIGHUP信号 ，但是当拔去 usb时还是掉了，初始化设置adb tcpip 来拉起atx-agent 或许不错

**Comment by codeskyblue** [comment]
恩，如果这样的话，倒是可以直接在apk里面加个启动atx-agent的功能

**Comment by lroc** [comment]
apk 启动atx-agent 是需要root权限的，否则即使开了，也不能启动测试，需要跨进程访问

**Comment by DevineLiu** [comment]
我用ansole 启动过atx-agent倒是可以用

**Comment by freedom-wy** [comment]
oppo r9 初始化没问题，用usb线连接atx-agent是启动的，通过u2控制手机和app，通过weditor获取app控件也是没有问题的。
但是拔掉usb线当atx-agent停止运行时，通过u2.connect(ip地址)或重启设备后，直接通过u2.connect(ip地址)去连接手机设备时，显示

`
```
[I 200418 23:28:26 __init__:373] wait for device(192.168.1.8), left(9.9s)
[I 200418 23:28:28 __init__:373] wait for device(192.168.1.8), left(7.9s)
[I 200418 23:28:30 __init__:373] wait for device(192.168.1.8), left(5.9s)
[I 200418 23:28:32 __init__:373] wait for device(192.168.1.8), left(3.9s)
[I 200418 23:28:34 __init__:373] wait for device(192.168.1.8), left(1.9s)
Traceback (most recent call last):
  File "/home/user1/u2_project/u2_selector.py", line 5, in <module>
    d = u2.connect("192.168.1.8")
  File "/home/user1/u2_project/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 124, in connect
    return connect_usb(addr)
  File "/home/user1/u2_project/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 168, in connect_usb
    d._init_atx_agent()
  File "/home/user1/u2_project/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 330, in _init_atx_agent
    raise RuntimeError("USB device %s is offline" % self._serial)
RuntimeError: USB device 192.168.1.8 is offline
```
`
请问如何解决呢？

**Comment by baijun9206** [comment]
> oppo r9 初始化没问题，用usb线连接atx-agent是启动的，通过u2控制手机和app，通过weditor获取app控件也是没有问题的。 但是拔掉usb线当atx-agent停止运行时，通过u2.connect_wifi(ip地址)或重启设备后，直接通过u2.connect_wifi(ip地址)去连接手机设备时，通过查看agent_alive,显示的是false 请问如何解决呢？
> 
> 目前设置过电源选项和手机管家中的设置项，设置了atx开机启动，但手机重启后，只能通过connect连接USB或通过adb shell 启动atx-agent。
> 
> 手机型号oppo r9 plus 未root

我俩是相同的问题

**Comment by Xander-97** [comment]
> > oppo r9 初始化没问题，用usb线连接atx-agent是启动的，通过u2控制手机和app，通过weditor获取app控件也是没有问题的。 但是拔掉usb线当atx-agent停止运行时，通过u2.connect_wifi(ip地址)或重启设备后，直接通过u2.connect_wifi(ip地址)去连接手机设备时，通过查看agent_alive,显示的是false 请问如何解决呢？
> > 目前设置过电源选项和手机管家中的设置项，设置了atx开机启动，但手机重启后，只能通过connect连接USB或通过adb shell 启动atx-agent。
> > 手机型号oppo r9 plus 未root
> 
> 我俩是相同的问题



> > oppo r9 初始化没问题，用usb线连接atx-agent是启动的，通过u2控制手机和app，通过weditor获取app控件也是没有问题的。 但是拔掉usb线当atx-agent停止运行时，通过u2.connect_wifi(ip地址)或重启设备后，直接通过u2.connect_wifi(ip地址)去连接手机设备时，通过查看agent_alive,显示的是false 请问如何解决呢？
> > 目前设置过电源选项和手机管家中的设置项，设置了atx开机启动，但手机重启后，只能通过connect连接USB或通过adb shell 启动atx-agent。
> > 手机型号oppo r9 plus 未root
> 
> 我俩是相同的问题

我也是  OPPO R9
