### ISSUE TITLE
初始化时候失败

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#168]
Failed to install app-uiautomator.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1042182060.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]

初始化时候失败了，报上面的错误

**Comment by codeskyblue** [comment]
这是啥手机，安装个apk还要证书呀

**Comment by flyfire100** [comment]
不知道怎么回事，后面换了测试手机，估计是版本操作系统版本太低了
