### ISSUE TITLE
exists 有时判断不出来

### ISSUE THREAD

**Issue by WeihuaGu** [openatx/uiautomator2#170]
比如存在这个控件，exists判空，但是再执行一次exists()，或者先sleep上一两秒就行了

**Comment by codeskyblue** [comment]
exists印象中还有timeout这个参数

**Comment by WeihuaGu** [comment]
哦，原来可以加timeout,感谢。有个疑问，就是我用for循环调用三次肯定可以识别，但是三次for循环其实是非常快的，是不是除了时间，还有其它因素

**Comment by codeskyblue** [comment]
3次循环可能是0.3s吧

**Comment by WeihuaGu** [comment]
我试验过，有时调用exists前sleep(1)秒还是不行，但三次循环或者递归调用三次一定可以。我感觉三次循环快的多……

**Comment by Cataglyphis** [comment]
用 .exists(timeout=xxx)  靠谱些

**Comment by lovexiaov** [comment]
我改成用wait 跟wait_gone 了:smile:
