### ISSUE TITLE
客户端 Uiautomator 使用时抛出 OOM 

### ISSUE THREAD

**Issue by RunDouble** [openatx/uiautomator2#177]
![image](https://user-images.githubusercontent.com/12154910/43435821-4707022c-94b4-11e8-86e9-4719b84457bb.png)

**Comment by codeskyblue** [comment]
这个日志挺详细的。是不是把watched开启了

**Comment by codeskyblue** [comment]
很渣的手机吗？

**Comment by codeskyblue** [comment]
开个线程，不停的调用 watchers.run()
