### ISSUE TITLE
init failed for an Android 8 device, stuck on "initialing..."

### ISSUE THREAD

**Issue by AfreenShaha** [openatx/uiautomator2#181]
Hi, after upgrading device from android 7 to Android 8, adb commands are returning device as offline.
Is it a known issue? does UIautomator2 supports Android 8 OS?

**Comment by AfreenShaha** [comment]
With multiple combinations, device is getting detected, but "python -m uiautomator2 init" command is getting stuck at line2 and not proceeding ahead with Android O: 
2018-08-01 19:04:18,447 - __main__.py:310 - INFO - Detect pluged devices: [u'17349D828F']
2018-08-01 19:04:18,447 - __main__.py:321 - INFO - Device(17349D828F) initialing ...

**Comment by mingyuan-xia** [comment]
Need more info on this. Are you able to access minicap/minitouch binarys, do you have a network proxy.
Need to report which step pauses, check:
https://github.com/openatx/uiautomator2/blob/master/uiautomator2/__main__.py#L339
