### ISSUE TITLE
某些页面元素在weditor是能看到，但使用tap却提示找不到了

### ISSUE THREAD

**Issue by huanzhijin** [openatx/uiautomator2#187]
问题：某些页面元素在weditor是能看到，但使用tap却提示找不到

个人的解决方法是用dump_hierarchy 后找到坐标再点击

为什么会出现dump_hierarchy时能找到元素，但使用uiautomator2 d(text='xx').click() 点击时会找不到？

**Comment by codeskyblue** [comment]
试试xpath

**Comment by huanzhijin** [comment]
嗯，用xpath可以

**Comment by codeskyblue** [comment]
一般来说键盘这种，hierarchy能够看到，但是Uiautomator2操作不了。原因不太清楚

**Comment by huanzhijin** [comment]
额， 不是键盘
像手机自动的虚拟按键，weditor能够看到，但是Uiautomator2也是操作不了

**Comment by susen4517x** [comment]
![image](https://user-images.githubusercontent.com/31468170/56403998-c61e4600-6296-11e9-957b-21b0ff9080d4.png)
![image](https://user-images.githubusercontent.com/31468170/56404022-e817c880-6296-11e9-8653-8ba433fdf686.png)
我也遇到 这个问题，ABC那个按钮，能获取到元素，但是点击无效，有什么解决方案么

**Comment by dydx2000** [comment]
> ![image](https://user-images.githubusercontent.com/31468170/56403998-c61e4600-6296-11e9-957b-21b0ff9080d4.png)
> ![image](https://user-images.githubusercontent.com/31468170/56404022-e817c880-6296-11e9-8653-8ba433fdf686.png)
> 我也遇到 这个问题，ABC那个按钮，能获取到元素，但是点击无效，有什么解决方案么

用 locng_click() 替代click() 。
