### ISSUE TITLE
WEditor在connect时提示Device(192.168.3.107) not attached.或Device(9cc172ea1905) not attached.

### ISSUE THREAD

**Issue by eminemisgod** [openatx/uiautomator2#190]
1.已经安装了uiautomator2、weditor
2.版本：python2.7、华为荣耀3C 安卓4.3、QQ浏览器
3.已经能够使用uiautomator2连接手机，并尝试过打开浏览器
4.在使用weditor时，不管用ip还是设备号都提示Device(xxxx) not attached
![image](https://user-images.githubusercontent.com/42352222/44045343-d4d56caa-9f5a-11e8-8ee1-cf6e4e05bc30.png)
![image](https://user-images.githubusercontent.com/42352222/44045358-dda977ea-9f5a-11e8-9501-6c86b970bf2d.png)
![image](https://user-images.githubusercontent.com/42352222/44045370-e7300f7c-9f5a-11e8-9ea8-d887c6b2bbee.png)
![image](https://user-images.githubusercontent.com/42352222/44045381-f0419824-9f5a-11e8-839f-fecbdc894843.png)

希望得到您的帮助，谢谢

**Comment by codeskyblue** [comment]
weditor版本不够新，另外init好像没成功。是不是apk没装上去

**Comment by eminemisgod** [comment]
apk安装成功了，在手机端能打开uiautomator。我pip安装时使用的是清华大学的国内源，不知道是否有影响，执行pip install -U weditor -i https://pypi.tuna.tsinghua.edu.cn/simple/时也没有安装别的版本

**Comment by mingyuan-xia** [comment]
@eminemisgod 有更新么？
