### ISSUE TITLE
支持国产模拟器逍遥安卓、海马玩、夜神

### ISSUE THREAD

**Issue by steinvenic** [openatx/uiautomator2#195]
可以支持一下模拟器吗？ adb devices 显示的是127.0.0.1:62001

**Comment by codeskyblue** [comment]
用connect_usb函数

**Comment by steinvenic** [comment]
![tim 20180819012258](https://user-images.githubusercontent.com/18524326/44301739-a10fb700-a346-11e8-87bd-9255505b2b2e.png)
试了，还是不行呢，请问大神用的什么模拟器呢？

**Comment by codeskyblue** [comment]
你这是什么模拟器。我用的genymotion

**Comment by steinvenic** [comment]
genymotion确实可以，但其他的国产模拟器逍遥安卓、海马玩、夜神都不可以直接用，需要把genymotion目录tools文件夹下adb相关文件覆盖到模拟器路径里面才可以

**Comment by codeskyblue** [comment]
这个是adb版本冲突吗

**Comment by mingyuan-xia** [comment]
@steinvenic 需要你做的：
- [ ] 确认是否需要特定版本adb才能操作与这些模拟器
- [ ] 确认minitouch/minicap驱动能否在这些模拟器上正常工作（通过adb）
- [ ] 确认uiautomator server是否能工作
- [ ] 确认atx-agent是否能正常启动并管理2和3

**Comment by mingyuan-xia** [comment]
没有更新，关
