### ISSUE TITLE
怎么设置截图后保存的图片的位置

### ISSUE THREAD

**Issue by bsshanghai** [openatx/uiautomator2#20]
image = d.screenshot() 
image.save("home.jpg")
我在pycharm 下创建一个项目。运行这两句的话，图片会存在根目录下面。
我新建一个pic文件夹。想把截图放在里面。
image.save("pic\home.jpg")
发现这样是不行...

**Comment by codeskyblue** [comment]
写绝对路径也行，你这个是pycharm的问题

**Comment by bsshanghai** [comment]
哦哦。好了好了。
