### ISSUE TITLE
Uiautomator started failed

### ISSUE THREAD

**Issue by dingronghui** [openatx/uiautomator2#21]
可以launch app,执行d.healthcheck() 出错
raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.
其他click调用也都是出现这样错误

 return self.server.jsonrpc_call(self.method, params, http_timeout)
  File "c:\users\pt001\uiautomator2\uiautomator2\__init__.py", line 255, in jsonrpc_call
    raise UiaError(self._server_jsonrpc_url, data, res.status_code, res.text, "HTTP Return code is not 200", res.text)
uiautomator2.UiaError: ('http://192.168.8.196:7912/jsonrpc/0', b'{"jsonrpc": "2.0", "id": "edc204b38751966bd204eb69b067bd6f", "method": "deviceInfo", "params": {}}', 502, '', 'HTTP Return code is not 200', '')

**Comment by dingronghui** [comment]
我自己解决了 https://github.com/openatx/android-uiautomator-server/releases 把2个apk重装下。应该是开始执行python -m uiautomator2 init 时候，uiautomator-apk 包没安装好导致的

**Comment by OnTheWay111** [comment]
估计是，我也是用这个方法解决的
