### ISSUE TITLE
联想 k520 8.0 getVisibleBounds出现死循环

### ISSUE THREAD

**Issue by codeskyblue** [openatx/uiautomator2#213]
疑似Android uiautomator库 `getVisibleBounds`出现死循环

![image](https://user-images.githubusercontent.com/3281689/45218246-82fbfd80-b2d9-11e8-88a4-559a1048707e.png)

![image](https://user-images.githubusercontent.com/3281689/45218256-8ee7bf80-b2d9-11e8-9829-8eb2204e9ada.png)

**Comment by huanzhijin** [comment]
![image](https://user-images.githubusercontent.com/15280640/45219339-226ebf80-b2dd-11e8-8a1c-9a2aad8ec6de.png)
![image](https://user-images.githubusercontent.com/15280640/45219354-2f8bae80-b2dd-11e8-8f4c-3440e6dac35c.png)
锤子 坚果 R1  8.1.0
