### ISSUE TITLE
使用xpath进行元素定位时，提示'Session' object has no attribute 'xpath'

### ISSUE THREAD

**Issue by wsj0794** [openatx/uiautomator2#214]
```
`import uiautomator2 as u2
d = u2.connect()
d.xpath("//android.widget.TextView[@text='Network & connection']").click()`
```

## Versions (版本)
0.1.2

## Screenshots （相关截图）

![image](https://user-images.githubusercontent.com/42199254/45280299-5973e980-b506-11e8-93c1-69383d36c1d5.png)

**Comment by codeskyblue** [comment]
版本太低

**Comment by wsj0794** [comment]
@codeskyblue 请问哪个版本可以，我在PyPi上有看到0.1.3版本，但这个版本即不支持python3.7.0

**Comment by codeskyblue** [comment]
python3.6 通过 `pip install --pre -U uiautomator2` 安装。安装文档上有写的

**Comment by wsj0794** [comment]
感谢感谢，目前已经将python3.7降为3.6了，结果正常
