### ISSUE TITLE
win10 执行python -m uiautomator2 init失败

### ISSUE THREAD

**Issue by Yagami2013** [openatx/uiautomator2#23]
1.pip install --pre uiautomator2已执行成功
2.连接设备谷歌nexus Android 8.1
3.日志如下：
D:\uiautomator2>python -m uiautomator2 init
2018-01-08 17:05:28,703 - __main__.py:236 - INFO - Device(84B5T15A10013698) initialing ...
D:\python\lib\site-packages\urllib3\util\ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[Kminicap.so |################################| 23.0 KiB / 23.0 KiB
[?25h2018-01-08 17:05:31,944 - __main__.py:115 - INFO - install minicap
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[Kminicap |################################| 566.5 KiB / 566.5 KiB
[?25h2018-01-08 17:05:54,605 - __main__.py:122 - INFO - install minitouch
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[Kminitouch |################################| 33.8 KiB / 33.8 KiB
[?25h2018-01-08 17:06:03,450 - __main__.py:143 - INFO - app-uiautomator.apk(1.0.6) installing ...
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\python\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[Kapp-uiautomator.apk |                                | 16.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |                                | 32.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |                                | 48.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |#                               | 64.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |#                               | 80.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |#                               | 96.0 KiB / 1.6 MiB[Kapp-uiautomator.apk |##                              | 112.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##                              | 128.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##                              | 144.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###                             | 160.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###                             | 176.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###                             | 192.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###                             | 208.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |####                            | 224.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |####                            | 240.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |####                            | 256.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#####                           | 272.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#####                           | 288.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#####                           | 304.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |######                          | 320.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |######                          | 336.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |######                          | 352.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#######                         | 368.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#######                         | 384.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#######                         | 400.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#######                [Kapp-uiautomator.apk |#####[Kapp-uiautomator.apk |##########                      | 576.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###########                     | 592.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###########                     | 608.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###########                     | 624.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |############                    | 640.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |############                    | 656.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |############                    | 672.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#############                   | 688.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#############                   | 704.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#############                   | 720.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##############                  | 736.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##############                  | 752.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##############                  | 768.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##############                  | 784.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###############                 | 800.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###############                 | 816.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###############                 | 832.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |################                | 848.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |################                | 864.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |################                | 880.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#################               | 896.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#################               | 912.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |#################               | 928.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##################              | 944.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##################              | 960.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##################              | 976.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |##################              | 992.0 KiB / 1.6 Mi[Kapp-uiautomator.apk |###################             | 1008.0 KiB / 1.6 M[Kapp-uiautomator.apk |##############################  | 1.6 MiB / 1.6 MiB

**Comment by codeskyblue** [comment]
I guess reinstall your python will resolve your problem
