### ISSUE TITLE
Would you support go wrapper in the future? Or any roadmap?

### ISSUE THREAD

**Issue by hwangjr** [openatx/uiautomator2#231]
I wonder if you would have the go wrapper in the future? For now, I think ATX is awesome, and I love the go support. thanks for your effort.

**Comment by mingyuan-xia** [comment]
Not planned. The lib is python based. Yet, its underlying `uiautomator2` server (JSONRPC server for accessibility service written in Java) and `atx-agent` (device daemon written in Go) expose REST APIs that are language-neutral. 
Here are the pointers:
https://github.com/openatx/android-uiautomator-server
https://github.com/openatx/atx-agent

**Comment by hwangjr** [comment]
https://github.com/trazyn/uiautomator-go

**Comment by mingyuan-xia** [comment]
looks good.
