### ISSUE TITLE
小米手机使用d.send_action("search") ,提示没有该属性

### ISSUE THREAD

**Issue by LPVP** [openatx/uiautomator2#233]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
AttributeError: 'Session' object has no attribute 'send_action'
```

## Versions (版本)
Version: 0.1.3.dev40

## Issue and steps to reproduce (复现步骤)
小米手机使用d.send_action("search") ,提示没有该属性

- 手机型号红米note4x
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
代码里有，需要其他信息，python版本啥的，同时请更新库重试
https://github.com/openatx/uiautomator2/blob/master/uiautomator2/__init__.py#L1308
