### ISSUE TITLE
u2/agent掉线拉起问题 以及希望有稳定的disable_popups

### ISSUE THREAD

**Issue by 1281480917** [openatx/uiautomator2#234]
1.重启手机ui2或者agent掉线（因为手机不是我一个人使用，是属于整个部门财产，很容易出现这种情况，我宁愿把它加入允许自启动名单里，是否可以有个守护程序拉起来或者有个选项让用户手动启动？）
2.
disable_popups()很实用，建议有大佬测试稳定版上来
## Versions (版本)
0.1.4.dev47

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
dup
https://github.com/openatx/uiautomator2/issues/232
1. 建议一点一个issue，issue tracker不是领导汇报报告
2. 不要重复
