### ISSUE TITLE
vivo-X6SA 5.1.1 上app_install下载完成后安装显示NOT_APK（atxagent 0.34可以, 0.45失败）

### ISSUE THREAD

**Issue by 1281480917** [openatx/uiautomator2#235]
![image](https://user-images.githubusercontent.com/16160664/47411643-03988f80-d79c-11e8-8509-c23acd69f0ee.png)

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and to reproduce (复现步骤)
vivo-X6SA手机，已经root，agent0.34都可以用app_install或者shell安装，升级到最新版本agent4.5后无法安装，报错如上图

## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/16160664/47411777-68ec8080-d79c-11e8-96a4-6774a84140cf.png)

## Additional Details （其他信息）

**Comment by 1281480917** [comment]
安卓版本5.1.1

**Comment by mingyuan-xia** [comment]
not an APK, 下载的uiautomator.apk没成功，`init` 时加上 `--mirror` 从中国源抓取apk

**Comment by 1281480917** [comment]
依然不行，安装上述方法依然报错
![image](https://user-images.githubusercontent.com/16160664/47891584-cc5a6a80-de8e-11e8-931f-49d1315f85c1.png)

**Comment by 1281480917** [comment]
![image](https://user-images.githubusercontent.com/16160664/47891853-db8de800-de8f-11e8-92ee-ed84a60bce4b.png)

**Comment by mingyuan-xia** [comment]
哪里报错，这不是success了么？

**Comment by 1281480917** [comment]
这个是安装ui2，一直都是成功的。我说的问题是在我调用app_install这个方法时，安装失败。它先是把软件下载到tmp目录下，然后tmp目录的apk就不见了。用shell安装已经下载到手机的apk也会报同样的错。apk是腾讯官网下载的腾讯管家。
![image](https://user-images.githubusercontent.com/16160664/47894600-b81e6980-de9e-11e8-906d-33094ec7f784.png)

**Comment by mingyuan-xia** [comment]
看似主要问题是download 100%后apk不见了，你看的手机上哪个目录？
“用shell安装已经下载到手机的apk也会报同样的”是用的 `pm install` ?

**Comment by 1281480917** [comment]
\sdcard\tmp目录。用pm -r install命令测试过，也是相同的问题。我没有找到ui2的日志，有atx-agent的日志，不过没啥问题
![image](https://user-images.githubusercontent.com/16160664/47900670-a77aed00-deb8-11e8-9c8e-e3753ea8c661.png)

**Comment by mingyuan-xia** [comment]
能pull下来，用工具看看是否是正确的apk么？（怕下载出错什么的）

**Comment by 1281480917** [comment]
我确定包没问题，我自己拖了几个程序上去用命令安装，都没成功，之前是可以的。这几个程序手动能装。app_install那个方法上传的包在tmp目录下，这个方法运行完就自己删了，根本没法获取
