### ISSUE TITLE
Cannot find popup in hierarchy

### ISSUE THREAD

**Issue by Jekamajor** [openatx/uiautomator2#236]
Hello!

It is not a bug, I need to check if specified popup exists but does not know how to do it.

## Versions 
Version: 0.1.4.dev47

## Issue and steps to reproduce
When I tap on Refresh button in WhatsApp, I can see the popup message "Your contact list has been updated."
I need to determine if this popup exists but I can't catch this in hierarchy. When I reproduce this in Weditor, I see this popup but cannot even select this.

When I do 
d.dump_hierarchy()
I cannot find any ierarchy node with this text.

When I do this
if d(textContains=u"update").wait(timeout=5)
it returns false

Tell me please how can I catch this popup with uiautomator2

## Screenshots
![screenshot_2](https://user-images.githubusercontent.com/44431577/47422845-47839880-d78c-11e8-9f0e-84865621e8d5.png)

![screenshot_3](https://user-images.githubusercontent.com/44431577/47423200-20799680-d78d-11e8-8a43-170e7d755daa.png)

**Comment by mingyuan-xia** [comment]
Popups are overlay windows, not detectable with hierarchy viewer, which is a limitation of Android uiautomator service itself not the tool.
