### ISSUE TITLE
[feature] console_scripts entry point :: init()

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#237]
## The idea

Within `setup.py` we should have a console script such as uia2init.

It would be cooler and easier to type.
It could receive args, by default init all devices, or accept an argument `--serial <serial>` to single out a particular device.

### Notes
Support for `python3 -m uiautomator2 init` could  be maintained.
Other arguments could be supplied too.

Possibly have a 2nd console_script to list off alive devices, that are `init'd` ?

**Comment by gamesguru** [comment]
1. init all
2. health check all
3. all_devices.service('uiautomator').stop()

Agreed these are good to give unique script names, or more suggestions? before I start pull request i wanted to ask.
@mingyuan-xia @codeskyblue

**Comment by mingyuan-xia** [comment]
not sure how well setup.py works across OS platforms. Why do you need to stop all devices' uiautomator in that?

**Comment by gamesguru** [comment]
Why
---
If I want to run uiautomatorviewer, or manual adb shell commands... it is faster when uia2 daemon is stopped. Otherwise lags. And is (would be) quite helpful when tracking and resolving issues across 1 computer with 20 android devices.

This feature would allow users to perform common commands, like `python3 -m uiautomator2 init` and a proposed `stopall`, while typing only short, easy to remember commands, e.g. `u2init` and `u2kill`

Then we can design arguments, e.g. --serial, or --model with rough match via regex.

How
---
Difference between `entry_points/console_scripts` and `scripts` in setup.py, is that `scripts` only works on mac/Linux.  But `console_scripts` _also_ generates binary "uia2init.exe" file which can be called on Windows' cmd line.

You can try that with `pip3 install nutri` and then see `nutri -h` is working across all OS platforms.
See [setup.py](https://github.com/gamesguru/nutri/blob/ffb8c385872310e64f9706c5eb0633f5d5dd8e99/setup.py) file for example on how to do this.  
```
    entry_points={
        'console_scripts': [
            'nutri=libnutri.nutri:main',
        ],
    },
```
`nutri` is what you type into command line,
`libnutri` is target folder,
`nutri.py` is main python file therewithin, and
`main` is target function to call out.

With uiautomator2 project, the `init` function nested under `MyFire` object, it is possibly correct: `'u2init=__main__.MyFire.init',`

But someone should test this, who has push access to the PyPI page.

**Comment by mingyuan-xia** [comment]
ok stopall makes sense. About retrofitting `--serial`, right now there is an ugly workaround as Fire might interpret args as a float: https://github.com/openatx/uiautomator2/blob/master/uiautomator2/__main__.py#L334
As we are working to change that, we might also wipe out this stupid thing as well.
Need to get to know nutri first.

**Comment by mingyuan-xia** [comment]
ok I only had some experience with click and the basic argparser, none with fire and nutri. I am open to a more intuitive and clear cmdline parser.

**Comment by codeskyblue** [comment]
actually there is an entry script named u2cli, sometimes it works sometimes not

**Comment by gamesguru** [comment]
so should we do the entry point, or no??  I can start it
