### ISSUE TITLE
current_app函数更新后activity名称多了一个PackageName

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#238]
## Versions (版本)
0.4.2与0.4.5

## Issue and steps to reproduce (复现步骤)
从0.4.2升级到0.4.5, d.current_app()['activity']获取的结果不一致，
0.4.2版本类似“.MainActivity”，0.4.5版本类似“com.xxx.xxx\.MainActivity”
相比较而言，多了一个app的PackageName。
查看两个版本的代码，current_app函数有改动，后续是以0.4.5方式为准，还是会回退到0.4.2的方式？

**Comment by codeskyblue** [comment]
暂定决定不退回了。多了一个package name影响应该也不大
