### ISSUE TITLE
如何获取元素的bounds信息？

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#248]
我现在有个问题，要获取视频框中的内容，我的想法是先整个图片进行截图，然后再截取视频框中的区域，但是不知道怎么获取视频框的大小，目前我们有接口可以获取元素的bounds吗？

**Comment by flyfire100** [comment]
自己解析xml也可以获取，只是比较麻烦

**Comment by mingyuan-xia** [comment]
文档里有 页内搜索bounds
