### ISSUE TITLE
手机安装uiautomator后，其他电脑uiautomatorviewer.bat无法抓取到控件

### ISSUE THREAD

**Issue by dc77175363** [openatx/uiautomator2#25]
![image](https://user-images.githubusercontent.com/31239879/35035007-f25cb02a-fbaa-11e7-8a97-9ecebc7ca43d.png)

**Comment by codeskyblue** [comment]
是的，这两个冲突，推荐使用weditor
https://github.com/openatx/weditor

具体使用方法可以参考这个帖子： <https://testerhome.com/topics/11357>
