### ISSUE TITLE
mac系统下uiautomator2 started failed

### ISSUE THREAD

**Issue by IRelive** [openatx/uiautomator2#253]
mac系统，python3.6.7, 安卓8.0
执行命令 python3 -m uiautomator2 init 安装显示success。
执行adb devices 也显示相对应的编号
执行pip show uiautomator2 可以正常获取信息
运行脚本
```
import uiautomator2 as u2
u = u2.connect_usb('B2NGAC6841311803')
```
报错
![20181120154914](https://user-images.githubusercontent.com/12489277/48758726-fbb90600-ecdb-11e8-9e2a-4e94d6adbd27.png)
![image](https://user-images.githubusercontent.com/12489277/48758741-10959980-ecdc-11e8-9788-d30fbe6c55d2.png)

但是通过手动命令
$ adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub \
    com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
可以启动成功！
![image](https://user-images.githubusercontent.com/12489277/48758937-96194980-ecdc-11e8-9f17-aa4c99bb65db.png)
在这个问题纠结了好长时间不知为何，希望大佬能看下，在此万分感谢！

**Comment by miaomiaot** [comment]
我在windows系统下也是出现了这个错误，是更新到最新版本后出来的，换回4月份的旧版本就可以正常连接。

**Comment by codeskyblue** [comment]
pip show uiautomator2 看看版本号，然后看看init的输出是啥

**Comment by miaomiaot** [comment]
今天又更新了一次，已经可以正常连接了，是已经修复过这个bug了？

**Comment by IRelive** [comment]
今天更新了下，问题确实解决了。
