### ISSUE TITLE
跑时间长了，电脑内存炸了

### ISSUE THREAD

**Issue by pengbeilin** [openatx/uiautomator2#259]
log
```
HTTPConnectionPool(host='192.168.177.101', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000000000FA7D240>, 'Connection to 192.168.177.101 timed out. (connect timeout=10)'))
```

## Versions (版本)
Name: uiautomator2
Version: 0.1.4.dev43

电脑环境 window7

## Issue and steps to reproduce (复现步骤)
大概有300条的case，然后每次执行到两百多条就直接炸了（电脑直接内存不足导致模拟器直接挂掉，然后就连接超时了），看log好像有说到截图，不知道是不是截图的问题，我case里面截图比较多，每条case执行都要截两次图 截图后也基本没有等待 直接就是跑下一条case

- 手机型号 模拟器

**Comment by codeskyblue** [comment]
然后再也恢复不了了？

**Comment by codeskyblue** [comment]
运行了多久？

**Comment by pengbeilin** [comment]
我昨天晚上又试了下，大概的情况是这样子的！
代码就下面这个 循环的去做截图操作：
用的模拟器，就是不停的去截图，截了两百次，然后我电脑内存直接涨了2G，
然后用真机去跑的时候就没有出现问题
`

if __name__ == '__main__':
    driver = u2.connect('192.168.177.101')
    for i in range(0, 200):
        print("-----index:%s" % i)
        sleep(0.2)
        driver.screenshot()
`

**Comment by wGodlike** [comment]
真机也出现了 咋解决啊？

**Comment by pengbeilin** [comment]
你加下这个Ui2的交流群，499563266
