### ISSUE TITLE
UiObject对象函数child函数偶尔会报unicode object has no attribute 'clone'错误

### ISSUE THREAD

**Issue by penghongya11** [openatx/uiautomator2#261]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```
d(className="android.widget.ListView", resourceId="android:id/list") 
 .child_by_text("设置", className="android.widget.LinearLayout")

不是每次都出现

## Versions (版本)
通过`pip show uiautomator2`可以获取到
Version: 0.1.4.dev45
## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有
![qq20181204-0](https://user-images.githubusercontent.com/39592983/49419386-8b24e580-f7c1-11e8-92d6-8b296635a63e.png)

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
完整复现方法，打开`API Demos`应用。
代码
```python
d(resourceId="android:id/list").child_by_text("App")[0]
```
就会出现异常
```
  File "/Users/codeskyblue/Workspace/uiautomator2/uiautomator2/__init__.py", line 2012, in __getitem__
    # In UIAutomator, UIObject2 has getParent() method
AttributeError: 'unicode' object has no attribute 'clone'
```
