### ISSUE TITLE
联想 乐檬K80M - init权限分配无效atx-agent启动失败

### ISSUE THREAD

**Issue by hswyxj** [openatx/uiautomator2#268]
```
python -m uiautomator2 init
```

## Versions (版本)
Version: 0.1.8.dev14

## Issue and steps to reproduce (复现步骤)
初始化最后启动 atx-agent失败，手动执行给了权限后也还是提示权限不够

- 手机型号： 联想 乐檬K80M（系统版本：安卓4.4.4）
- 错误日志：
   - python -m uiautomator2 init： ERROR - Failure, unable to get result from http://localhost:50615/version
   - 手动启动atx-agent：/system/bin/sh: /data/local/tmp/atx-agent: can't execute: Permission denied
- 代码片段： python -m uiautomator2 init

## Screenshots （相关截图）
能有尽量有
![image](https://user-images.githubusercontent.com/28854143/49714274-439dce00-fc87-11e8-899d-4b131eb176a6.png)

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/pull/163
这个已经被merge试试看新版本

**Comment by hswyxj** [comment]
还是不行
