### ISSUE TITLE
能抓取设备logcat日志吗？

### ISSUE THREAD

**Issue by dc77175363** [openatx/uiautomator2#27]
测试需要，我需要logcat日志

**Comment by mingyuan-xia** [comment]
`d.adb_shell('logcat', '-d')` 返回的就是

**Comment by codeskyblue** [comment]
还需要加一个获取实时命令行输出的接口

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2#shell-commands

**Comment by codeskyblue** [comment]
先不用关，毕竟没写完

**Comment by codeskyblue** [comment]
增加了一个持续获取命令输出的命令 `d.shell("logcat", stream=True)`
