### ISSUE TITLE
华为在手机解锁的时候页面有问题

### ISSUE THREAD

**Issue by cotyyang** [openatx/uiautomator2#274]
![0fbab0a090ebcf05dae541a6c3dfaa2](https://user-images.githubusercontent.com/34573329/49913354-54895200-fec8-11e8-9623-257f373d2fa9.jpg)
![ee6aff7fabe3f9a2624be8eda1650e3](https://user-images.githubusercontent.com/34573329/49913358-5521e880-fec8-11e8-9852-1b796a1f9855.png)
手机上显示的和weditor不同

**Comment by codeskyblue** [comment]
具体的型号

**Comment by cotyyang** [comment]
> 具体的型号

P20

**Comment by mingyuan-xia** [comment]
发现过同样问题，华为新机型，由于安全考虑，解锁屏不能投屏，测试机自行去掉
