### ISSUE TITLE
请问有flick方法吗

### ISSUE THREAD

**Issue by l764191074** [openatx/uiautomator2#283]
## 请问有flick方法吗？
这个方法，相当于手在屏幕上使劲滑动了一下，通常用来滑动列表页，例如今日头条列表页，一页一页的滑动太慢了，用flick一下子就可以滑动一大截，我看appium是有个方法的，问一下有没有对应的api

**Comment by mingyuan-xia** [comment]
没有，可以PR

**Comment by codeskyblue** [comment]
@l764191074 你试试
```python
# 右滑
d.swipe(0, 0.5, 0.9, 0.5, steps=2)
```

是这个效果吗？

**Comment by l764191074** [comment]
> @l764191074 你试试
> 
> ```python
> # 右滑
> d.swipe(0, 0.5, 0.9, 0.5, steps=2)
> ```
> 
> 是这个效果吗？

其实是向上滑，翻列表页

**Comment by codeskyblue** [comment]
上滑动

```python
d.swipe(0.5, 0.9, 0.5, 0.1, steps=2)
```
