### ISSUE TITLE
atx-agent 0.5.2, apk 1.1.7, wifi连接后将apk放到后台后alive状态为false

### ISSUE THREAD

**Issue by Cataglyphis** [openatx/uiautomator2#284]
手机：华为荣耀9
系统：android 8.0
atx agent版本：0.5.2
apk版本：1.1.7
uiautomator2：0.1.10.dev1
问题：
1. 用wifi连接手机与apk
2. 初始化uiautomator2连接为d，操作手机上app，发现经常出现timeout异常
3. 查看d.alive状态发现为false，说明uiautomator service已经不在；d.agent_alive状态正常
4. 调用d.reset_uiautomator方法后，重新启动uiautomator service，d.alive状态恢复正常
5. 将atx app放到后台后，一段时间d.alive状态又变为false
6. 用USB连接未发现该问题

手机log：
01-03 10:06:22.119  1659  2114 I PGServer: report state:6 event type:2 pid:0 uid:10139 pkg:com.github.uiautomator to pid: 1192
01-03 10:06:22.120  1659  2114 I ash     : Unfreeze com.github.uiautomator OK !
01-03 10:06:22.123  1192  1673 I PGManagerService: proxyBroadcast:[com.github.uiautomator] proxy:false
01-03 10:06:22.124  1659  2114 I ash     : unproxy com.github.uiautomator broadcast OK !
01-03 10:06:22.125  1659  2114 D APwPowerPolicy: gps pkg: com.github.uiautomator uid:10139 duration:0
01-03 10:06:22.126  1192  1673 D GpsFreezeProc: removeFreezeProcess pkg:com.github.uiautomator
01-03 10:06:22.128  1659  2114 I ash     : unproxy gps:com.github.uiautomator,uid:10139,result:true
01-03 10:06:22.132  1659  2114 D APwPowerPolicy: gps pkg: com.github.uiautomator uid:10139 duration:0
01-03 10:06:22.135  1659  2114 I ash     : nap package: com.github.uiautomator, visible: false
01-03 10:06:32.177  1659  2114 I ash     : com.github.uiautomator skips not important notification
01-03 10:06:32.185  1659  2114 I ash     : com.github.uiautomator { doze duration=10055 UptimeDuration=10055 } transition to: hibernation reason:app_type_unknown unknown_state unknown_state
01-03 10:06:32.185  1659  2114 I ash     : perform hibernation actions: com.github.uiautomator
01-03 10:06:32.189  1659  2114 I ash     : not perform alarm action:com.github.uiautomator
01-03 10:06:32.191  1192  5799 D GpsFreezeProc: addFreezeProcess pkg:com.github.uiautomator
01-03 10:06:32.192  1659  2114 I ash     : proxy gps:com.github.uiautomator,uid:10139,result:true
01-03 10:06:32.192  1659  2114 I ash     : perform delay action: com.github.uiautomator
01-03 10:06:32.196  1659  2114 I PGServer: report state:6 event type:1 pid:0 uid:10139 pkg:com.github.uiautomator to pid: 1192
01-03 10:06:32.198  1659  2114 I ash     : Freeze com.github.uiautomator OK !
`01-03 10:06:32.208  1659  2114 I ash     : close sockets >> com.github.uiautomator, uids : [10139]`
01-03 10:06:32.222   760   787 I AwareLog: HibSTrategy::HibStrategySwapCandidateProcessAdd packagename com.github.uiautomator
01-03 10:06:32.312   760  3187 I AwareLog: HibStrategy::HibStrategySwapCandidateProcessRemove packagename is com.github.uiautomator

**Comment by mingyuan-xia** [comment]
电池优化，看看配置里面能不能不优化

**Comment by Cataglyphis** [comment]
@mingyuan-xia 在power设置中，允许atx-agent & apk 自启动，目前看来可以解决该问题
