### ISSUE TITLE
稳定出现的bug

### ISSUE THREAD

**Issue by 474420502** [openatx/uiautomator2#287]
```
.scroll.to 执行这个语句. 在他慢慢搜索元素的过程, 稳定出现 这个. atx挂了
HTTPConnectionPool(host='127.0.0.1', port=40847): Read timed out. (read timeout=60)

```
## Versions (版本)
Name: uiautomator2
Version: 0.1.10.dev16
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /home/eson/tools/uiautomator2
Requires: docopt, fire, humanize, logzero, progress, pure-python-adb, requests, retry, six, whichcraft

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快
 ses(className="android.widget.TextView", text=t).scroll.to(className="android.widget.TextView", text=t, max_swipes=5000)

- 手机型号? 魅族Note
- 错误日志? atx不知道在那
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
获取下 `/sdcard/atx-agent.log` 贴一下

**Comment by codeskyblue** [comment]
嗯，知道怎么回事了。 因为是用的http请求的方式跟com.github.uiautomator通信的，python代码里面写的默认是90s超时，超时之后就会认为com.github.uiautomator 故障了，然后决定重启。
处理方法，暂时还没思路

**Comment by 474420502** [comment]
我明白了, 我本来就猜是有什么超时了. 我改其他方法实现一样的东西! thanks @codeskyblue

**Comment by mingyuan-xia** [comment]
已经添加到wiki常见问题
https://github.com/openatx/uiautomator2/wiki#%E5%AF%B9%E4%BA%8E%E9%95%BF%E6%97%B6%E9%97%B4scroll%E4%B8%AD%E9%97%B4uiautomator2%E4%BC%9A%E9%87%8D%E5%90%AF
