### ISSUE TITLE
请问有提供实时投屏功能吗？貌似目前的“远程投屏”并不能使用

### ISSUE THREAD

**Issue by oujibahei** [openatx/uiautomator2#289]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
直接手机IP + 7912端口，浏览器打开，啥都没有吗？

**Comment by oujibahei** [comment]
浏览器显示无法打开（pixel 2和三星S7）

**Comment by mingyuan-xia** [comment]
atxagent服务起来没

**Comment by StarMX** [comment]
shell 进去命令行启动minicap 看报什么错

**Comment by codeskyblue** [comment]
问题不好查，有需要再打开吧
