### ISSUE TITLE
安装如何获取安装信息？

### ISSUE THREAD

**Issue by dc77175363** [openatx/uiautomator2#29]
app_install只返回了包名，没有返回类似 安装J:\apks\jzx\jzx_agent_103652_yyb_ysdk_dalan_177_1.9.2_20180118_16885.apk
	pkg: /data/local/tmp/jzx_agent_103652_yyb_ysdk_dalan_177_1.9.2_20180118_16885.apk

Success
假如包有问题，不清楚为什么安装失败。

**Comment by dc77175363** [comment]
{u'message': u'downloading', u'id': u'2', u'titalSize': 407992690, u'copiedSize': 49152}

        Returns:
            packageName

        Raises:
            RuntimeError
明白了

**Comment by codeskyblue** [comment]
好像版本有点低，可以升级下
