### ISSUE TITLE
how can i catch connect error

### ISSUE THREAD

**Issue by mengdodo** [openatx/uiautomator2#290]
my devices atx-agent process is not running before i use u2.connect() function,
how can i catch this error and do something?

such as:

    try:  
       d = u2.connect')   
    except (ConnectionRefusedError) as e:  
       print('begin do python -m uiautomator2 init')  
       os.system("source activate py36 && cd /project_path && python -m uiautomator2 ini")

but This is invalid.
please help me @codeskyblue  ,thx!

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/51238446-e695e600-19b1-11e9-80a1-c341a67f407e.png)
代码写错了
