### ISSUE TITLE
为什么不同设备获得端口是一样的？

### ISSUE THREAD

**Issue by mingyanzou** [openatx/uiautomator2#293]
```
    for sn in sns:
        d = u2.connect_usb(sn)
```

uiautomator2 object for 127.0.0.1:44677 init 0430a6cc2523439a
uiautomator2 object for 127.0.0.1:44677 init 59e66a42
uiautomator2 object for 127.0.0.1:44677 init 753db2dd
uiautomator2 object for 127.0.0.1:44677 init dc5bb868

**Comment by mingyanzou** [comment]
@mingyuan-xia @codeskyblue 有遇到过这个问题吗?

**Comment by codeskyblue** [comment]
看起来像个bug

**Comment by wangshuwen1107** [comment]
我mac电脑上也有相同问题

**Comment by wangshuwen1107** [comment]
![image](https://user-images.githubusercontent.com/23114635/57193015-7d8aac00-6f69-11e9-8f3b-2416f063b775.png)

**Comment by codeskyblue** [comment]
看代码应该是已经修复了，提供下uiautomator2版本号。

**Comment by codeskyblue** [comment]
有问题再Reopen

**Comment by wangshuwen1107** [comment]
没问题了uiautomator2的版本不对 谢谢
