### ISSUE TITLE
cannot identify image file <_io.BytesIO object at 0x043B7D50>（附log）

### ISSUE THREAD

**Issue by Botreechan** [openatx/uiautomator2#294]
## Versions (版本)：
Version: 0.1.10.dev24

## Issue and steps to reproduce (复现步骤)：
1.dumpUI时报标题错误 
2.手机打开http://127.0.0.1:7912/screenshot/0可以看到当前浏览器界面的截图

手机：小米6

## Screenshots ：
![image](https://user-images.githubusercontent.com/23278447/51156234-8de12300-18b5-11e9-88b8-545c9f126b58.png)

## log：
[atx-agent.log](https://github.com/openatx/uiautomator2/files/2757916/atx-agent.log)

**Comment by codeskyblue** [comment]
已经见不少人说这个问题，可以头疼的是我这里就是无法复现。
你先升级weditor到最新试试

```
pip install -U --pre weditor
```

**Comment by Botreechan** [comment]
> 已经见不少人说这个问题，可以头疼的是我这里就是无法复现。
> 你先升级weditor到最新试试
> 
> ```
> pip install -U --pre weditor
> ```

我也没找到复现方法，重启手机后莫名其妙的又好了。

**Comment by Non-Smoke** [comment]
我连接的时候都会出现这种情况

**Comment by Non-Smoke** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
