### ISSUE TITLE
Chrome Webview Implementation is not working

### ISSUE THREAD

**Issue by thlengane** [openatx/uiautomator2#299]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

## Code
-----in python console-----
---from uiautomator2 import connect as conn
```
>>> d = conn()
>>> xml=d.dump_hierarchy()
>>> xml.find('I have')
-1
>>>
```

## Versions (版本)

Name: uiautomator2
Version: 0.1.11.dev1
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: c:\python\lib\site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, pure-python-adb, logzero, pillow, lxml
Required-by:

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

On Android 7.1 and above, I am experiencing a weird issue when I start the uiautomator2 server. After starting it, the xml dump does not have all the ui on the screen but when I stop it and do _adb shell uiautomator dump_, I see them. Also in the python console, the _d.dump_hierarchy()_ is not showing all elements on the screen. Lastly, when the server is started, _adb shell uiautomator dump_ somehow does not work.

With all this, it says element not found whenI try to click it.

I have tested this on the Oneplus 5T with Android P and Samsung J7 Pro. Everything works fine in all the Android devices with OS 6 and below. Here are the steps to reproduce it.

-----in command prompt-----
```
1. adb shell /data/local/tmp/atx-agent server --daemond
2. adb shell uiautomator dump
    (prints nothing, no file is created)

3. adb shell /data/local/tmp/atx-agent server --stop
4. adb shell uiautomator dump
    (Creates file and print --> UI hierchary dumped to: /sdcard/window_dump.xml)

5. adb shell /data/local/tmp/atx-agent server --daemond
6. adb shell uiautomator dump
    (prints nothing, no file is created)
```

-----in python console-----

```
>>> from uiautomator2 import connect as conn
>>> d = conn()
>>> xml=d.dump_hierarchy()
>>> xml.find('I have')
-1
>>>
```

## Screenshots （相关截图）
![test](https://user-images.githubusercontent.com/7370719/51757072-26a04b80-20cb-11e9-9142-65a8850b4718.png)
![screen_xml](https://user-images.githubusercontent.com/7370719/51757509-34a29c00-20cc-11e9-9a72-c3fd6f21fcfe.png)
![weditor](https://user-images.githubusercontent.com/7370719/51827097-43b66380-22f1-11e9-82d4-4b6adfc0023e.png)

## Additional Details （其他信息）

**Comment by thlengane** [comment]
So here is what I have found out...

1. From Android 7.1, Android moved to using Chrome WebView instead of the default Android System WebView to save battery (I assume)
2. By default, Chrome WebView would be selected and you would not be able to select the Old Android System WebView
3. Now, to get around the above problem, you have to uninstall or disable Chrome. Automatically, the system will revert back to Android System WebView.
4. Everything will start working as normal and you will be able to view content inside WebView, however, if you upgrade Android System WebView in the App Store,  you will go back the problem where you can't view some of the content in WebView.
5. I only tested this on several devices that have Android System Webview 68.0.3440.91

Lastly, @codeskyblue are you aware of this? Is there a solution for this instead of the workaround I 
have? If the answer is no, could I then ask this to be a feature request to support the Chrome WebView?

![weditor1](https://user-images.githubusercontent.com/7370719/51839428-dc5cdb80-2311-11e9-8f85-0b0e9dd246cf.png)
![weditor2](https://user-images.githubusercontent.com/7370719/51839432-df57cc00-2311-11e9-9eb2-a111a645103c.png)

**Comment by codeskyblue** [comment]
The issue about `adb shell uiautomator dump` is not working is not a bug, you have to close the uiautomator server before using `uiautomator dump`

Related (中文) with <https://github.com/openatx/uiautomator2/wiki#%E5%A6%82%E4%BD%95%E5%81%9C%E7%94%A8uiautomator%E7%9A%84%E5%AE%88%E6%8A%A4%E7%A8%8B%E5%BA%8F-how-to-stop-uiautomator-process-keeper>

**Comment by thlengane** [comment]
Thank you for your response @codeskyblue , so the main issue was no the `adb shell uiautomator dump`, the issue was I could not get elements in the WebView on Android 7 and above. It is because android default to Chrome instead of the Old Android System WebView. If you check my response on this article, I found a work around, it works but because all future Android phones are going to use chrome Webview, is there a planned support for this?? If you already have a solution for this, how can I get it working on my side?
