### ISSUE TITLE
pip install adb模块时，在安装M2Crypto时出现openssl/err.h的文件不存在的问题

### ISSUE THREAD

**Issue by SoaringXu** [openatx/uiautomator2#304]
## Issue and steps to reproduce (复现步骤)
pip install adb

## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/47767338/52994527-d52d7700-3452-11e9-9853-57a05f62c117.png)

## Additional Details （其他信息）
我下载了M2Crypto的包解压后build也会出现一样的错误

**Comment by codeskyblue** [comment]
啊，这是啥库。uiautomator2依赖的是 pure-python-adb
