### ISSUE TITLE
设备调试完成后，几天后再连，连不上

### ISSUE THREAD

**Issue by dc77175363** [openatx/uiautomator2#31]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.20.73', port=7912): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd29b33ce50>: Failed to establish a new connection: [Errno 111] Connection refused',))
检查手机ip及应用，都有开启。为何连不上呢？

**Comment by dc77175363** [comment]
[atx-agent.log](https://github.com/openatx/uiautomator2/files/1654662/atx-agent.log)
已上传atx log，麻烦大神帮忙看看

**Comment by dc77175363** [comment]
手机连上电脑，重新执行 python -m uiautomator2 init
我想问如何保持atx-agent 稳定运行？

**Comment by codeskyblue** [comment]
代码怎么写的？

**Comment by dc77175363** [comment]
import uiautomator2 as u2
d = u2.connect('192.168.8.2')
这样子写，同样的代码，同样的设备，几天后连不上设备

**Comment by codeskyblue** [comment]
有可能是设备自己重启了，看下设备的启动时间

**Comment by dc77175363** [comment]
请问设备重启后就不行吗？如果设备重启，需要如何操作？

**Comment by mingyuan-xia** [comment]
重启后首先在电脑上 浏览器打开 `192.168.8.2:7912`（ip可能会变） 能连上才说明可以用，否则说明atx-agent死掉了，启动一下

**Comment by codeskyblue** [comment]
这个issue看样子没啥问题了，先关掉了
