### ISSUE TITLE
有些按钮使用各种点击无反应

### ISSUE THREAD

**Issue by qianyedoufulao** [openatx/uiautomator2#313]
![在红色按钮各种方式点击,APP没有反应](https://img-blog.csdnimg.cn/20190318110005818.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FpYW55ZWRvdWZ1bGFv,size_16,color_FFFFFF,t_70)

**Comment by mingyuan-xia** [comment]
1. 没有code 
2. 微信很多控件不让你定位的
补充细节，否则自动关
