### ISSUE TITLE
python -m uiautomator2 init 强制重新安装apk

### ISSUE THREAD

**Issue by zangtian2** [openatx/uiautomator2#317]
0.2.0
init初始化会强制重新安装apk，但是在oppo vivo机器上会需要输入密码，，导致自动化搞不下去，需要人工参与。。能够回滚到过去，版本一致就不要再安装

**Comment by codeskyblue** [comment]
如果已经init过一次，下次就不需要init了。直接命令行运行 `adb shell /data/local/tmp/atx-agent server -d` 就可以了。

**Comment by codeskyblue** [comment]
刚更新了下，检测到已经安装过apk就不安装了。 `pip install -U --pre uiautomator2`
