### ISSUE TITLE
关于Scroll不能搜索到低端问题

### ISSUE THREAD

**Issue by max90727** [openatx/uiautomator2#321]
我在调用child_by_text函数的时候发现了一个问题，在一个有滚动条的页面依次向下滚动搜索的时候，滚动条不能到达最底端，停在的中间的某一个位置，这导致了，最后一个条目没有办法检索到。请问这个该如何处理？

我的child_by_text调用是这么写的
```
d(className="android.support.v7.widget.RecyclerView", resourceId="
scrollbar_recycle_view") \
                .child_by_text(self.item_text, allow_scroll_search=True, className="android.widget.LinearLayout")
```

我们用的设备不是手机设备，是汽车显示器搭载Android系统，没有办法提供型号。
测试报错是
`in child_by_text
    allow_scroll_search
in wrapper
    return _method_obj(*args, **kwargs)

self = <uiautomator.JsonRPCMethod object at 0x05F9DF90>
args = ({'mask': 2097168, 'childOrSibling': [], 'childOrSiblingSelector': [], 'className': 'android.support.v7.widget.Recycle... 16, 'childOrSibling': [], 'childOrSiblingSelector': [], 'className': 'android.widget.LinearLayout'},
'Pressure', True)
kwargs = {}
data = {'id': 'ee7145b5ca766febf66c34ad06a902cf', 'jsonrpc': '2.0', 'method': 'childByText', 'params': ({'mask': 2097168, 'ch...16, 'childOrSibling': [], 'childOrSiblingSelector': [], 'className': 'android.widget.LinearLayout'}, 'Pressure', True)}
jsonresult = {'error': {'code': -32001, 'data': 'for text= "Pressure"', 'message': 'android.support.test.uiautomator.UiObjectNotFoundException'}, 'id': 'ee7145b5ca766febf66c34ad06a902cf', 'jsonrpc': '2.0'}
res = <urllib3.response.HTTPResponse object at 0x05F9D870>

        def __call__(self, *args, **kwargs):
            if args and kwargs:
                raise SyntaxError("Could not accept both *args and **kwargs as JSONRPC parameters.")
            data = {"jsonrpc": "2.0", "method": self.method, "id": self.id()}
            if args:
                data["params"] = args
            elif kwargs:
                data["params"] = kwargs
            jsonresult = {"result": ""}
            if os.name == "nt":
    #             print 'start post ' + str(data)
                res = self.pool.urlopen("POST",
                                        self.url,
                                        headers={"Content-Type": "application/json"},
                                        body=json.dumps(data).encode("utf-8"),
                                        timeout=self.timeout)
                jsonresult = json.loads(res.data.decode("utf-8"))
            else:
                result = None
                try:
                    req = urllib2.Request(self.url,
                                          json.dumps(data).encode("utf-8"),
                                          {"Content-type": "application/json"})
                    result = urllib2.urlopen(req, timeout=self.timeout)
                    jsonresult = json.loads(result.read().decode("utf-8"))
                finally:
                    if result is not None:
                        result.close()
            if "error" in jsonresult and jsonresult["error"]:
                raise JsonRPCError(
                    jsonresult["error"]["code"],
>                   "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
                )
E               TypeError: string indices must be integers
`

**Comment by codeskyblue** [comment]
如果不好使，可以自己写一个边swipe边检查的函数

**Comment by max90727** [comment]
那我要怎么知道知道当前页已经swipe到底了呢？

**Comment by codeskyblue** [comment]
当swipe不在出现新元素的时候

**Comment by HiHub2019** [comment]
怎么判断swip出新元素

**Comment by yinkh** [comment]
和后来者说下原因哈，这是Android版本的UiAutomator就有的bug，原因是UIScrollable类中的scrollSwipe方法的foundEnd的条件错误，现在同时判断了页面触顶或者触底，应该根据上划或者下划分别判断触顶或者触底。不然就会出现从顶部开始滚动向下滚动，滚动一次，因为条件event.getFromIndex() == 0导致触发到错误的触底判断。
![image](https://github.com/openatx/uiautomator2/assets/8170059/afcfc0e5-df53-447a-bfbd-6766ecec30ae)
