### ISSUE TITLE
screenshot效率低

### ISSUE THREAD

**Issue by citymaster** [openatx/uiautomator2#323]
## Versions (版本)
0.1.11
手机型号： Nubia z17

## Details （详细信息）
1、我这边循环调用screenshot进行截图，发现差不多要550ms才截图一次，您这边测试效率是否也差不多？
2、看了下源码实现，发现atx-agent调用的minicap进行截图，而且是minicap保存图片到文件，然后atx-agent将文件以http方式传送给PC，是不是这种实现方式影响效率？

**Comment by citymaster** [comment]
因为我看到minicap描述目前效率通常是30-40 FPS，差不多25-33ms一张图，但是他这边视频流传输使用的是socket的方式传输图片。所以http方式传输效率真的这么差么，多了差不多500ms....

**Comment by codeskyblue** [comment]
如果为了效率的话可以 使用websocket连接 手机ip:7912/minicap   那个screenshot其实只是为了稳定，并不追求速度
