### ISSUE TITLE
调用sibling和child抛出'str' object has no attribute 'clone'异常

### ISSUE THREAD

**Issue by max90727** [openatx/uiautomator2#326]
调用sibling或者child方法抛出uiautomator2里面的异常
```
 d(className="android.support.v7.widget.RecyclerView", resourceId="id/scrollbar_recycle_view")
  .child_by_text("Settings", allow_scroll_search=True, className="android.widget.LinearLayout")
  .sibling(resourceId="id/item_selector_text")
```
抛出异常：
    File "C:\Users\A321283\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\session.py", line 956, in sibling
    return UiObject(self.session, self.selector.clone().sibling(**kwargs))
AttributeError: 'str' object has no attribute 'clone'

child_by_text 的exists是true，这个parent是可以找到的

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
没这么高级的用法呀

**Comment by codeskyblue** [comment]
要不你先scroll过去，然后再点击

**Comment by max90727** [comment]
> 要不你先scroll过去，然后再点击

这个里面没有点击，就是要拿到sibling里面的字符，跟Children and siblings例子里面一样的，先拿到child_by_text再找到child一样的，而且我试了试child，一样的异常

**Comment by max90727** [comment]
> 没这么高级的用法呀

我之前用的uiautomator，上面的代码一摸一样的是可以用的，然后现在换成uiautomator2，就抛出了异常

**Comment by codeskyblue** [comment]
这个地方的代码，之前有issue提到有bug，所以修复了下，估计改到了这个问题。但是最近我暂时被工作缠身，暂时也抽不出空去修复这个了

**Comment by max90727** [comment]
如果花的时间不多，能麻烦你修一下吗，我们已经要用了，谢谢

**Comment by max90727** [comment]
> 这个地方的代码，之前有issue提到有bug，所以修复了下，估计改到了这个问题。但是最近我暂时被工作缠身，暂时也抽不出空去修复这个了
您好，能麻烦您修复一下这个BUG吗，我们急着要用你们的uiautomator2。谢谢

**Comment by codeskyblue** [comment]
我也没这么空，建议你还是想办法绕过去，或自己看看能不能修复

**Comment by weiaiSanli** [comment]
> 如果花的时间不多，能麻烦你修一下吗，我们已经要用了，谢谢
请问你有没有修复成功啊?

**Comment by weiaiSanli** [comment]
请问有没有修复好这个BUG

**Comment by x157123** [comment]
这个是不是没有维护了

**Comment by Dskx54** [comment]
嗨！ 这个bug被修复了吗?
