### ISSUE TITLE
关于 already registered! 的问题(进程 com.github.uiautomator 杀不掉)

### ISSUE THREAD

**Issue by retrfy** [openatx/uiautomator2#329]
手头项目使用的是Java uiautomator, 

因为自带的ui automator viewer不太好用, 所以获取资源id时用的是python -m weditor这个工具

然后在android studio中run case时, 会报错:   UiAutomationService already registered!

并且在cmd中force-stop(ps | find "uiautomator" 后 force-stop, 然后再查询)无法杀掉com.github.uiautomator这个进程

除了重启手机, 此问题有解吗?

**Comment by codeskyblue** [comment]
文档上有写的。可以代码关闭，也可以通过 打开atx应用，点击里面的关闭uiautomator按钮

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by retrfy** [comment]
嗯, 解决了我的问题.
