### ISSUE TITLE
'UiObject' object has no attribute 'toast'

### ISSUE THREAD

**Issue by luomomimi** [openatx/uiautomator2#331]
现在还是不支持直接判断tosat是否存在么
代码如下
        if u(text=text).toast.get_message(3,3).exists:
我的本意是想判断toast的内容是否存在与正确
是目前不支持，还是我方法用错了

**Comment by codeskyblue** [comment]
用错了
```
d.toast.get_message(3,3)
```

**Comment by luomomimi** [comment]
如果

**Comment by luomomimi** [comment]
如果
message = d.toast.get_message(3,3)
那么message是什么类型的  是text么

**Comment by codeskyblue** [comment]
那可能显示的不是toast
