### ISSUE TITLE
获取元素进行set_text赋值所消耗时间浮动很大，如何进行优化

### ISSUE THREAD

**Issue by zjlwmz** [openatx/uiautomator2#332]
# ip
    ip = "192.168.1.126"
    code = 100
    # 连接
    d = u2.connect(ip)
    for num in range(30):
        s = time.time()
        d(resourceId="com.gf.client:id/stock_code_edit").set_text(code)
        print(time.time() - s)

为什么这个消耗的时间浮动非常大，有时候0.5s,有时候可能最大2s，想问问这个时间是怎么产生的，可以进行优化么，

使用版本
uiautomator2 0.2.1

调用APP的截图
![图片](http://jeewx.cn/app/image/12.png) 

计算结果输出时间：
![图片](http://jeewx.cn/app/image/13.png) 

使用手机型号
oppo a37m

**Comment by zjlwmz** [comment]
经过研究发现连接AutomatorHttpServer 9008的时候，请求的时间明显过程，而连接ATX-Agent的时间明显比AutomatorHttpServer 快的多，请问这个是什么情况，是NanoHTTPD框架本身很慢的呢

**Comment by mingyuan-xia** [comment]
自行在你的环境调试函数调动里面哪里慢，没有环境我们不可能复现

**Comment by zjlwmz** [comment]
就是发送jsonrpc到手机去执行，来回到时间不稳定

**Comment by mingyuan-xia** [comment]
网络环境？ 同wifi1网段？是不是开代理了？

**Comment by codeskyblue** [comment]
我来回复下，其实看看代码
