### ISSUE TITLE
android自动化测试怎么模拟 按下ctrl+c（adb shell/ uiqutomator2的方式）

### ISSUE THREAD

**Issue by little-hang** [openatx/uiautomator2#336]
android自动化测试怎么模拟 按下ctrl+c（adb shell/ uiqutomator2的方式）

目的：想录制andorid视频。adb shell screenrecord开始录制后，得按下ctrl+c结束录制（想在
满足一定条件时，按下ctrl+c）结束录制

**Comment by codeskyblue** [comment]
tag as feature request

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
录屏后期也不打算支持了
