### ISSUE TITLE
xpath单独给一元素定位时无法获取text值？

### ISSUE THREAD

**Issue by vitamincqb** [openatx/uiautomator2#337]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
import time
from time import sleep
import logging

import uiautomator2 as u2

d = u2.connect('0123456789ABCDEF')

d.xpath("//android.widget.TextView[1][@resource-id='com.tencent.android.qqdownloader:id/wo']").click()
sleep(2)
d.press('back')
sleep(2)
for x in d.xpath("//android.widget.TextView[@resource-id='com.tencent.android.qqdownloader:id/wo']").all():
    print("Text:", x.text)

# 上面的for循环可以通过text取值，为何单独时就没有text attribute呢？
result = d.xpath("//android.widget.TextView[1][@resource-id='com.tencent.android.qqdownloader:id/wo']")
print(f'result: {result.text}')
“
>>output
Text: 视频
Text: 阅读
Text: 社交
Text: 理财
Text: 购物
Traceback (most recent call last):
  File "C:\Users\q\Desktop\temp.py", line 17, in <module>
    print(f'result: {result.text}')
AttributeError: 'XPathSelector' object has no attribute 'text'
```
## Versions (版本)
Version: 0.2.3.dev2

## Issue and steps to reproduce (复现步骤)
# 上面的for循环可以通过text取值，为何单独时就没有text attribute呢？
result = d.xpath("//android.widget.TextView[1][@resource-id='com.tencent.android.qqdownloader:id/wo']")
print(f'result: {result.text}')

## Screenshots （相关截图）
能有尽量有
![image](https://user-images.githubusercontent.com/39504758/56867016-d52d9280-6a12-11e9-8ed7-8a291f6c6526.png)
![image](https://user-images.githubusercontent.com/39504758/56867025-f5f5e800-6a12-11e9-909f-005689b6b77f.png)

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
`d.xpath("....").all()` 返回 list of XMLElement。 暂时可以这么用 `d.xpath("....").all()[0].text` ,这个确实还没这么好用，以后还需要优化下

**Comment by codeskyblue** [comment]
```
d.xpath("....").get_text()
```

计划提供这个方法
