### ISSUE TITLE
咨询输入和点击的问题

### ISSUE THREAD

**Issue by retrfy** [openatx/uiautomator2#344]
除了文档给的input method方法外, 有类似于UIAUTOMATOR2这样给EDITTEXT输入文字的方法吗?

另外关于点击, 有直接通过resourceID来实现点击的方法吗?

**Comment by codeskyblue** [comment]
不太清楚你说的 EDITTEXT是什么？你可以举个具体的使用例子。
通过resourceId点击。比如resourceId是 android/mm

有两种方法

1. `d.xpath("@android/mm").click()`
2. `d(resourceId="android/mm").click()`
