### ISSUE TITLE
为什么多条用例测试过程中会出现阻塞？

### ISSUE THREAD

**Issue by qing0404** [openatx/uiautomator2#347]
为什么多条用例测试过程中会出现阻塞？
比如100条用例，跑到50条之后就停住了，也不报错
人为的去插拔一下设备之后，才能继续运行用例

**Comment by seiyasaga** [comment]
是100条用例写在一个脚本里的吗？

**Comment by qing0404** [comment]
不是的，用例的具体操作都是分文件的，执行文件里就只是把方法加到suit里面，像下面这样：
suite.addTest(WatchTest('test_device_080')) 
suite.addTest(WatchTest('test_device_081'))
suite.addTest(WatchTest('test_device_082'))

**Comment by codeskyblue** [comment]
卡在哪里了？方便debug不

**Comment by qing0404** [comment]
卡在任意一个case，没有规律，也可能不会出现阻塞
出现阻塞时：插拔下设备，或者是重启下atx-agent就可以继续了

**Comment by codeskyblue** [comment]
什么手机？卡的时候 atx-agent的日志 /sdcard/atx-agent.log

**Comment by qing0404** [comment]
没有特定的手机，有小米的，有华为三星的机器，出现阻塞没有规律
卡的时候没有注意atx-agent的日志，下次出现的时候再注意看下
