### ISSUE TITLE
app_start启动APP会打开手机自动旋转

### ISSUE THREAD

**Issue by veast** [openatx/uiautomator2#349]
app_start启动APP会打开手机自动旋转（下拉通知栏可以看到的“自动旋转”）

举例：
  d.app_start("com.android.chrome")
  d.app_start("com.android.mms")

Uiautomator2 Version： 0.2.3.dev2

**Comment by codeskyblue** [comment]
666, 这都被你观察到了。

**Comment by codeskyblue** [comment]
`app_start`是调用的monkey命令启动的。你可以换成这个方法 `d.session("com.android.mms")` 启动应用，这个不会吧那个**自动旋转**打开

**Comment by veast** [comment]
试了下OK，感谢：）

**Comment by mingyuan-xia** [comment]
现在app_start有一个use_monkey option

**Comment by codeskyblue** [comment]
目前已经修改 app_start的逻辑，默认使用 d.session启动，除非指定了 use_monkey选项
