### ISSUE TITLE
手机和电脑在不同的地方

### ISSUE THREAD

**Issue by allenzhangp** [openatx/uiautomator2#35]
现在有个问题是服务器部署在阿里云上，手机不能通过数据线链接。这种情况要怎么处理？
atx-server已经检测到这台手机，但是点进去之后是一片空白
![Uploading 700E7D80-AA90-49F4-A20C-9C99188E3293.png…]()

**Comment by codeskyblue** [comment]
还不支持

**Comment by 5368** [comment]
１．手机内网穿透［已实现］
２．改源码，加个本地init后，连接远端服务器受控［想的］

**Comment by mingyuan-xia** [comment]
同步屏幕需要minicap数据量不小, 操作需要minitouch；两者都是实时性要求很高的，在公网环境下不可控，必须在网络基础设施方便自行解决这些问题
