### ISSUE TITLE
使用exists或count做过滤为什么没有标签内没有的元素也返回True?

### ISSUE THREAD

**Issue by 541260561** [openatx/uiautomator2#351]
if parent_tag.child(className='android.widget.FrameLayout').sibling(resourceId='com.tencent.mm:id/e4m',
                                                                                    className='android.widget.ImageView').exists(timeout=2):
                    print('视频跳过')
                    continue

**Comment by codeskyblue** [comment]
这个实在猜不出来怎么回事。你不妨改成xpath试试。。

```
d.xpath('//android.widget.FrameLayout/../*[@resource-id="com.tencent.mm:id/e4m"]').exists
```

**Comment by codeskyblue** [comment]
duplicated with https://github.com/openatx/uiautomator2/issues/778
