### ISSUE TITLE
XPathSelector 能不能提供一个 getUIObject的方法 QAQ

### ISSUE THREAD

**Issue by tyzero** [openatx/uiautomator2#359]
当前版本返回的d.xpath()返回的都是 XPathSelector

而 d(“”) 返回是是 经过Selector  再返回-> UiObject

讲道理，xpath() 应该也能 返回UiObject才对

毕竟XPathSelector 连set_text 和 get_text都没有, 难受

**Comment by codeskyblue** [comment]
实现原理不一样啊，不过 get_text应该有啊

**Comment by tyzero** [comment]
嗯嗯，了解了。O(∩_∩)O谢谢
