### ISSUE TITLE
运行 python -m uiautomator2 init 报 Exception: ('status code', 404)

### ISSUE THREAD

**Issue by kuailel45** [openatx/uiautomator2#36]
![default](https://user-images.githubusercontent.com/17819498/35424443-a16bcab2-028e-11e8-83a2-3cf05bdf7f66.png)
手机是小米5，已开调试模式，pc是win10，python版本3.6.3，uiautomator2 (0.0.4.dev9)。
大神帮忙看一下

**Comment by codeskyblue** [comment]
嗯，这issue提的不错，各种消息都有写。

执行这个命令，看下输出

```
python -muiautomator2 init --verbose
```

**Comment by kuailel45** [comment]
大神，我执行这个命令，输出如下：
![default](https://user-images.githubusercontent.com/17819498/35492491-1f44be5c-04e8-11e8-8ef0-b9e4e97f3be5.png)

**Comment by codeskyblue** [comment]
第五行，看到了一个奇怪的  `Active code: 65001`  

```
adb shell getprop ro.build.version.sdk
```
会输出什么？

**Comment by kuailel45** [comment]
![default](https://user-images.githubusercontent.com/17819498/35544486-8d9eef68-05a5-11e8-8ed7-6841749a7262.png)
Active code: 65001这个是更改命令行编码方式为UTF8出现的。
我去掉Active code: 65001之后可以安装依赖程序成功了。

**Comment by codeskyblue** [comment]
nice
