### ISSUE TITLE
是否可以取消aircv组件的16:9限制

### ISSUE THREAD

**Issue by haogefeifei** [openatx/uiautomator2#363]
我看源码了，限制死了必须16:9，现在这个比例的设备越来越少了。

**Comment by haogefeifei** [comment]
我先把aircv源码copy出来用了。。

**Comment by codeskyblue** [comment]
这个aircv 仅供参考，最好还是重写一份。欢迎贡献一份新的

**Comment by qingqingcaoyuanlin** [comment]
`from uiautomator2.ext.aircv import CVHandler

CV = CVHandler()
im_source = self.d.screenshot(format='opencv')
ret = CV.find_template(im_source, CV.imread(file))#file提前截好的图片
self.d.click(ret['result'][0], ret['result'][1])`

看了aircv代码，最简单的实现，可以再添加其他优化，测试过1S可完成识别，效率比使用findit实现的接口快2S。
提前截图：用CVHandler().show显示手机截图，用截图工具把需要的图标截下来保存。
另外，aircv存放在ext-archived文件夹下，导致无法import，需要把aircv复制到ext文件夹下。
