### ISSUE TITLE
app截屏能做到滚动截屏吗？

### ISSUE THREAD

**Issue by floatice** [openatx/uiautomator2#364]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
不能，欢迎提pr
