### ISSUE TITLE
设备重启后atx-agent能否自动连接成功？

### ISSUE THREAD

**Issue by seiyasaga** [openatx/uiautomator2#365]
如何操作可以使设备重启后atx-agent自动连接成功？

重启后日志：
 "atx-agent is not running. Fix it with following steps.\n1. Plugin device in
to computer.\n2. Run command \"python -m uiautomator2 init\""
EnvironmentError: atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"

**Comment by codeskyblue** [comment]
是插着USB数据线吗？插线的时候默认会重启atx-agent的

**Comment by seiyasaga** [comment]
一直插着数据线，重启后就连不上了

**Comment by seiyasaga** [comment]
重启后在脚本里加上d = u2.connect()重新start  atx-agent，就可以连接成功了。

**Comment by codeskyblue** [comment]
恩，目前只有在connect的时候才会重启atx-agent
