### ISSUE TITLE
Huawei P20 Huawei Mate20  获取toast失败

### ISSUE THREAD

**Issue by shixue33** [openatx/uiautomator2#366]
两款华为机型Huawei P20 ，HUAWEI Mate20 获取toast失败。（目前只在华为的机器上有这个现象）
系统都是9.0，EMUI 9.0.0

```
d.toast().reset()
d.toast().get_message()
```

错误信息：
![WechatIMG104](https://user-images.githubusercontent.com/7905093/59399487-c5052300-8dc6-11e9-9096-bc9c54d4e496.jpeg)

**Comment by codeskyblue** [comment]
弄好了？

**Comment by jeffchen** [comment]
I encounter the same issue, could you please share the solution?
Thanks.

**Comment by jeffchen** [comment]
After checking the source code, AccessibilityEventListener is not initialized in AutomatorServiceImpl in 1.1.7_dev:
    public AutomatorServiceImpl() {
        ......
        // Disable it also disable toast catcher
        // Just to make sure if the following code make global worse or better.
        **// uiAutomation.setOnAccessibilityEventListener(new AccessibilityEventListener(device, watchers));**
    }

1.1.7:
    public AutomatorServiceImpl() {
        ......
        // default uiAutomation serviceInfo.eventTypes is -1
        // I guess this might be watch all eventTypes
        uiAutomation.setOnAccessibilityEventListener(**new AccessibilityEventListener(device, watchers)**);
    }
