### ISSUE TITLE
在真机上运行某些命令uiautomator start failed .

### ISSUE THREAD

**Issue by wwangchaohui** [openatx/uiautomator2#367]
手机：小米6x ,android8.1
环境：在手机上安装了termux终端，python3.7.3,
通过pip 安装了uiautomator2 0.2.4dev
axt-agent 0.6
app-uiautomator.apk 1.17
app-uiautomator-test.apk

我是想在手机上直接运行一些python脚本来执行一些自动化的操作。
运行过程中有些uiautomator2对象的函数可以成功运行，但是有些会报错。
import uiautomator2 as u2
d = u2.connect(“0.0.0.0")
d.app_start("com.netease.cloudmusic")
d.device_info
这些没问题
运行其他的都会出现uiautomator start failed 
不知道是哪个地方出了差错？帮我看看，小弟先谢谢各位大佬了。

下面是手机截图

![IMG_20190614_173730](https://user-images.githubusercontent.com/7232687/59500709-983b3380-8ecc-11e9-95f2-21650453dd2a.jpg)
![Screenshot_2019-06-14-16-58-10-981_com github uiautomator](https://user-images.githubusercontent.com/7232687/59500785-bbfe7980-8ecc-11e9-95e8-d20d42efc728.png)
![Screenshot_2019-06-14-16-57-37-374_com termux](https://user-images.githubusercontent.com/7232687/59500802-c1f45a80-8ecc-11e9-96fa-4c59d0c32551.png)
![Screenshot_2019-06-14-16-58-03-686_com termux](https://user-images.githubusercontent.com/7232687/59500808-c587e180-8ecc-11e9-9806-d3d9fda66803.png)

![Screenshot_2019-06-14-17-53-58-729_com termux](https://user-images.githubusercontent.com/7232687/59501348-eac91f80-8ecd-11e9-92fd-33f9c37e82d7.png)

**Comment by codeskyblue** [comment]
这时什么手机呀，怎么连 instrument命令都没有

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/59581724-5f879e00-9108-11e9-811f-1435f7c5f7a9.png)

这里connect的参数要写成 `127.0.0.1:7912`

**Comment by wwangchaohui** [comment]
手机是小6x ,android 8.1
把connect的参数要写成 127.0.0.1:7912, 结果是一样不停的uitutomator is starting ......
 然后  started failed

**Comment by codeskyblue** [comment]
atx-agent你是用adb启动的吗？

**Comment by wwangchaohui** [comment]
太感谢codeskyblue了，
我所有的操作都是在手机termux终端下进行的，atx-agent也是我拷贝到termux通过./atx-agenty方式运行。
听到你问是用adb启动的吗？我在电脑是通过adb 运行手机上的atx-agent,一切正常，再也没有错误提示。

然后我在termux通过adb 的方式连接到本地手,adb shell /data/local/atx-agent server .成功了，完全正常。
非常感谢。。。谢谢老哥。
![Screenshot_2019-06-18-13-18-31-811_com termux](https://user-images.githubusercontent.com/7232687/59658863-6f21e800-91d7-11e9-8791-a4e34303d3f4.png)

**Comment by codeskyblue** [comment]
adb的权限比较高一些，有运行instrument的权限。没问题的话issue我先关掉了

**Comment by wwangchaohui** [comment]
还有一个问题想问老大，我把minicap,minitouch，已经拷到了手工/data/local/tmp/.然后只开起了am shell /data/local/tmp/atx-agent server
在浏览器进入192.168.43.1：7912/remote,可以看到手机的远程投屏画面...
但是鼠标无法操作投屏画面来控制手机
是不是手机需要root？或者手动开启一下minitouch服务呢？

本来是想用python  -m uiautomator2 init 
初始化自动安装一下的，结果执行错误，我准备在Ubuntu上装个python3.7替换下python3.5...
结果把python3.5删除，就把系统给整坏了，崩溃。。。现在等U盘重装系统。。。

**Comment by codeskyblue** [comment]
Ubuntu自带的Python你不要卸载，内部的程序可能依赖它。uiautomator2 3.5好像也支持。 为什么控制不了呢。因为前端没写呀

**Comment by wwangchaohui** [comment]
终究还是暴露了我的智商
我再去研究一下这个minitouch东西怎么用
感觉这些东西组合起来做群控的话，很方便
