### ISSUE TITLE
How to disable uiautomator2 log message?

### ISSUE THREAD

**Issue by troub1emaker-sys** [openatx/uiautomator2#368]
Name: uiautomator2
Version: 0.2.3

I just write a simple code and found that there will be some log message on command line. How to disable uiautomator2 log message?
Thank you.

> d(resourceId='com.android.permissioncontroller:id/continue_button').info

> WARNING:root:-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.android.permissioncontroller:id/continue_button], method: objInfo, retrying in 0.5 seconds...
> WARNING:root:-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.android.permissioncontroller:id/continue_button], method: objInfo, retrying in 0.6 seconds...

**Comment by codeskyblue** [comment]
这个不太好改。。

**Comment by codeskyblue** [comment]
因为日志留着还有调试的用途，要是留开关的话，不太好弄

**Comment by troub1emaker-sys** [comment]
> 因为日志留着还有调试的用途，要是留开关的话，不太好弄

I got it. How about logger message? I found it will start to output my logger message on command line.

> loggerFormat = Formatter('%(asctime)s - %(levelname)s\t- %(message)s', datefmt='%Y/%m/%d %H:%M:%S')
> logger.setLevel(level=DEBUG)		
> fileHandler = FileHandler('test')
> fileHandler.setFormatter(loggerFormat)
> logger.addHandler(fileHandler)
> d = uiautomator2.connect()
> try:
> 	d(resourceId='com.android.permissioncontroller:id/continue_button').info
> except UiObjectNotFoundError:
> 	pass
> logger.debug('123')

> WARNING:root:-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.android.permissioncontroller:id/continue_button], method: objInfo, retrying in 0.5 seconds...
> WARNING:root:-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.android.permissioncontroller:id/continue_button], method: objInfo, retrying in 0.6 seconds...
> DEBUG:test:123

**Comment by mingyuan-xia** [comment]
You can redirect your logger msg. Or you can help on converting plain logs to logger-style. We just dont have the time for this now.

**Comment by troub1emaker-sys** [comment]
> You can redirect your logger msg. Or you can help on converting plain logs to logger-style. We just dont have the time for this now.

I got it. Many thanks.
