### ISSUE TITLE
minSdkVersion 最低18的原因 解释说明

### ISSUE THREAD

**Issue by codeskyblue** [openatx/uiautomator2#369]
编译时回报如下错误

Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 18 declared in library [com.android.support.test.uiautomator:uiautomator-v18:2.1.3] /Users/sunshengxiang/.gradle/caches/transforms-1/files-1.1/uiautomator-v18-2.1.3.aar/f7359737caf97644a42e0c9e229026c9/AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 18,
		or use tools:overrideLibrary="android.support.test.uiautomator.v18" to force usage (may lead to runtime failures)

**Comment by mingyuan-xia** [comment]
提高到１８吧
