### ISSUE TITLE
Allow other calls to accessibility service

### ISSUE THREAD

**Issue by xpconanfan** [openatx/uiautomator2#371]
Please consider [setting UI automation flags](https://developer.android.com/reference/android/support/test/uiautomator/Configurator#setuiautomationflags)
with [this flag](https://developer.android.com/reference/android/app/UiAutomation.html#FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES)

so uia2 does not block additional `adb uiautomator dump` calls

**Comment by codeskyblue** [comment]
related to https://github.com/openatx/android-uiautomator-server/issues/10
