### ISSUE TITLE
init提示错误：unknown host service

### ISSUE THREAD

**Issue by wang5561207** [openatx/uiautomator2#373]
所有设备都是这样，重新init出现如下提示
![捕获](https://user-images.githubusercontent.com/37778956/59960154-75290900-94f6-11e9-9ee9-98af124d84b4.PNG)

**Comment by codeskyblue** [comment]
新版的uiautomator2使用adb协议直接跟adb server通信的。
所以为了解决这个问题，需要你提供点更详细的信息。

首先先确保你的adb是正常可以使用的。

打开一个终端，运行下面的命令
```
wget https://github.com/NetEaseGame/ATX/raw/master/scripts/100-lines-tcp-proxy.py
python2 100-lines-tcp-proxy.py  # forward port 5555 to 5037
```

打开第二个终端

```
adb -s abcdefg -P 5555 forward tcp:1122 tcp:3344
```

然后将第一个终端的输出，截图发过来。

**Comment by wang5561207** [comment]
谢谢，测试后发现是我的ADB服务有问题，但想请教一下是否有方法让设备重启后，不需要init就能通过ip连上主机

**Comment by codeskyblue** [comment]
通过usb你可以不用init，但是通过wifi连接就必须重新init

**Comment by sltruman** [comment]
我用最新版的雷电模拟器也出现了这个问题。

**Comment by sltruman** [comment]
这个问题似乎是由于阉割版的adb导致的：adb forward --list命令不支持。

**Comment by sltruman** [comment]
通过替换为官方的ADB包解决了这个问题。 @codeskyblue

**Comment by calvin-tee** [comment]
@sltruman 请问是如何替换官方adb包，我重启后就出现这个问题了
