### ISSUE TITLE
hi,uiautomator2 后续会支持获取空间的parent吗，很重要。

### ISSUE THREAD

**Issue by Testerding** [openatx/uiautomator2#375]
Versions (版本)
0.1.3dev9

在源码中看如下备注：
# android-uiautomator-server not implemented
# In UIAutomator, UIObject2 has getParent() method
似乎并未实现，在实际编写过程中觉得此方法很重要，uiautomator2 后续会支持获取控件的parent吗

**Comment by codeskyblue** [comment]
因为java实现的问题后续也不会支持，除非你能提一个非常nb的pr。 你这个暂时可以用 xpath的方法来代替
