### ISSUE TITLE
模拟器下出现虚拟按键，挡住点击，有办法让它不显示吗？

### ISSUE THREAD

**Issue by falwiw** [openatx/uiautomator2#377]
![QQ图片20190702130117](https://user-images.githubusercontent.com/14345904/60483783-8e397300-9cc9-11e9-9d8f-52a0e151a5ae.png)

模拟器下出现虚拟按键，挡住点击，有办法让它不显示吗？

**Comment by codeskyblue** [comment]
有个adb-keyboard的应用，那个是没有底部的这东西的
