### ISSUE TITLE
子线程中的exists()似乎会导致watcher产生BUG

### ISSUE THREAD

**Issue by veast** [openatx/uiautomator2#382]
遇到了和https://github.com/openatx/uiautomator2/issues/210 一样的问题，甚至延伸出来了另一个问题**Cannot register new watcher from within another**。不过经过分析，似乎找到了问题触发的条件：

① 如果在线程中不断调用.exists()，且主线程本身声明了5-6个（浮动）及以上watcher，会抛出**Cannot register new watcher from within another**

② 同样在线程中不断调用.exists()，且主线程本身声明了2个（浮动）及以上watcher，执行d.watchers.remove()，会抛出**Cannot remove a watcher from within another**

以上看起来属于同一个根因导致..？

![image](https://user-images.githubusercontent.com/9658131/60964270-76a35f80-a345-11e9-989c-25ee64f06009.png)

**Comment by codeskyblue** [comment]
watched这个方法因为不稳定被我从1.0.0版本中去掉了

试试下面这种方法

```python
d.xpath.when("本地下载").click()
d.xpath.watch_background(2.0) # 每2.0s检查一次
```

**Comment by veast** [comment]
好的，多谢答复。
