### ISSUE TITLE
U2如何做图片比较

### ISSUE THREAD

**Issue by xiaoyaoamiao** [openatx/uiautomator2#383]
ATX： def exists(self, pattern, **match_kwargs):
U2： def exists(self, **match_kwargs):

所以现在U2的exists()怎么去支持图片比较？
目前这种是出错的：
d.exists('email_login_dashboard_cn.2265x1080.png')
TypeError: exists() takes exactly 1 argument (2 given)

**Comment by seiyasaga** [comment]
如何做图片对比啊

**Comment by xiaoyaoamiao** [comment]
> 如何做图片对比啊

U2是没有图片对比的，我目前的解决方案是把U2和ATX都import进来。
在需要做图片对比的时候调用atx的图片对比方法。
import atx
import uiautomator2 as u

        context.driver = u.connect(host)
        context.driver_atx = atx.connect(host, platform='android')
