### ISSUE TITLE
截图导致模拟器死机，怎么解决？

### ISSUE THREAD

**Issue by 1026cy** [openatx/uiautomator2#385]
发现了一个使用u2给安卓模拟器截图后会导致模拟器死机的问题。真机上并不会发生这个问题。
安卓版本6.0，官方sdk安装模拟器。
![报错截图](https://user-images.githubusercontent.com/34910886/61182541-3efb2700-a667-11e9-9548-2c7509f9236e.jpg)

u2版本：
Name: uiautomator2
Version: 0.3.3
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, logzero, adbutils, pillow, lxml
Required-by: weditor

**Comment by codeskyblue** [comment]
看了下最新的版本，遇到模拟器的时候，现在会改用 `screencap`命令截图了，问题应该不大了
