### ISSUE TITLE
uiautomator2 version 0.3.3  手机型号：华为Mate 8, 

### ISSUE THREAD

**Issue by houhaicoder** [openatx/uiautomator2#386]
问题：后台总是隔几十秒就显示： uiautomator2 is starting ...    
           期间手机没有任何操作
- 手机型号 华为mate 8
- uiautomator2的版本号(0.3.3`)
- 手机截图
![image](https://user-images.githubusercontent.com/34623471/61277587-0f722900-a7e5-11e9-9992-a47c4b70e706.png)

**Comment by codeskyblue** [comment]
很难搞呀，先换个手机吧。

**Comment by codeskyblue** [comment]
fixed in 3.2.0
