### ISSUE TITLE
启动陌陌报异常

### ISSUE THREAD

**Issue by kcher** [openatx/uiautomator2#393]
启动陌陌的时候报如下异常，尝试启动抖音是正常的。

- 手机型号
网易momo模拟器

- uiautomator2的版本号
0.3.3

- 相关日志
![图片](https://user-images.githubusercontent.com/4252702/61805579-9fa91180-ae68-11e9-9c7f-da649f5615bf.png)

**Comment by codeskyblue** [comment]
ref: https://github.com/shogo82148/androidbinary

**Comment by LeoSsy** [comment]
请问你启动陌陌干嘛？ 😂
