### ISSUE TITLE
d.swipe() 返回 True or False

### ISSUE THREAD

**Issue by shigubuhua** [openatx/uiautomator2#396]
希望如下功能：
d.swipe(sx, sy, ex, ey) 能够如 d(text="Settings").scroll() 一样，在滑动正常时返回True，滑动到头时返回False，现在似乎默认返回''(空字符)

**Comment by shigubuhua** [comment]
似乎d(className="android.widget.ListView").scroll()，也不能返回正确的True or False。
只有d(scrollable=True).scroll()，返回值是正确的True or False。

**Comment by mingyuan-xia** [comment]
滑动没有所谓正常不正常，x,y给多少就怎么滑
scroll接口文档没有定义返回值的意义，不应该使用
这几个API只是看上去在做同一件事情，实现完全不同，没有统一的返回
