### ISSUE TITLE
模拟器(安卓5.1.1)在使用u2运行app自动化时频繁crash

### ISSUE THREAD

**Issue by cnhkzyy** [openatx/uiautomator2#399]
## 手机型号
夜神模拟器 v6.2.6.1

## 安卓版本
v5.1.1

## uiautomator2的版本号
0.3.3

## 相关日志
见附件（大概出现在08-01 12:40之后）
[crash.txt](https://github.com/openatx/uiautomator2/files/3455989/crash.txt)

## 备注
在逍遥模拟器（安卓版本v5.1.1上亦出现此问题）

**Comment by codeskyblue** [comment]
日志真大呀

**Comment by codeskyblue** [comment]
升级到1.0.3试试，如果还有问题，你在reopen

**Comment by cnhkzyy** [comment]
> 升级到1.0.3试试，如果还有问题，你在reopen

大佬，啥原因引起的

**Comment by codeskyblue** [comment]
好了，还是没好

**Comment by cnhkzyy** [comment]
> 好了，还是没好

没好
![image](https://user-images.githubusercontent.com/29578918/63075859-a73e7080-bf65-11e9-9b69-04c5adf60530.png)
