### ISSUE TITLE
Can it be detectable by application?

### ISSUE THREAD

**Issue by sionking** [openatx/uiautomator2#400]
I would like to use this package to control a 3'rd party application.
Can this application know it is under control or it is transparent ?
I guess clicking on a point x,y is not totally the same as user click? or is it ?

Thanks.

**Comment by codeskyblue** [comment]
It is the same as you click and also support 3rd party apps.

**Comment by instasck** [comment]
> It is the same as you click and also support 3rd party apps.

So there is no flag when using this ?
