### ISSUE TITLE
uiautomator2升级至1.0.0，atx-agent在Android 9上无法运行

### ISSUE THREAD

**Issue by joelai** [openatx/uiautomator2#406]
- Samsung A60，Huawei 麦芒8，vivo Z5x
- Android 9
- uiautomator2的版本号 1.0.0

**Comment by hypery11** [comment]
-     Mi8 (dipper)
-     Android 9
-    uiautomator2 v1.0.0

一樣狀況，開啟直接閃退

**Comment by chenwenkun** [comment]
三星s10
android 9
uiautomator2 v1.0.0
也是闪退

**Comment by codeskyblue** [comment]
1.0.3版本修复该问题
