### ISSUE TITLE
missing call unregisterReceiver()

### ISSUE THREAD

**Issue by rp517045939** [openatx/uiautomator2#407]
附上logcat 抓取的日志，

08-13 11:04:28.938  9464  9464 E ActivityThread: Service com.github.uiautomator.Service has leaked IntentReceiver com.github.uiautomator.monitor.BatteryMonitor$1@a45ed7a that was originally registered here. Are you missing a call to unregisterReceiver()?
08-13 11:04:28.938  9464  9464 E ActivityThread: android.app.IntentReceiverLeaked: Service com.github.uiautomator.Service has leaked IntentReceiver com.github.uiautomator.monitor.BatteryMonitor$1@a45ed7a that was originally registered here. Are you missing a call to unregisterReceiver()?
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1596)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1329)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1698)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1671)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1659)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.github.uiautomator.monitor.BatteryMonitor.register(BatteryMonitor.java:40)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.github.uiautomator.monitor.AbstractMonitor.<init>(AbstractMonitor.java:17)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.github.uiautomator.monitor.BatteryMonitor.<init>(BatteryMonitor.java:21)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.github.uiautomator.Service.onCreate(Service.java:132)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4150)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ActivityThread.access$2400(ActivityThread.java:273)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.os.Handler.dispatchMessage(Handler.java:112)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.os.Looper.loop(Looper.java:216)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at android.app.ActivityThread.main(ActivityThread.java:7625)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at java.lang.reflect.Method.invoke(Native Method)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
08-13 11:04:28.938  9464  9464 E ActivityThread:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
08-13 11:04:28.945  9464  9484 W System.err: java.net.UnknownServiceException: CLEARTEXT communication to 127.0.0.1 not permitted by network security policy
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.946  9464  9484 W System.err:    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
08-13 11:04:28.947  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.947  9464  9484 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.947  9464  9484 W System.err:    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-13 11:04:28.947  9464  9484 W System.err:    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
08-13 11:04:28.947  9464  9484 W System.err:    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-13 11:04:28.947  9464  9484 W System.err:    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
08-13 11:04:28.947  9464  9484 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
08-13 11:04:28.947  9464  9484 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-13 11:04:28.947  9464  9484 W System.err:    at java.lang.Thread.run(Thread.java:784)
08-13 11:04:28.947  9464  9487 W System.err: java.net.UnknownServiceException: CLEARTEXT communication to 127.0.0.1 not permitted by network security policy
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-13 11:04:28.947  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
08-13 11:04:28.948  9464  9487 W System.err:    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-13 11:04:28.948  9464  9487 W System.err:    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
08-13 11:04:28.948  9464  9487 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
08-13 11:04:28.948  9464  9487 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-13 11:04:28.948  9464  9487 W System.err:    at java.lang.Thread.run(Thread.java:784)
08-13 11:04:28.949  9464  9486 W System.err: java.net.UnknownServiceException: CLEARTEXT communication to 127.0.0.1 not permitted by network security policy
08-13 11:04:28.949  9464  9486 W System.err:    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
08-13 11:04:28.949  9464  9486 W System.err:    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.950  2077  2077 D HWUCD_SensorWallpaperService: onSensorChanged value : 0.0849
08-13 11:04:28.950  9464  9486 W System.err:    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
08-13 11:04:28.951  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-13 11:04:28.952  9464  9486 W System.err:    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-13 11:04:28.952  9464  9486 W System.err:    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-13 11:04:28.952  9464  9486 W System.err:    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
08-13 11:04:28.952  9464  9486 W System.err:    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-13 11:04:28.952  9464  9486 W System.err:    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
08-13 11:04:28.952  9464  9486 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
08-13 11:04:28.953  9464  9486 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-13 11:04:28.953  9464  9486 W System.err:    at java.lang.Thread.run(Thread.java:784)

**Comment by codeskyblue** [comment]
这个unregisterReceiver 我暂时不会修，有熟悉Android的可以帮下忙

**Comment by yaming116** [comment]
https://github.com/openatx/android-uiautomator-server/pull/35

查看代码没有发现如何出现的，目前解决方法先注销一次
