### ISSUE TITLE
关于d.watchers.watched = True

### ISSUE THREAD

**Issue by eminemisgod** [openatx/uiautomator2#408]
- 手机型号
华为p20
系统是安卓9

- uiautomator2的版本号(`pip3 show uiautomator2`)
Name: uiautomator2
Version: 1.0.0
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: e:\python\python3.7\lib\site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, logzero, adbutils, pillow, lxml
Required-by: weditor

- 问题描述
在执行到d.watchers.watched = True时，报错。信息如下：
jsonrpc请求报文：
b'{"jsonrpc": "2.0", "id": "e22b0db145feb7fd014a7c54cc9f6df6", "method": "runWatchersOnWindowsChange", "params": [true]}'

返回值：
{'jsonrpc': '2.0', 'id': 'e22b0db145feb7fd014a7c54cc9f6df6', 'error': {'code': -32601, 'message': 'method not found'}}

另外：之前有看到说移除d.watchers.watched ，但是在小米mix2上运行却没有该报错

**Comment by codeskyblue** [comment]
估计版本没有刷新到最新吧，反正是已经移除了
