### ISSUE TITLE
最新版本--serial参数不生效，无法通过--serial指定设备初始化

### ISSUE THREAD

**Issue by GBwuka** [openatx/uiautomator2#409]
![image](https://user-images.githubusercontent.com/1592742/63080435-a3b1e600-bf73-11e9-9f4d-84908c6941f8.png)

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/commit/2c17c8609ee305b2e01e221ec392c9e39abdb4a5
