### ISSUE TITLE
vivo Y67上执行d.info非常慢

### ISSUE THREAD

**Issue by codeskyblue** [openatx/uiautomator2#41]
原因分析.

`d.info`中会调用`UiDevice.getDisplayRotation()` 之后，该函数的实现如下

```java
    public int getDisplayRotation() {
        Tracer.trace();
        waitForIdle();
        return getAutomatorBridge().getRotation();
    }
```

waitForIdle为等待当前UI稳定的意思。默认等待时间10s。（实际测试每次都会超时）

>另外这里uiautomator2也有bug，参考链接 <https://www.ydkf.me/archives/22>

## 解决方法
![image](https://user-images.githubusercontent.com/3281689/35790738-dddd4d84-0a7e-11e8-9730-e58444a2c8b0.png)

将上方的黄色提示框关掉之后。使用IP连接设备，`d.info`调用速度恢复正常。
怀疑是上方的提示框影响了waitForIdle函数

**Comment by mingyuan-xia** [comment]
有些机型wifi连接状态还有cellular链接状态会有小的上下行箭头，这样ui一直无法稳定，另外有些会开着cpu管理器，在notification上显示总是变的数字，也会造成持续不稳定。是否考虑不忙等待，采样5次取多数？

**Comment by codeskyblue** [comment]
@mingyuan-xia 除非你让我去改u2的源码

**Comment by markyao0591** [comment]
这个有解决方法吗？ 在一些播放场景，有进度条在更新，就会导致卡住，最后抛timeout

HTTPConnectionPool(host='127.0.0.1', port=56210): Read timed out

**Comment by Apple-Flavor** [comment]
@markyao0591 这个问题现在还有，特别是有进度条的界面，点击控件非常慢，有时候甚至timeout.  请问这个解决了吗？

**Comment by codeskyblue** [comment]
用xpath应该可以，不过现在还没支持
