### ISSUE TITLE
WebView support

### ISSUE THREAD

**Issue by monicadanesa** [openatx/uiautomator2#410]
Hi All

I am curious, is possible to implement Webview testing use uiautomator2?

**Comment by codeskyblue** [comment]
Yes, it is possible. But need time to implement

**Comment by monicadanesa** [comment]
thank you for response my comment. yeap, because in the future, people are more using webview than native..

**Comment by mingyuan-xia** [comment]
PRs and plans are more welcomed.

**Comment by jerrycgc** [comment]
Is it possible to use this webview feature this year?

> Yes, it is possible. But need time to implement

**Comment by codeskyblue** [comment]
no
