### ISSUE TITLE
Watchers error with Android 10 on Windows

### ISSUE THREAD

**Issue by Avi-Dekra** [openatx/uiautomator2#411]
With Android 10 devices, I am seeing an error when starting watchers. Can you please help

-32601 Method not found: <method not found> data: , method: runWatchersOnWindows
Change

**Comment by mingyuan-xia** [comment]
Please provide context, which u2 version.
Also attach logcat, atxagent.log and more complete stacktraces

**Comment by codeskyblue** [comment]
watchers.watched方法已弃用。issue我先关了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
