### ISSUE TITLE
众筹 openatx 持续集成测试手机

### ISSUE THREAD

**Issue by codeskyblue** [openatx/uiautomator2#413]
>声明：本次众筹主要用来促进openatx项目的健康持续发展。目前为首次众筹，欢迎提出自己的意见。

本次主要用来给uiautomator2的代码做持续集成测试用。

预计购买手机型号：https://www.mi.com/redmi7a/
共计：￥599
已收到：￥558

参与人：

- 素者 50
- RRR 50
- kunkun 50
- gradient30(github) 188
- 一百土情局 50
- 大连-马文韬 50
- 上海-咸鱼菜鸡 50
- wsf 20
- ？？ 50

请使用微信打赏的方式，参与。参与者的昵称将会展示到众筹页。请打赏时备注：**众筹413**
并在下方回复，你的昵称和金额（可以是QQ群中的昵称）。非常感激您花时间看这个issue

![image](https://user-images.githubusercontent.com/3281689/63260527-c3b71180-c2b3-11e9-824a-daaf4ab94fde.png)

**Comment by rp517045939** [comment]
-RRR 50

**Comment by gradient30** [comment]
GSY188👍

**Comment by oubingkun** [comment]
-kunkun -50

**Comment by thedreamly** [comment]
大连-马文韬 50

**Comment by qiuhengxing** [comment]
上海-咸鱼菜鸡 50

**Comment by zhangminvip** [comment]
iflytek-小张 100

**Comment by reach296** [comment]
深圳-星星 50

**Comment by yuyinweiliao** [comment]
上海 魔都 哈哈
