### ISSUE TITLE
using phone internet instead of wifi connection.

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#414]
When the device is controlled over WIFI it is impossible to get internet connection (also when the wifi has no internet !) . is there any solution ?

**Comment by mingyuan-xia** [comment]
can not understand what u are talking about. Please clarify.

**Comment by codeskyblue** [comment]
我看懂了，就是如何通过4g或5G的方案控制手机

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
算了，没精力支持
