### ISSUE TITLE
应用启动后，session/app_start没有及时返回

### ISSUE THREAD

**Issue by su1216** [openatx/uiautomator2#415]
- redmi k20
- android 9.0
- uiautomator2 1.1.0

安装app并使用session/app_start启动app后，app内部申请权限，会弹出一个需要用户授权的对话框，此时app已经成功启动，但是session/app_start还阻塞着

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/blob/master/uiautomator2/__init__.py#L841
底层call am start启动，请调试，停在哪步，如果am start没有返回，即系统行为

**Comment by codeskyblue** [comment]
计划弃用 am start 中的-W参数

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
从 1.2.3 版本开始启用-W参数
