### ISSUE TITLE
double click -second click not on same point.

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#416]
I do click by "swipe_points" so it will look more human, I swipe 3- 7 points and it perform a button click.
Can I do the same for double click ? 
Do a swipe_point wait 0.2 seconds and do another swipe_point ?
If I will make it by:
swipe_points()
sleep(0.2)
swipe_points()

The sleep delay can be much higher - and not stable.

**Comment by mingyuan-xia** [comment]
zoom into the implementation of `swipe_pionts`.
Read: https://source.android.com/devices/input/touch-devices

**Comment by codeskyblue** [comment]
why not use click sleep and then click

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
