### ISSUE TITLE
APP弹出窗口dump_hierarchy的元素的bounds与 adb dump出来的不一致

### ISSUE THREAD

**Issue by mitchychien** [openatx/uiautomator2#417]
测试手机：安卓9.0 展锐测试机
如下图fmradio应用（其他应用的弹出窗口也有该问题，非弹出页面没有问题）：
**adb获取的bounds:**
![adb](https://user-images.githubusercontent.com/54353651/63420149-b24b4200-c438-11e9-8a9a-881680154bf2.png)

**u2获取的boudns:(right,bottom坐标有偏差)**
![uiautomator2](https://user-images.githubusercontent.com/54353651/63420150-b24b4200-c438-11e9-9797-8d9ee438a8be.png)

**Comment by codeskyblue** [comment]
先关了，下次遇到再说
