### ISSUE TITLE
d.screenshot("xxx.png")截图的像素有偏差

### ISSUE THREAD

**Issue by mitchychien** [openatx/uiautomator2#418]
测试手机：安卓9.0 展锐测试机
uiautomator2的版本号：Version: 1.0.4.dev4

如下图：目测是一样的，但放大后使用U2截的图中图标边缘处有蓝色噪点，每次噪点随机，并不固定。
![无标题](https://user-images.githubusercontent.com/54353651/63421450-2c7cc600-c43b-11e9-924e-a95c52131d8d.png)

**Comment by mingyuan-xia** [comment]
u2用minicap screenshot实际是jpg，压缩过的，图像效果不稳定但是速度快和大小好
如果需要高保真稳定截图，用screencap或者直接获取drawing cache

**Comment by codeskyblue** [comment]
-_-!! 要求这么高

**Comment by mitchychien** [comment]
> -_-!! 要求这么高

要做图像对比，不能都偏差 ：）

**Comment by codeskyblue** [comment]
>> -_-!! 要求这么高 ...

@mitchychien 偏差一点没关系的

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
