### ISSUE TITLE
长时间运行会导致uiautomator的内存变大

### ISSUE THREAD

**Issue by zy9096** [openatx/uiautomator2#422]
uiautomator-server version：1.1.7
如图，麻烦看一下是否存在内存泄露的问题
![image](https://user-images.githubusercontent.com/19945764/63569851-a1700d00-c5ad-11e9-8993-127b4c71cafa.png)

**Comment by mingyuan-xia** [comment]
请提供几次的hprof dump用于分析，未发现明显OOM问题

**Comment by codeskyblue** [comment]
跑个一天试试

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zy9096** [comment]
ps：我发现在屏幕熄屏的情况下，apk占用的内存会持续变大，此时dump_hierarchy是不是会存在问题？

**Comment by codeskyblue** [comment]
只要暂时没有大的离谱，就ok。目前这个还不是主要问题

**Comment by yaming116** [comment]
https://github.com/openatx/android-uiautomator-server/pull/34

okhttp这块使用会产生线程结束不掉，不知道是不是这块引起的

**Comment by zhizunbao84** [comment]
我现在在自动化测试一个apk，运行时间长了以后，该apk就会变得很慢，手机内存不够了

**Comment by jiajia172000** [comment]
确实存在这个问题。我自动答题学习强国，出现过内存占用过大运行慢，但是后来重新安装atxagent以及修改了代码后，莫名其妙消失了。

**Comment by fjf123456** [comment]
确实存在这个问题，我用了2台机子，刚开始溜溜的，后面跑到没内存慢的要死
