### ISSUE TITLE
handling touch events

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#423]
I am not too familier with android developments.
I am tring to understand whether the touch events this repo send using the ADB is with sendevent or "tap" ?

Since **adb - tap** will skip the **sendevent** - and 3'rd app controlled using the ADB can detect it been controlled since the touch is not as human do.

Can someone shade light on it ?

notes:
https://stackoverflow.com/questions/4386449/send-touch-events-to-a-device-via-adb
https://stackoverflow.com/questions/3437686/how-to-use-adb-to-send-touch-events-to-device-using-sendevent-command

**Comment by instasck** [comment]
![image](https://user-images.githubusercontent.com/43851500/63652308-a1b40800-c767-11e9-9510-75bd461c5e71.png)
I found out this repo is using the iput method and not the sendevent which is different in tems of detections.

**Comment by mingyuan-xia** [comment]
Basic one-off operations turn to "input" utility.
Real-time touch events go to `minitouch`.

**Comment by instasck** [comment]
> Basic one-off operations turn to "input" utility.
> Real-time touch events go to `minitouch`.

Do you think application can identify real touch and fake one ?

**Comment by mingyuan-xia** [comment]
Injected events can always be detected, depending on whether the app wants to do so or not.
This lib is for testing, not for security related purposes.

**Comment by instasck** [comment]
> Injected events can always be detected,

I want to know more (and pay for it) so I found you and msg you if that is ok.
