### ISSUE TITLE
app_start(stop=False)总是先杀死进程再拉起app

### ISSUE THREAD

**Issue by zuinjly** [openatx/uiautomator2#425]
- samsang s6 
- uiautomator2   1.2.1.dev3

在模拟app切换前后台时，用到了如下代码：
                self.d.press("home")
                time.sleep(5)
                self.d.app_start("com.xxxx.xxxx")

在uiautomator2 ver0.2.3时，可以正常使用，今天更新到1.2.1后，发现每次app_start，都是杀死了app后再次拉起，看了下app_start的代码，发现有了更改，原来v0.2.3的app_start只能用self.d.app_start("com.xxxx.xxxx", use_monkey=True)替代；而v1.2.1下app_start("com.xxxx.xxxx")虽然默认stop=False，仍会使app重启，貌似和默认的-S参数有关？
![image](https://user-images.githubusercontent.com/17973158/63749364-d8139380-c8dd-11e9-817c-5dff040419b2.png)

**Comment by mingyuan-xia** [comment]
欢迎PR

**Comment by codeskyblue** [comment]
这个我正在弄，别提pr了

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
fixed in 1.2.1

**Comment by Louis24** [comment]
> fixed in 1.2.1

为什么一加手机 我写的好友申请  最近不能用了呢  每次都
