### ISSUE TITLE
用的夜神模拟器，不能显示模拟器界面，黑屏，但是元素信息能出来

### ISSUE THREAD

**Issue by kxltsuper** [openatx/uiautomator2#430]
用的夜神模拟器，不能显示模拟器界面，黑屏，但是元素信息能出来，请问这是什么原因？
我现在摸瞎的获取元素信息。。。。效率太低了。

如何实现Appetizer里的界面与模拟器的界面同步显示出来(不黑屏)。谢谢！

**Comment by codeskyblue** [comment]
@mingyuan-xia 模拟器你没有安装minicap吧

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mingyuan-xia** [comment]
新版Appetizer会检测出模拟器并拒绝投屏

**Comment by kxltsuper** [comment]
> 新版Appetizer会检测出模拟器并拒绝投屏

怎么破？用老版本的吗，具体要在哪个版本以下呢？

**Comment by kxltsuper** [comment]
> @mingyuan-xia 模拟器你没有安装minicap吧
> 
> Sent with [GitHawk](http://githawk.com)

安装了，不行。后来查资料说安装minicap不行，又删除，还是不行。

**Comment by mingyuan-xia** [comment]
模拟器不支持投屏

**Comment by kxltsuper** [comment]
> 模拟器不支持投屏

谢谢！那有没有能支持模拟器投屏的方法？

**Comment by mingyuan-xia** [comment]
目前没有，模拟器并非我们主要支持的场景，模拟器是用来玩游戏的不是用来测试的

**Comment by codeskyblue** [comment]
@mingyuan-xia 这个先别关

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
