### ISSUE TITLE
atx-agent recover failed

### ISSUE THREAD

**Issue by monicadanesa** [openatx/uiautomator2#432]
Hi all,

I have tried to install uiautomator2 in env (pipenv) and connect using this command 
```
import uiautomator2 as u2
d = u2.connect()
```

and I got the error message :
`atx-agent recover failed`

How to solve the atx agent recover failed?

**Comment by monicadanesa** [comment]
i closed because i forget to call `python3 -m uiautomator2 init`

**Comment by codeskyblue** [comment]
github上的代码里面，我增加了一个功能 connect_usb(init=True)  自带init功能，不防试试

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by monicadanesa** [comment]
thanks for replying, anyway is it possible I am not run`python3 -m uiautomator2 init` for the first time? only `pip install uiautomator2`

**Comment by codeskyblue** [comment]
With the following step, you do not need to run `uiautomator2 init`
Suppose your android serial is `aabbcc`

With the following code

```python
import uiautomator2 as u2

d = u2.connect_usb("aabbcc", init=True)
print(d.info)
```

**Comment by monicadanesa** [comment]
Hi I have followed the code, but I got the error message 
`TypeError: connect_usb() got an unexpected keyword argument 'init'`

**Comment by codeskyblue** [comment]
you need install from source code

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
1.2.3 版本，已发布

**Comment by linxiaofeng** [comment]
Hi,使用美图手机尝试执行connect()会报相同的错误（已经执行过init方法），问下该如何定位问题
