### ISSUE TITLE
scroll 不稳定和执行速度问题

### ISSUE THREAD

**Issue by mitchychien** [openatx/uiautomator2#433]
1. d(scrollable=True).scroll.horiz.forward()  每次执行scroll的steps不是很固定，按理来说应该是当前元素的宽度。
2. d(scrollable=True).scroll.horiz.forward(steps=100) 带 steps参数后执行速度很慢，比不带参数慢很多。

**Comment by mitchychien** [comment]
问题1已找到其他方式解决

**Comment by codeskyblue** [comment]
1 step 印象中大约 20ms
