### ISSUE TITLE
红米k20密码框使用send_keys导致键盘多次弹出（8次左右），并且有时无法正确输入

### ISSUE THREAD

**Issue by su1216** [openatx/uiautomator2#434]
- redmi k20
- 2-1.2.3.dev4

```
d(className="android.widget.EditText", resourceId="密码框id").click()
sleep(1)
self.d.send_keys("abc")
```

现象，click时，小米安全键盘正常弹出，输入密码时，键盘不断重新弹出，然后才能输入密码，输入密码之后，点击键盘中完成按钮，有时无法点击，会变成在键盘中输入"y"

**Comment by codeskyblue** [comment]
输入法设置里面，你看看有没有 关闭安全输入法

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/64410972-c476e280-d0be-11e9-9a71-617ef68a3e33.png)

**Comment by su1216** [comment]
> 输入法设置里面，你看看有没有 关闭安全输入法

有，可关闭
