### ISSUE TITLE
Use Google keyboard instaed of uiautomator2

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#435]
Can I show on the screen the keyboard of google, and type using this keyboard while testing my app ?

The size diffrent is what bothers me.

**Comment by codeskyblue** [comment]
call set_fastinput_ime(False)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by instasck** [comment]
> call set_fastinput_ime(False)
> 
> Sent with [GitHawk](http://githawk.com)

so self.device.send_keys(char) will work with any keyboard ?

**Comment by codeskyblue** [comment]
Try this: `d.shell("input text 1234")`

**Comment by instasck** [comment]
I managed to work it out with minitouch
