### ISSUE TITLE
请问uiautomator2是否支持操作手机复制粘贴

### ISSUE THREAD

**Issue by freedom-wy** [openatx/uiautomator2#438]
请问uiautomator2是否支持操作手机复制粘贴？
如复制手机中短信内容到剪切板，再从剪切板粘贴到记事本中。

**Comment by yaming116** [comment]
不明白场景？为啥不是获取文字直接输入到记事本中？

**Comment by codeskyblue** [comment]
获取剪贴板的内容可以用来做测试的断言

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaming116** [comment]
如果需要可以添加两个方法支持，设置剪贴板和获取

**Comment by codeskyblue** [comment]
已支持
