### ISSUE TITLE
请群主核实下我被踢出qq群的原因

### ISSUE THREAD

**Issue by submarinezy** [openatx/uiautomator2#441]
*提Bug需要注意的事项*
在私聊群主请教3个问题后，今天登录qq发现踢出群，且加不上群主qq。与群主交谈过程中未发生不愉快。我本人对群主无任何恶意，也未在群内起哄、发广告、私加群友。请群主确认下是不是认错人了。本人还非常想进群与大家一起探讨，学习，请群主核查，谢谢

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
昵称没改，或者是发黄图，聊黑产信息。 如果这些都不属于，你就再加一次。
