### ISSUE TITLE
keep awake method

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#446]
I am running my phones with WIFI and not-Charging.
What is the best method to keep the phone awake for testing during the day.
it need to run for 30 minute every 2 hours. so in that 2 hours I am trying to check for ping and when ping fail I do screen on screen off, it will keep the phone wifi awake for longer.

But still I am facing issues as ADB ERROR and HTTP RECEIVE TIMEOUT.
I tried various applications on the phone to keep wifi but it not working.

**Comment by hypery11** [comment]
svc power stayon true

**Comment by mingyuan-xia** [comment]
DO not use the issue tracker as question board. Use QQ group: 499563266 for questions

**Comment by mingyuan-xia** [comment]
https://android.stackexchange.com/questions/109955/what-does-svc-power-stayon-wireless-do
