### ISSUE TITLE
Avoid using setup_requires parameter in setup.py

### ISSUE THREAD

**Issue by chrisoro** [openatx/uiautomator2#448]
Pip doesn't support installation packages using setup_requires because that option causes distutils to install packages without using PIP. Therefore any PIP configuration are ignored for packages listed in setup_requires. Using setup_requires requires that pip has no way of controlling where these dependencies are located.

You should instead probably specify project requirements in a file called requirements.txt. 

See:
- https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires
- https://github.com/django-guardian/django-guardian/pull/638
- pytest-dev/pytest-xdist#136

**Comment by mingyuan-xia** [comment]
we used `setup_requires` for pbr (more of a legacy) not for any actually dependency.
pbr is a setuptool helper lib from openstack, and `setup_requires` is still a suggested way to use it. See: https://docs.openstack.org/pbr/latest/user/using.html#requirements
Also you can find the `requirements.txt` is actually managing all deps we have now.

**Comment by chrisoro** [comment]
I understand but currently, it is impossible to install uiautomator2 without an internet connection since or proxy setup. setup_requires circumvents pip completely and tries to create it's own access.

I can't do `pip install uiautomator2` without a working connection to https://pypi.org/simple/pbr

This is quite easy to fix, you could actuall drop pbr completely since all that you use it for, has been added to python in the last few years.

Do you want me to create a PR to show it to you?

**Comment by mingyuan-xia** [comment]
Yes pls. We would review if pbr is still needed, especially when we have decided to drop for python<=3.5.

**Comment by codeskyblue** [comment]
Thanks for your contribution, but pbr is not going to remove for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chrisoro** [comment]
@codeskyblue so you are OK with that it's not possible to install uiautomator2 in any offline or restricted network environment?

I would argue that most users use uiautomator for replicated android testing in a restricted environment (vm).

But as you are maintainer, up to you. This PR doesn't change anything regarding functionality, it is simply the same without pbr.
