### ISSUE TITLE
dump_hierarchy偶尔准确偶尔不准确

### ISSUE THREAD

**Issue by zhizunbao84** [openatx/uiautomator2#449]
win7 64位，python3.6 64位
- 手机型号：逍遥模拟器
- uiautomator2的版本号(`pip show uiautomator2`)    1.3.4
用dump_hierarchy函数获取页面信息有时候准确，有时候不准确（获取的信息跟页面显示内容完全不一样）
但是我用命令行adb shell uiautomator dump却可以获取到页面信息。

**Comment by codeskyblue** [comment]
能不能给个截图

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhizunbao84** [comment]
什么截图呢?!

**Comment by zhizunbao84** [comment]
我是在android.webkit.WebView里面有一个或多个android.widget.EditText。我是在模拟器里面搞。
今天白天的时候我用uiautomator2的dump_hierarchy(compressed=False)获取，根本获取不到；用命令行adb shell uiautomator dump却可以获取，但是bounds确实负值。
我刚才克隆出个模拟器，用命令行adb shell uiautomator dump测试，却可以获取。但没有用dump_hierarchy(compressed=False)测试。
这是为啥呢呀。
而且有的元素我用dump_hierarchy(compressed=False)获取，和用dump_hierarchy(compressed=False)获取到的bounds不一样。

**Comment by zhizunbao84** [comment]
这个跟adb 的版本或者uiautomator的版本有关系么

**Comment by mingyuan-xia** [comment]
1. webview内不支持，不同安卓版本webview版本不同本来就很不一样
2. `adb shell uiautomator dump` 没有可比性
3. 建议去看看WebView.enableDebugging一个开关
4. 模拟器不是我们支持的重点
