### ISSUE TITLE
app_install 失败

### ISSUE THREAD

**Issue by hctest1** [openatx/uiautomator2#451]
安装报ZeroDivisionError错误，但是最终包还是安装到手机了，可是程序会抛异常

- 手机型号
荣耀 10 青春版（HRY-AL00a ）
HUAWEI C8817E

- uiautomator2的版本号
1.3.6
- 代码
![image](https://user-images.githubusercontent.com/47594453/66380079-44a7a500-e9e9-11e9-8feb-4aa59a7e46dd.png)

- 相关日志
![image](https://user-images.githubusercontent.com/47594453/66381248-889ba980-e9eb-11e9-8d5f-c8336dbba539.png)

**Comment by codeskyblue** [comment]
👍
