### ISSUE TITLE
更新了uiautomator2的版本，Watchers.watched无法使用

### ISSUE THREAD

**Issue by sqoneal** [openatx/uiautomator2#452]
调用Watchers.watched会报以下错误：
-32601 Method not found: <method not found> data: , method: hasWatchedOnWindowsChange

查了一下新版本把watcher弃用了，请问权限窗口这种突发的弹窗如何控制？以前都是通过watcher控制的。

**Comment by codeskyblue** [comment]
可以使用d.xpath.when代替

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sqoneal** [comment]
> 可以使用d.xpath.when代替
> 
> Sent with [GitHawk](http://githawk.com)

这样是不是就不能有watcher的预先监控的效果了？要实现全程监控是得开一条单独的线程吧？

**Comment by codeskyblue** [comment]
目前的做法就是单开一个线程。你看看文档
https://github.com/openatx/uiautomator2/blob/master/uiautomator2/ext/xpath/README.md
