### ISSUE TITLE
为啥self.touch不加上转换相对值的方法以支持相对坐标呢?

### ISSUE THREAD

**Issue by TsingWei** [openatx/uiautomator2#454]
`self.touch`这里面https://github.com/openatx/uiautomator2/blob/3df7203e19f96134b14d05c15eb7a4c40dbdaef7/uiautomator2/session.py#L347
为啥不加上转换相对到绝对值的方法
```
x, y = self.pos_rel2abs(x, y)
```
是有什么顾虑么?

**Comment by codeskyblue** [comment]
click支持相对坐标。d.touch.down目前是作为一个高级底层用法，最好还是不过多的封装。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
