### ISSUE TITLE
播放视频10分钟时间左右后，uiautomator2起不来了

### ISSUE THREAD

**Issue by zhizunbao84** [openatx/uiautomator2#456]
![222222222229](https://user-images.githubusercontent.com/2263408/66725264-c755b780-ee62-11e9-8c51-8cf3c33f3bf3.png)
![333333333336](https://user-images.githubusercontent.com/2263408/66725269-cfadf280-ee62-11e9-8f8a-fb1cae5abebd.png)
操作某个app播放视频10分钟时间左右后，uiautomator2起不来了，提示uiautomator start failed，提示是jsonrpc http_timeout.

可以考虑个长连接什么的？

**Comment by mingyuan-xia** [comment]
atxagent.log
adb logcat

**Comment by zhizunbao84** [comment]
嗯嗯，我在网上搜，说uiautomator只有在空闲的时候才能工作，是不是播放视频的时候就导致了uiautomator2起不来呢
我目前是直接adb shell input 坐标的方式暂停视频，然后继续。

**Comment by wwangchaohui** [comment]
我最近也遇到了这个问题,研究了一天.
看这里https://github.com/openatx/atx-agent/issues/56
3分钟/jsonrpc/0接口没有请求，关闭uiautomator服务.．
这个是作者添加的一个功能

只能在ATX 是手动停止axt-agent，重启下．
或者
 adb shell ./data/local/tmp/atx-agent server  --stop
