### ISSUE TITLE
Android 手机长时间运行后HTTPConnectionPool(host='127.0.0.1', port=50421): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by lifxia** [openatx/uiautomator2#459]
- 手机型号

Lenovo L78071 | Z5s  |9.0  

nubia | NX616J | Z18S | 8.1.0

Sony | H9493 | Xperia XZ3 | 9

- uiautomator2的版本号(`pip show uiautomator2`)

- 手机截图
- 相关日志
HTTPConnectionPool(host='127.0.0.1', port=48761): Read timed out. (read timeout=60)
- 最好能附上可能复现问题的代码。
大概运行2-3h后进行当前页面无元素可点
进行测试APP及uiautomator重启
 self._device = u2.connect_usb(self._deviceid)
self._sess = self.device.session()

已在重启前手动启动atx-agent server及uiautomator的apk
日志如下：
atx-agent 启动 adb -s d8590de9 shell /data/local/tmp/atx-agent server -d
2019/10/16 09:43:53 [INFO][github.com/openatx/atx-agent] main.go:513: atx-agent listening on 10.2.41.0:7912
运行命令行：adb -s d8590de9 shell am start -n com.github.uiautomator/com.github.uiautomator.MainActivity
Starting: Intent { cmp=com.github.uiautomator/.MainActivity }
Warning: Activity not started, its current task has been brought to the front
多次运行重启后抛异常

atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"

**Comment by lifxia** [comment]
Name: uiautomator2
Version: 0.2.3
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location:.local/lib/python2.7/site-packages
Requires: logzero, fire, retry, docopt, progress, humanize, requests, whichcraft, six
Required-by:

**Comment by wGodlike** [comment]
同问
