### ISSUE TITLE
long_click长按，会有两次点击操作

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#46]
sess(text=u"哈哈哈 哎呦呦").long_click()
sess(text=u"删除回复").click()

本来长按一个回复内容，弹出框，想点击“删除回复”。
但是实际效果：弹出框也弹了，但是又有一个点击操作，点击了回复内容，
使得页面跳到另外一个页面了。
sess(text=u"删除回复").click()就点击不到了。

**Comment by codeskyblue** [comment]
手机啥型号

**Comment by HeartIsBeat** [comment]
华为BLN-AL30

**Comment by codeskyblue** [comment]
神奇

**Comment by HeartIsBeat** [comment]
@codeskyblue ┭┮﹏┭┮有办法么。

**Comment by codeskyblue** [comment]
重启下手机试试，我想不到好方法了

**Comment by HeartIsBeat** [comment]
@codeskyblue 重启一下，总会出现连接不上uiautomator问题。即使手动开启uiautomator，也还是这个错误
requests.exceptions.ConnectionError: HTTPConnectionPool(host='x.x.x.x', port=7912): Max retries exceeded with url: /shell (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025AB7CFB668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
![image](https://user-images.githubusercontent.com/20472976/36824545-e97408aa-1d3d-11e8-9b80-68d3d0819cc4.png)
![image](https://user-images.githubusercontent.com/20472976/36824564-fdb07cb8-1d3d-11e8-90e5-c2492ce85ed0.png)
可解决办法：python -m uiautomator2 init 重新安装一下才可以。

**Comment by HeartIsBeat** [comment]
![image](https://user-images.githubusercontent.com/20472976/36825418-46f05642-1d42-11e8-981f-ae141a6b4193.png)
好像管用的就 launch atx-agent daemon这句。
是因为重启后，守护进程不会自启动？

**Comment by codeskyblue** [comment]
恩，不会启动

**Comment by HeartIsBeat** [comment]
有没有启动 守护进程的命令？ 
uiautormator停止atxagent后，就无法启动atxagent了。
只能重装下uiautomator2？
@codeskyblue

**Comment by codeskyblue** [comment]
long_click之前加上运行下面的代码试试

```python
d.jsonrpc.setConfigurator({"actionAcknowledgmentTimeout": 40})
```

**Comment by HeartIsBeat** [comment]
Name: uiautomator2
Version: 0.1.3.dev1
版本的长按ok了

**Comment by codeskyblue** [comment]
是修改了Configurator还是什么都没动

**Comment by HeartIsBeat** [comment]
什么都没动哦
