### ISSUE TITLE
使用d(scrollable=True).scroll(steps=10)报错处理

### ISSUE THREAD

**Issue by msw1535540** [openatx/uiautomator2#460]
手机：华为畅享9plus

使用代码d(scrollable=True).scroll(steps=10)运行滑动操作，抛出异常
-32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[SCROLLABLE=true], method: scrollForward
请问该怎么处理？

**Comment by mingyuan-xia** [comment]
“UiObjectNotFoundException”

**Comment by HiHub2019** [comment]
解决了吗
