### ISSUE TITLE
[W 191023 11:04:20 xpath:31] lxml was not installed, xpath will not supported

### ISSUE THREAD

**Issue by ThickBull** [openatx/uiautomator2#461]
该异常出现的场景：U2的1.3.6版本+python3.8.0版本
在uiautomator2/xpath.py文件的源码
try:
    from lxml import etree
except ImportError:
    logger.warning("lxml was not installed, xpath will not supported")
该异常标明，from lxml import etree导包失败。
当python版本切换为3.7.2时，导包是成功的，不再出现该异常。
在python3.8.0版本下已尝试改变lxml库的版本，但仍未解决。
请版主支撑。

**Comment by codeskyblue** [comment]
是lxml这个库装装不上去吗？

**Comment by cv936669367** [comment]
是会出现这个问题 幸亏 anaconda切换版本能解决 但是后续版本会优化吗

**Comment by codeskyblue** [comment]
现在强制安装了，哈哈
