### ISSUE TITLE
调用Session对象获取到ui_object对象后，存在一段短暂的时间，这段时间用len方法获取ui_object对象的长度，返回0

### ISSUE THREAD

**Issue by bluesnoblue** [openatx/uiautomator2#464]
![IMG20191023_164014](https://user-images.githubusercontent.com/28392064/67374845-5d50b700-f5b4-11e9-83db-d3ef20ce5072.jpg)

**Comment by mingyuan-xia** [comment]
你全擦掉了，让上帝来调试么？
elements的那行，只是设置了一个selector，屏幕在动画或者转场或者加载时都会存在元素不稳定状态
最简单wait就好了
