### ISSUE TITLE
升级了之后，怎么以前的方法还去掉了，以前的脚本还要重新修改

### ISSUE THREAD

**Issue by qing0404** [openatx/uiautomator2#473]
**版本升级了，可以新增，但是以前的不应该去掉啊，这样，以前的脚本全都要重新改一遍**
如：
d.info.get('screenOn')  升级之后返回None
启动app，d.app_start(pkg_name=...)  升级后变成d.app_start(package_name=...) 
d(resourceId=...).wait()  升级后，wait方法也找不到了
应该还有其他很多改动了的，还不知道

Name: uiautomator2
Version: 2.0.1.dev7

**Comment by codeskyblue** [comment]
一个个的回复你。

之所已升级是因为升级之后功能稳定了很多。缺点就是有一些功能丢失了。所以这个版本升了第一位版本号，表示这个版本有不能向后兼容的更新。

- d.info 试了下这个screenOn还真没有了。
- d.app_start("com.example.app") 这个你直接写，不要用 package_name=的这种方法。
- toast, 和 d.touch.dowm 这两个也暂时不能用了

**Comment by zangtian2** [comment]
d.serial好像有bug

**Comment by qing0404** [comment]
d.touch.dowm这个不能用了，那long_click也不能用了

丢失的功能有个列表吗？可以对照着，一次都改完

**Comment by qing0404** [comment]
我想把版本回退到1.3.7，要怎么操作啊？

**Comment by codeskyblue** [comment]
pip3 install "uiautomator2<2.0" -U

**Comment by codeskyblue** [comment]
正在改

**Comment by codeskyblue** [comment]
改完啦，原来的功能回来了。抱歉抱歉
