### ISSUE TITLE
XPath will cause ValueError if class is empty

### ISSUE THREAD

**Issue by AlecHaring** [openatx/uiautomator2#475]
I noticed that almost every time I tried to use an xpath selector, I'd get this error:
` File ".../venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 431, in all
    node.tag = safe_xmlstr(node.attrib.pop("class"))
  File "src/lxml/etree.pyx", line 991, in lxml.etree._Element.tag.__set__
  File "src/lxml/apihelpers.pxi", line 1644, in lxml.etree._getNsTag
  File "src/lxml/apihelpers.pxi", line 1679, in lxml.etree.__getNsTag
ValueError: Empty tag name
`

After looking into it, it seems like if the hierarchy has an element with an empty class, it will throw an error because you are replacing the xml tag with the class attribute. I replaced
`node.tag = safe_xmlstr(node.attrib.pop("class"))`
with
`node.tag = safe_xmlstr(node.attrib.pop("class")) if node.attrib.get("class") != "" else "node"`
in xpath.py as a temperary fix which seems to fix the problem

An example of an element that would throw an error would be:
`{'index': '0', 'text': '', 'resource-id': '', 'class': '', 'package': .... }`

**Comment by codeskyblue** [comment]
Check it now.

**Comment by AlecHaring** [comment]
Works great. Thanks
