### ISSUE TITLE
XMLElement中引用了无效的成员变量_parent

### ISSUE THREAD

**Issue by daihongliang** [openatx/uiautomator2#477]
class XMLElement(object):
    def __init__(self, elem, d: "uiautomator2.Device"):
        """
        Args:
            elem: lxml node
            d: uiautomator2 instance
        """
        self.elem = elem
        self._d = d
这里面的成员变量已经修改成了self._d，但后面的click方法中还在用self._parent，swipe方法中也是一样
def click(self):
        """
        click element
        """
        x, y = self.center()
        self._parent.send_click(x, y)

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
Thanks
