### ISSUE TITLE
Flutter空间可以识别但click操作无反应

### ISSUE THREAD

**Issue by chenxue1011** [openatx/uiautomator2#482]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号：小米6
- uiautomator2的版本号(`pip show uiautomator2`)： 2.0.0
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by weiaiSanli** [comment]
小米机型需要模拟按键权限,这个是系统权限,在稳定版的开发者模式中是没有的,你需要将手机刷成MIUI开发版本以后再开发者模式中打开模拟按键就可以正常使用了!
