### ISSUE TITLE
List of supported devices 设备兼容性情况

### ISSUE THREAD

**Issue by sionking** [openatx/uiautomator2#489]
is there a list of supported (tested) devices somewhere?
I can tell Xiaomi redmi GO works well.
A6 looses connection many times need a reboot.

**Comment by codeskyblue** [comment]
Looks like a good advice.

**Comment by codeskyblue** [comment]
1. host a cloud server
2. write a command to check if device if supported.
3. show list on the cloud server

**Comment by codeskyblue** [comment]
Device tested by myself

- 小米 MIX 2
- 坚果 Pro 3
- 锤子 M1
- OPPO Y67
- 华为 DIG-AL00
- 魅族 16

**Comment by mingyuan-xia** [comment]
我们有数据，可以提供一个简单的，明年考虑安排上

**Comment by xubodreamsky** [comment]
请问是否可以用虚拟机

**Comment by codeskyblue** [comment]
可以用虚拟机 @xubodreamsky  列表先不整了，没空弄
