### ISSUE TITLE
uiautomator會在執行的時候，每三分鐘重啟一次

### ISSUE THREAD

**Issue by troub1emaker-sys** [openatx/uiautomator2#497]
- 手机型号: Google Pixel 2
- uiautomator2的版本号: 2.3.1
- 相关日志
`C:\Users\user\AppData\Local\Temp\_MEI118322\uiautomator2\__init__.py:509:` RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
[D 191209 10:22:01 __init__:696] force reset uiautomator
[D 191209 10:22:01 __init__:720] Product-brand: google
[D 191209 10:22:01 __init__:739] uiautomator is starting ...
[D 191209 10:22:02 __init__:739] uiautomator is starting ...
[D 191209 10:22:03 __init__:739] uiautomator is starting ...
[I 191209 10:22:04 __init__:700] uiautomator back to normal
[D 191209 10:25:52 __init__:696] force reset uiautomator
[D 191209 10:25:52 __init__:720] Product-brand: google
[D 191209 10:25:53 __init__:739] uiautomator is starting ...
[D 191209 10:25:54 __init__:739] uiautomator is starting ...
[D 191209 10:25:55 __init__:739] uiautomator is starting ...
[D 191209 10:25:56 __init__:739] uiautomator is starting ...
[D 191209 10:25:57 __init__:739] uiautomator is starting ...
[D 191209 10:25:58 __init__:739] uiautomator is starting ...
[I 191209 10:25:58 __init__:700] uiautomator back to normal
[D 191209 10:28:52 __init__:696] force reset uiautomator
[D 191209 10:28:52 __init__:720] Product-brand: google
[D 191209 10:28:53 __init__:739] uiautomator is starting ...
[D 191209 10:28:54 __init__:739] uiautomator is starting ...
[D 191209 10:28:55 __init__:739] uiautomator is starting ...
[D 191209 10:28:56 __init__:739] uiautomator is starting ...
[D 191209 10:28:57 __init__:739] uiautomator is starting ...
[D 191209 10:28:58 __init__:739] uiautomator is starting ...
[I 191209 10:28:58 __init__:700] uiautomator back to normal`

uiautomator會在執行的時候，每三分鐘重啟一次

**Comment by shijie93** [comment]
同样遇到了这个问题

**Comment by codeskyblue** [comment]
我也很头疼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AllenLuosong** [comment]
你们脚本中有这个操作吗？
# 开启uiautomator 防止重复启动
**d.service("uiautomator").start()**

**Comment by troub1emaker-sys** [comment]
> 你们脚本中有这个操作吗？
> 
> # 开启uiautomator 防止重复启动
> **d.service("uiautomator").start()**

沒有寫到這行耶
加這個可解嗎

**Comment by codeskyblue** [comment]
@troub1emaker-sys 再更新一下uiautomator2, 连接USB重新connect 试试，更新了一下apk，修复了一下内存泄漏的问题。可能会好一些。

**Comment by troub1emaker-sys** [comment]
> @troub1emaker-sys 再更新一下uiautomator2, 连接USB重新connect 试试，更新了一下apk，修复了一下内存泄漏的问题。可能会好一些。

經過這陣子的測試，情況有穩定多了，不過還是偶爾會跳出connection is not stable。

uiautomator2的版本号: 2.3.1
atx的版本号: 0.8.2
apk的版本号: 2.1.1

[I 200115 14:26:08 __init__:539] Device connection is not stable, rerun init-atx-agent ...
