### ISSUE TITLE
from aircv import Aircv 無法成功導入

### ISSUE THREAD

**Issue by kobojp** [openatx/uiautomator2#498]
雷電模擬器
uiautomator2的版本号(2.3.2)

import uiautomator2 as u2
from aircv import Aircv
u2.plugin_register('aircv', Aircv)
d = u2.connect('127.0.0.1:5555') # alias for u2.connect_wifi('192.168.5.4')

錯誤訊息
from aircv import Aircv
ModuleNotFoundError: No module named 'aircv'

我從\Lib\site-packages\uiautomator2\ext-archived\aircv 是有這個資料夾的。
該如何解決 請大神幫幫忙

**Comment by codeskyblue** [comment]
aircv目前还不能作为插件，你这个功能目前没有。
