### ISSUE TITLE
华为mate20_pro (Android 10) init错误：listen tcp :7912 :socket: operation not permitted

### ISSUE THREAD

**Issue by lau8889** [openatx/uiautomator2#499]
- 手机型号
华为mate20pro
- uiautomator2的版本号(`pip show uiautomator2`)
uiautomator2 2.3.2
- 相关日志
pc端：
Check atx-agent version
Forward: local:tcp:49474 -> remote:tcp:7912
步骤报错：10054] 远程主机强迫关闭了一个现有的连接

手机端atx-agent.log：
internet is not connected.2019/12/13 10:54:06 [1;35[Fatal] main.go:532 listen tcp :7912:socket: operation not permitted [0m

**Comment by lau8889** [comment]
matepro20安卓版本是android10，我用另外两台华为手机，以及android9的三星s8都能初始化成功，是不适配android10吗

**Comment by lau8889** [comment]
看起来是atx-agent的权限不足，我在pc端命令行使用adb shell 打开服务时也报权限不足

**Comment by lau8889** [comment]
app是否能添加system权限解决这个问题

**Comment by lau8889** [comment]
pc命令行调用adb shell /data/local/tmp/atx-agent server --port=7912
报错main.go listen tcp :7912 :socket: operation not permitted

**Comment by mingyuan-xia** [comment]
看来10的adb shell被进一步限制了
`app是否能添加system权限解决这个问题` 你试试呢

**Comment by lau8889** [comment]
Samsung S10初始化啥的没有问题，估计是华为mate20pro的锅，应用那把能加的权限都加了也不行
