### ISSUE TITLE
关于Android 4.2.2　d.info

### ISSUE THREAD

**Issue by 5368** [openatx/uiautomator2#5]
http://192.168.168.116:7912/version
可以回显0.0.6版本

不能打印d.info

能启动和关闭app
------------------------------------------------------------------------------------
d.press('back')
  File "/home/jet/wtm/uiautomator2/uiautomator2/__init__.py", line 485, in press
    return self.jsonrpc.pressKey(key)
  File "/home/jet/wtm/uiautomator2/uiautomator2/__init__.py", line 151, in __call__
    return self.server.jsonrpc_call(self.method, params)
  File "/home/jet/wtm/uiautomator2/uiautomator2/__init__.py", line 175, in jsonrpc_call
    raise UiaError(self._server_jsonrpc_url, data, res.status_code, res.text, "HTTP Return code is not 200", res.text)
uiautomator2.UiaError: ('http://192.168.168.116:7912/jsonrpc/0', '{"params": ["back"], "jsonrpc": "2.0", "id": "3c437a0a91cb550457002078bf9a6eed", "method": "pressKey"}', 502, u'', 'HTTP Return code is not 200', u'')

**Comment by codeskyblue** [comment]
/sdcard/atx-agent.log中等的内容贴出来看看
