### ISSUE TITLE
三星手机samsung s9 get text的时候会带有“\u200e” 

### ISSUE THREAD

**Issue by youth0905** [openatx/uiautomator2#502]
三星手机samsung s9 get text的时候会带有“\u200e”, 小米手机就没这个问题

- 手机型号  samsung s9（SMG9600）
- uiautomator2的版本号(`pip show uiautomator2`)   Version: 0.1.4.dev23
- 手机截图
![image](https://user-images.githubusercontent.com/58931592/70958317-dac80d80-20b3-11ea-9c03-755a23f0a250.png)

- 相关日志

**Comment by codeskyblue** [comment]
正常，print的时候就变成中文了

**Comment by youth0905** [comment]
不是 因为有这个存在，get text的时候get不到





------------------ 原始邮件 ------------------
发件人: shengxiang <notifications@github.com&gt;
发送时间: 2019年12月30日 09:54
收件人: openatx/uiautomator2 <uiautomator2@noreply.github.com&gt;
抄送: youth0905 <1178041497@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[openatx/uiautomator2] 三星手机samsung s9 get text的时候会带有“\u200e”  (#502)




正常，print的时候就变成中文了

**Comment by youth0905** [comment]
if self.dev(text="蓝牙", resourceId="android:id/title").exists(timeout=3):
    self.dev(text="蓝牙", resourceId="android:id/title").click() #go into wifi interface
当使用上述方式去查找元素的时候，找不到对应的“text”， 只有蓝牙模块有这个问题，其他模块没有这个问题，经过调查发下是蓝牙模块get text的时候多了“\u200e”，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shengxiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 上午9:54
收件人:&nbsp;"openatx/uiautomator2"<uiautomator2@noreply.github.com&gt;;
抄送:&nbsp;"小youth"<1178041497@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openatx/uiautomator2] 三星手机samsung s9 get text的时候会带有“\u200e”  (#502)




正常，print的时候就变成中文了
