### ISSUE TITLE
uiautormator2 connect device Fail， error message is atx-agent recover failed

### ISSUE THREAD

**Issue by cffznz** [openatx/uiautomator2#504]
Hi:
I installed the uiautormator 2 with python 3.7.4 (python3 -m pip install uiautomator2)and also run the python3 -m uiautomator2 init successfully. But when I tried to use u2.connect('devicename') or u2.connect_usb('devicename', init=True), the error occurred as follwoing:
[I 191226 11:37:52 init:113] uiautomator2 version: 2.4.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python37\lib\site-packages\uiautomator2\__init__.py", line 189, in connect_usb
    raise RuntimeError("atx-agent recover failed")
RuntimeError: atx-agent recover failed
- Test device: vehicle head unit with Android 9 OS
- uiautomator2 2.4.0

Could you help me to reslove this problem?

**Comment by cffznz** [comment]
tried with uiautomator2 with version 2.4.1dev, still error with following information:
>>> d=u2.connect_usb('devicename',init=True)
[I 191226 14:12:12 init:113] uiautomator2 version: 2.4.1.dev1
c:\Python37\lib\site-packages\uiautomator2\__init__.py:180: RuntimeWarning: start atx-agent ...
  warnings.warn("start atx-agent ...", RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python37\lib\site-packages\uiautomator2\__init__.py", line 189, in connect_usb
    raise RuntimeError("atx-agent recover failed")
RuntimeError: atx-agent recover failed

**Comment by codeskyblue** [comment]
What kind phone you are using?

**Comment by cffznz** [comment]
It's not a phone, the test device is the vehicle navigation&infotainment unit with Android 9 OS

**Comment by codeskyblue** [comment]
感觉是/data/local/tmp没有执行权限，暂时还没修复

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 18512099608** [comment]
I have occure the same ploblem,my way to solve this is to reintall and it works.
