### ISSUE TITLE
aircv的路径问题

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#507]
aircv本来在uiautomator2\ext\路径下，新版本，aircv转到了uiautomator2\extext-archived路径下。
由于'extext-archived'存在‘-’，导致import时无法自动显示extext-archived，即使手动填写，运行时也会提示导入包错误，建议将aircv重新放回uiautomator2\ext\路径下。

**Comment by codeskyblue** [comment]
放到哪里就是说明不管它了。不过有另外一个替代品可以用。

安装方法 `pip3 install "uiautomator2[image]"`

```python
import uiautomator2 as u2
d = u2.connect()
d.image.click("setting.png")
```
