### ISSUE TITLE
Hide com.github.uiautomator and com.github.uiautomator.test

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#508]
I don't really understand what those 2 files are ?
Are they google apk files ? who creates them ?
Can I change the name of those packages and still be able to run this repo (while changing the relevant code)?

CAN I HIDE THEM FROM LISTMYAPP application or from "getInstalledPackages" as they where system applcations?

**Comment by codeskyblue** [comment]
These two apk is very necessary to run uitest. and can not be hided from `installedPackages`. To change the package name, I think you have to change atx-agent and uiautomator2(python lib)

**Comment by instasck** [comment]
> These two apk is very necessary to run uitest. and can not be hided from `installedPackages`. To change the package name, I think you have to change atx-agent and uiautomator2(python lib)

But who compiles those apk ? are they google owned or atx ? how can I change the package name of it ? where is the source code ?
