### ISSUE TITLE
怎么可以打包成apk在手机执行呢 

### ISSUE THREAD

**Issue by drduan** [openatx/uiautomator2#513]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by RocWangPeng** [comment]
我也想知道这个问题，如何把脚本打包apk

**Comment by XDSwang** [comment]
可以尝试把python 打包

**Comment by mingyuan-xia** [comment]
暂时没有计划支持
