### ISSUE TITLE
红米7升级最新的ut2后报错，系统是miui10

### ISSUE THREAD

**Issue by lewuyi** [openatx/uiautomator2#521]
Backend Qt5Agg is interactive backend. Turning interactive mode on.
[I 200209 15:20:22 init:132] uiautomator2 version: 2.5.3
[I 200209 15:20:22 init:248] skip version check for atx-agent dev
D:\anaconda\lib\site-packages\uiautomator2\__init__.py:378: RuntimeWarning: start atx-agent ...
  warnings.warn("start atx-agent ...", RuntimeWarning)
[D 200209 15:20:26 __init__:764] restart-uiautomator since "atx-agent restarted"
[D 200209 15:20:27 __init__:817] Device: xiaomi, fe479b2
D:\anaconda\lib\site-packages\uiautomator2\__init__.py:709: UserWarning: 404 page not found

  warnings.warn(res.text)

**Comment by codeskyblue** [comment]
atx-agent 保持最新，你这个是dev版本。
