### ISSUE TITLE
用screenshot出问题，提示OSError: [Errno PIL.Image.open IOError] cannot identify image file，已有解决方案

### ISSUE THREAD

**Issue by runningabcd** [openatx/uiautomator2#527]
error 1

File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uiautomator2/session.py", line 500, in screenshot
    raise IOError("PIL.Image.open IOError", ex)
OSError: [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x10d3791d0>

代码

    self.device.screenshot().save('abc.png')

error 2

File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uiautomator2/session.py", line 500, in screenshot
    raise IOError("PIL.Image.open IOError", ex)
OSError: [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x10d3791d0>

代码

    import requests
    r = requests.get(self.device._default_session.server.screenshot_uri, timeout=10, stream=True)
    logging.info(r.content)
    from PIL import Image
    import io
    ib = io.BytesIO(r.content)
    logging.info(ib)
    aux_im = Image.open(ib).convert("RGB")
    aux_im.save('abc.png')

正确的写法

查看了appium的screenshot 源码才发现，这个应该是uiautomator2的bug，截屏这块有问题

appium源码

      def get_screenshot_as_png(self):
           return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
      def get_screenshot_as_base64(self):
           return self.execute(Command.SCREENSHOT)['value']

uiautomator2 源码

        r = requests.get(self.server.screenshot_uri, timeout=10)
        if filename:
            with open(filename, 'wb') as f:
                f.write(r.content)
            return filename
        elif format == 'pillow':
            try:
                from PIL import Image
                buff = io.BytesIO(r.content)
                return Image.open(buff).convert("RGB")
            except Exception as ex:
                raise IOError("PIL.Image.open IOError", ex)
        elif format == 'opencv':
            import cv2
            import numpy as np
            nparr = np.fromstring(r.content, np.uint8)
            return cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        elif format == 'raw':
            return r.content
        else:
            raise RuntimeError("Invalid format " + format)
 

正确写法如下

    import base64
    img = base64.b64decode(self.device._default_session.jsonrpc.takeScreenshot(1.0,100).encode('ascii'))
    print(img)
    with open("abc.jpg", "wb") as f:
        f.write(img)

这么写就可以截屏了

手机小米9 系统安卓10

**Comment by runningabcd** [comment]
期待和你们一起维护这个项目

**Comment by mingyuan-xia** [comment]
直接提一个PR吧，该一下screenshot这个函数实现，谢谢

**Comment by index9-44** [comment]
img = base64.b64decode(self.device._default_session.jsonrpc.takeScreenshot(1.0, 100).encode('ascii'))
AttributeError: 'APITest' object has no attribute 'device'
大佬第一句话报错，这个怎么解决呢

**Comment by codeskyblue** [comment]
@runningabcd  我还是不知道发生了什么问题，你能执行下这个命令 `d.screenshot(format='raw') `看看输出不

**Comment by a6a18** [comment]
@codeskyblue 我在最近發售的小米電視(android 9)上使用screenshot也遇到同樣的問題，但是使用adb shell screencap卻能抓出來圖片。

這台：https://m.buy.mi.com/tw/item/3203600038?viewId=fb078c6458d5d642ffe3a22679a8ee81+8_1_4_1_4_0_omega_3203600038&pageId=newproducts

d.screenshot(format='raw')的輸出結果：https://mega.nz/file/m9BXQCyA#0GOF4yi8FAtc4TDykr7QH410WIXdQgdpymfOTbidiak

**Comment by lihujun101** [comment]
错误确实还在，最新的版本，还在，希望联系楼主指导一下

**Comment by deviler520** [comment]
我也遇到过，重新装了atx好用了
$ adb push atx-agent /data/local/tmp
$ adb shell chmod 755 /data/local/tmp/atx-agent
# launch atx-agent in daemon mode
$ adb shell /data/local/tmp/atx-agent server -d
