### ISSUE TITLE
app_install无法返回包名

### ISSUE THREAD

**Issue by c0rpse** [openatx/uiautomator2#529]
- Google Pixel2
- uiautomator2.5.7

![image](https://user-images.githubusercontent.com/16606443/76379781-080f1980-638c-11ea-9107-2eede262e406.png)
返回的包名是None，手机安装apk成功。

**Comment by zangtian2** [comment]
+1 我也遇到了，是否需要回滚版本才行
- Name: uiautomator2
- Version: 2.6.0

**Comment by mingyuan-xia** [comment]
并没有说返回值是pkg，要获取自己事先获取
