### ISSUE TITLE
atx-agent recover failed

### ISSUE THREAD

**Issue by zhaoboy9692** [openatx/uiautomator2#531]
![image](https://user-images.githubusercontent.com/35800413/77156677-ca706600-6ada-11ea-97ee-173ff37a106b.png)

- 小米4 安卓6.0 miui10.8.9
- uiautomator2的版本号(`pip show uiautomator2`)
![image](https://user-images.githubusercontent.com/35800413/77156728-ed9b1580-6ada-11ea-8a52-57d64195165c.png)

经常发生该问题
顺便问一下，输入回车是什么？

**Comment by mingyuan-xia** [comment]
mi4太老，兼容性有问题
