### ISSUE TITLE
set_text的BUG

### ISSUE THREAD

**Issue by 503520985** [openatx/uiautomator2#534]
在找到控件之后对EditText的内容进行操作，得到的结果和预想中的不一样

- 手机型号honor4x 
- uiautomator2的版本号 2.6.0

问题如下：

EditText.set_text('123')  # EditText 里面显示是 123
EditText.set_text('45')  # EditText 里面显示是 453
EditText.clear_text()  # EditText 没有清除，里面显示是 453,，光标移动到最前面
EditText.set_text('6789')  # EditText 里面显示是 456789
EditText.clear_text() # EditText 可以清除

**Comment by codeskyblue** [comment]
先点击，再用 d.send_keys("123") 试试呢
