### ISSUE TITLE
图片对比完全一团糟

### ISSUE THREAD

**Issue by XDSwang** [openatx/uiautomator2#537]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by XDSwang** [comment]
我尝试了截图然后在电脑上剪辑，明明颜色值很明显不同却达到了0.9

**Comment by codeskyblue** [comment]
截个图瞅瞅

**Comment by XDSwang** [comment]
![Snipaste_2020-04-13_18-56-47](https://user-images.githubusercontent.com/39626582/79115915-b4905100-7db9-11ea-87d9-0dcb5248be08.png)
在双方黑白图还是有效果的，如果有一方或双方是多颜色完全就是一团糟

**Comment by jinjie666** [comment]
代码默认去除了rgb通道，使用的是灰度图对比，所以颜色都丢，可以改成rgb=Ture试下
find_all_template(self, im_source, im_search, threshold=template_threshold, maxcnt=0, rgb=False,
                          bgremove=False):

            s_gray = cv2.cvtColor(im_search, cv2.COLOR_BGR2GRAY)
            i_gray = cv2.cvtColor(im_source, cv2.COLOR_BGR2GRAY)

**Comment by liucong233** [comment]
> 代码默认去除了rgb通道，使用的是灰度图对比，所以颜色都丢，可以改成rgb=Ture试下
> find_all_template(self, im_source, im_search, threshold=template_threshold, maxcnt=0, rgb=False,
> bgremove=False):
> 
> ```
>         s_gray = cv2.cvtColor(im_search, cv2.COLOR_BGR2GRAY)
>         i_gray = cv2.cvtColor(im_source, cv2.COLOR_BGR2GRAY)
> ```

请问find_all_template函数在哪个文件下，没有找到
