### ISSUE TITLE
我需要 AccessibilityEvent events，有？

### ISSUE THREAD

**Issue by XDSwang** [openatx/uiautomator2#541]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by mingyuan-xia** [comment]
请务必提供详细的信息，能够复现你的问题，否则很难帮你解决

**Comment by XDSwang** [comment]
@mingyuan-xia 

> 请一流提供详细的信息，能够复现你的问题，否则很难帮你解决

我需要监控手机界面状态发生变化
