### ISSUE TITLE
minicap使用问题

### ISSUE THREAD

**Issue by Anry-Hu** [openatx/uiautomator2#542]
- 手机型号：OPPO R9M
- uiautomator2的版本号(`pip show uiautomator2`)：2.7.3

我想使用minicap的功能，于是写了如下代码：
```python
import asyncio
import websockets


async def hello():
    uri = "ws://127.0.0.1:7912/minicap"
    async with websockets.connect(uri) as websocket:
        for i in range(10):
            greeting = await websocket.recv()
            print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(hello())
```

结果如图所示。
![image](https://user-images.githubusercontent.com/28347656/80299232-6e79bb00-87c5-11ea-8c9d-b52368e8474d.png)

请问这个问题如何解决？

**Comment by mingyuan-xia** [comment]
你要给minicap发指令啊，否则他response 什么
