### ISSUE TITLE
uiautomator2根据元素的坐标截图方法怎么调用？

### ISSUE THREAD

**Issue by 102244653** [openatx/uiautomator2#543]
在测试中需要做按钮图片的对比，但是使用元素去截图报错没有方法属性

ss = update_btn.screenshot()
AttributeError: 'UiObject' object has no attribute 'screenshot'

后面尝试截取全屏后根据坐标截取，发现截取位置有偏差，所以还是想知道有木有定位到元素后直接截取图片的方法

**Comment by codeskyblue** [comment]
没有screenshot这个接口，但是可以通过.info获取到矩形坐标，再截图
