### ISSUE TITLE
Can't connect to the phone

### ISSUE THREAD

**Issue by zhipingxiang** [openatx/uiautomator2#546]
adb版本：1.0.41
手机Android版本：Android 10
Python版本：3.8.2
uiautomator2版本：2.7.3

问题：
1. 运行“python -m uiautomator2 init”
2. 脚本执行到check_atx_agent_version时失败，错误log如下：
```
> [D 200507 16:10:10 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:11 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:11 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:12 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:12 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:13 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:13 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:14 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:14 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> [D 200507 16:10:15 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
>     response.begin()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
>     retries = retries.increment(
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
>     raise value.with_traceback(tb)
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
>     httplib_response = self._make_request(
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
>     httplib_response = conn.getresponse()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
>     response.begin()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 303, in begin
>     version, status, reason = self._read_status()
>   File "D:\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by ZakAnun** [comment]
<details>
<summary>展开查看</summary>
<pre><code>
> adb版本：1.0.41 手机Android版本：Android 10 Python版本：3.8.2 uiautomator2版本：2.7.3
> 
> 问题：
> 
> 1. 运行“python -m uiautomator2 init”
> 2. 脚本执行到check_atx_agent_version时失败，错误log如下：
> 
> ```
> > [D 200507 16:10:10 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:11 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:11 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:12 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:12 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:13 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:13 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:14 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:14 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > [D 200507 16:10:15 init:383] Forward: local:tcp:55640 -> remote:tcp:7912
> > Traceback (most recent call last):
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
> >     httplib_response = self._make_request(
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
> >     six.raise_from(e, None)
> >   File "<string>", line 3, in raise_from
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
> >     httplib_response = conn.getresponse()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
> >     response.begin()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 303, in begin
> >     version, status, reason = self._read_status()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
> >     raise RemoteDisconnected("Remote end closed connection without"
> > http.client.RemoteDisconnected: Remote end closed connection without response
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "D:\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
> >     resp = conn.urlopen(
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
> >     retries = retries.increment(
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 403, in increment
> >     raise six.reraise(type(error), error, _stacktrace)
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
> >     raise value.with_traceback(tb)
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
> >     httplib_response = self._make_request(
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
> >     six.raise_from(e, None)
> >   File "<string>", line 3, in raise_from
> >   File "D:\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
> >     httplib_response = conn.getresponse()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
> >     response.begin()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 303, in begin
> >     version, status, reason = self._read_status()
> >   File "D:\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
> >     raise RemoteDisconnected("Remote end closed connection without"
> > urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> ```
</code></pre>
</details>

请问有运行成功吗？我也遇到了这个日志。
