### ISSUE TITLE
运行python3 -m uiautomator2 init直接报错

### ISSUE THREAD

**Issue by hutcwp** [openatx/uiautomator2#552]
问题描述： 
oppo r7s（5.1.1） 运行python3 -m uiautomator2 init直接报错

- 手机型号 oppo r7s

[I 200601 21:37:54 init:155] uiautomator2 version: 2.7.3 [I 200601 21:37:54 init:348] Install minicap, minitouch [W 200601 21:37:55 api:40] 404 Client Error: Not Found for url: https://github.com/openatx/stf-binaries/raw/0.2.2/node_modules/minitouch-prebuilt-beta/prebuilt/WARNING:%20linker:%20libdtf.so:%20unused%20DT%20entry:%20type%200x6ffffffe%20arg%200x44f0%0D%0AWARNING:%20linker:%20libdtf.so:%20unused%20DT%20entry:%20type%200x6fffffff%20arg%200x3%0D%0AWARNING:%20linker:%20libdtf.so:%20unused%20DT%20entry:%20type%200x6ffffffe%20arg%200x44f0%0D%0AWARNING:%20linker:%20libdtf.so:%20unused%20DT%20entry:%20type%200x6fffffff%20arg%200x3%0D%0Aarm64-v8a/bin/minitouch, retrying in 0 seconds...

==============================
问题原因：这台手机获取的运行部分adb命令时会带上warning日志，获取minicap url出错，导致去下载minicap的库时出现找不到地址的问题。不知道有啥好的解决办法没？

如下运行 “adb shell dumpsys window displays ”
WARNING: linker: libdtf.so: unused DT entry: type 0x6ffffffe arg 0x44f0
WARNING: linker: libdtf.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libdtf.so: unused DT entry: type 0x6ffffffe arg 0x44f0
WARNING: linker: libdtf.so: unused DT entry: type 0x6fffffff arg 0x3
WINDOW MANAGER DISPLAY CONTENTS (dumpsys window displays)
  Display: mDisplayId=0
    init=1080x1920 480dpi cur=1080x1920 app=1080x1800 rng=1080x1005-1800x1725
省略

**Comment by mingyuan-xia** [comment]
更新uiautomator2 已经2.9+了
