### ISSUE TITLE
How to click multiple objects at the same time?

### ISSUE THREAD

**Issue by revxnth** [openatx/uiautomator2#556]
i have 10 check boxed, but according to my code it clicks each check box one by one, is there any way to click all the check boxes displayed at the same time? (it's possible by hand so i thought it might be possible by code

**Comment by thlengane** [comment]
Use multiprocessing or threads. 

multiprocessing works best, threads might have a very slight delay.

**Comment by mingyuan-xia** [comment]
multiprocessing should be good enough. Not precisely simultaneously but  quick close. A human cannot generate that interaction in reality.
