### ISSUE TITLE
能不能一次获取  可滚动页面  的全部内容呢？

### ISSUE THREAD

**Issue by Gaoyongxian666** [openatx/uiautomator2#56]
想做个爬虫呢，像获取整篇文章，遍历列表元素等，不太好操作

因为有的视图，很长，我们必须滚动才可以获取某些元素，但这样很麻烦的，能不能做成那种像网页源代码那种，一次性获取所有元素，我想，既然selenium 都可以做出爬虫，这个也可以

我想到的解决办法，不知道能不能实现
这个项目是基于截图，可以滚动截图获取整个页面，然后再处理
或者修改配置文件，让安卓手机里面的内容缩放，变小，让它足以容下所有的内容

**Comment by codeskyblue** [comment]
据说有全屏截图的软件

**Comment by 5368** [comment]
对于你的需要的，我有类似的经验．
做个mitmproxy代理,
一个线程控制手机打开app和相关页面
一个线程启动mitmproxy,获取并过滤app请求的加密url．
一个线程做爬虫把过滤出的url,扒下来
