### ISSUE TITLE
uiautomator2 atx-agent 总是报错 

### ISSUE THREAD

**Issue by Hello-Linux** [openatx/uiautomator2#563]
File "F:\python_project\douyin\venv\lib\site-packages\uiautomator2\__init__.py", line 1867, in connect_wifi
    raise ConnectError("addr is invalid or atx-agent is not running", addr)
uiautomator2.exceptions.ConnectError: ('addr is invalid or atx-agent is not running', '192.168.199.129')

wifi连接总是报这个错误，是因为什么呢？我看了看apk里面的agent是运行着呢为啥说是not running

**Comment by mingyuan-xia** [comment]
从电脑上访问 192.168.199.129:7912，确保没有网络问题，如果网络不是同一个交换机也不行

**Comment by Hello-Linux** [comment]
@mingyuan-xia  192.168.199.129:7912是可以访问的，因为我的２个手机都是连接的同一个无线路由器．我感觉我的网络没有问题，就是不知道为啥会说addr is invalid or atx-agent is not running', '192.168.199.129

**Comment by ASheaJin** [comment]
你电脑可能设置代理了，要把代理去掉，或者设置你这个ip192.168.199.129不使用代理

**Comment by YongShing** [comment]
有一样的问题，连啥网都不好使，总是报这个错，难搞定

**Comment by YongShing** [comment]
这边查了下，wifi连接，需要设备的android版本是android 11及以上版本；低于这个版本会报错
