### ISSUE TITLE
python3.7 安装 uiautomator2 报错

### ISSUE THREAD

**Issue by king1348** [openatx/uiautomator2#580]
使用 win7 和 win10 python3.7 安装 uiautomator2 时，提示报错：
 Command "python setup.py egg_info" failed with error code 1 in C:\Users\a\AppData\Local\Temp\pip-install-qpjsk294\uiautomator2\
后来升级了 pip 后，还是提示安装失败。
麻烦大佬 指点下。谢谢

**Comment by mingyuan-xia** [comment]
具体error呢
