### ISSUE TITLE
逍遥模拟器无法启动ATX-agent的问题

### ISSUE THREAD

**Issue by jantionMH** [openatx/uiautomator2#582]
- 手机型号  ：逍遥模拟器
- uiautomator2的版本号2.11.1
- 截图
点击ATX之后
点击启动uiautomator

提示：
uiautomator not starting

而且一直启动不了，卸载重装都不行

**Comment by JunGaJang** [comment]
我用的逍遥，没有任何问题，U2版本是2.11.4
