### ISSUE TITLE
在部分低端机型，app底部tab的text无法获取到

### ISSUE THREAD

**Issue by ssfanli** [openatx/uiautomator2#583]
# 现象

和#362 类似，但是目前我这的现象是：

1. 相同的待测app，在部分低端机上，底部tab的text无法定位到，如下图所示
2. 全面屏手机需打开虚拟键才可以定位底部tab的text

### vivo x9 / 安卓7.1.2

无法定位`首页`
![image](https://user-images.githubusercontent.com/53210634/90752092-8ee7fb00-e309-11ea-8b96-a902ae921726.png)

### 华为mate9pro / 安卓9.0

可以定位`首页`
![image](https://user-images.githubusercontent.com/53210634/90752809-6dd3da00-e30a-11ea-8480-26cff724ff33.png)

# 问题机型

vivo x9 / 安卓7.1.2
vivo y66 / 安卓6.0

# 版本

uiautomator2 version: 2.11.1

**Comment by ShawnXW** [comment]
遇到相同问题了，应该是displayheight 取错了，我的应该是2600左右，xml文件里是2510，weditor也是。你解决了吗？

**Comment by ssfanli** [comment]
目前还没解决

**Comment by ssfanli** [comment]
> 遇到相同问题了，应该是displayheight 取错了，我的应该是2600左右，xml文件里是2510，weditor也是。你解决了吗？

没有
