### ISSUE TITLE
初始化uiautomator2出permisoon denied

### ISSUE THREAD

**Issue by MrGuoRanDuo** [openatx/uiautomator2#588]
管理员cd到venv下直接init还是无效 pycharm终端init无效 查了好多办法都没有用 和公司内网的各种奇怪的文件权限有关吗

- 手机型号 mumu模拟器
- uiautomator2的版本号  2.11.3   python3.7.3
- 手机截图  无
- 相关日志
![IMG20200916_150011](https://user-images.githubusercontent.com/57265425/93303073-8235c480-f82d-11ea-8e3e-f9544e414d13.png)

**Comment by mingyuan-xia** [comment]
`venv/bin/python3 xxx`
