### ISSUE TITLE
uiautomator2-2.7.0，toast布局包含ImageView和TextView，toast.get_message方法只返回了ImageView的contentDescription

### ISSUE THREAD

**Issue by YeKelvin** [openatx/uiautomator2#590]
Toast布局包含ImageView和TextView，toast.get_message方法只返回了ImageView的contentDescription，无法返回toast里TextView的内容

- 手机型号
OPPO Reno2 F

- uiautomator2的版本号(`pip show uiautomator2`)
2.7.0

- 手机截图
![image](https://user-images.githubusercontent.com/16164014/93568643-0a999e00-f9c3-11ea-8045-2cf6448ea3e8.png)

**Comment by codeskyblue** [comment]
无法复现了，后面再说吧。
