### ISSUE TITLE
全面屏手机DisplayHeight取值偏小，底部区域控件Bounds错误

### ISSUE THREAD

**Issue by ShawnXW** [openatx/uiautomator2#595]
手机底部控件Bounds的不正确，如抖音底部'首页'的height只有13，应该是displayheight 取错了，我的应该是2600左右，xml文件里是2510，weditor也是。
用eclipse看是正常的，问题与#362 #583 类似

版本2.11.4

**Comment by codeskyblue** [comment]
close for duplicated
