### ISSUE TITLE
How can I deploy it on cloud or on mobile itself.

### ISSUE THREAD

**Issue by ishandutta2007** [openatx/uiautomator2#597]
Currently to run test I am connecting to my PC every time. I would like to deploy the libraries and corresponding android sdk tools on any cloud server, so that I can trigger/schedule tests on mobile from there. Alternatively if its possible to deploy the bits on mobile and run from there thats also fine.

**Comment by mingyuan-xia** [comment]
not the concern of this automation lib

**Comment by tayhoney82** [comment]
> not the concern of this automation lib

sure, this is not an issue of the lib, I didn't mean it wither. I am just wanting for some suggestions on how to trigger the test on device from remote server.
Would be happy to connect with you on some other platform if you feel this thread is not the right place to discuss it.

**Comment by ishandutta2007** [comment]
sure, this is not an issue of `uiautomator2` lib, I didn't mean it either. I am just wanting for some suggestions on how to trigger the test on device from remote server.
Would be happy to connect with you on some other platform if you feel this thread is not the right place to discuss it.
