### ISSUE TITLE
长时间运行后,出现 http-request to atx-agent error, can only recover from USB

### ISSUE THREAD

**Issue by alexlipe** [openatx/uiautomator2#600]
- 小米 note 4x,  红米5p
- uiautomator2的版本号 2.11.3
长时间运行后, 不定期的会出现 http-request to atx-agent error, can only recover from USB 这个提示. 应该怎么处理? 继续重试操作? 还是应该连上usb后,重新进行init 操作?

**Comment by qugo9955** [comment]
我也遇到这个问题  OPPO R9s
OPPO R9s - ERROR - Exception, http-request to atx-agent error, can only recover from USB

**Comment by yangeren** [comment]
同出现此问题，长时间运行后，而且不会自己断开，会在线程里一直提示。但手机确实是连着USB的。
![image](https://user-images.githubusercontent.com/3181945/100299115-d13a6b80-2fcd-11eb-920f-017749b2dc48.png)
