### ISSUE TITLE
Flutter混合页面层级错位，造成click点击位置不准确

### ISSUE THREAD

**Issue by Jason20188** [openatx/uiautomator2#608]
- 手机型号 红米note8
- uiautomator2的版本号 2.12.0
- 手机截图
![image](https://user-images.githubusercontent.com/37041288/97573324-87895000-1a24-11eb-9702-ac18df038b6e.png)

**Comment by jantionMH** [comment]
遇到过相同问题，仅供参考
当时weditor 无法使用，于是我使用了uiautomatorview 进行页面元素获取
市场上有几个uiautomatorview版本，都可以用

**Comment by codeskyblue** [comment]
现在应该没了，先关掉了
