### ISSUE TITLE
dump_hierarchy可能不包含text, content-desc有中文字符的控件

### ISSUE THREAD

**Issue by reporter-law** [openatx/uiautomator2#609]
<node index="3" text="" resource-id="" class="android.widget.FrameLayout" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,895][283,1180]">
                        <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,895][283,1180]">
                          <node index="0" text="" resource-id="" class="android.widget.ImageView" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,895][283,1180]" />
                          <node index="1" text="" resource-id="" class="android.widget.ImageView" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,895][283,1180]" />
                        </node>
                        <node index="1" text="" resource-id="" class="android.widget.ImageView" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,895][283,1180]" />
                        <node index="2" text="全场免息" resource-id="" class="android.widget.TextView" package="com.taobao.taobao" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[24,1089][283,1137]" />

text、content-desc这些标签有时候会有中文存在，但是有时候又没有，怎么让输出的xml中文标签都有

**Comment by jantionMH** [comment]
不知道你在说什么，描述都不清楚，还想解决问题

**Comment by reporter-law** [comment]
通过xpath进行元素定位，如d.xpath("转到上一层级").click()需要知道元素的内容"转到上一层级"，但是通过d.dump_hierarchy()输出的xml文档中有时会没有这一内容的存在

**Comment by mingyuan-xia** [comment]
`d.xpath("转到上一层级")` 这不是一个合法的xpath
`但是通过d.dump_hierarchy()输出的xml文档中有时会没有这一内容的存在` 给例子

**Comment by reporter-law** [comment]
![淘宝](https://user-images.githubusercontent.com/61373015/102615280-99f45000-4170-11eb-8fd7-7779888bb943.jpg)
输出的xml搜索不到
![image](https://user-images.githubusercontent.com/61373015/102615335-b1333d80-4170-11eb-80c1-5e1575c58b24.png)


xml的全部输出
