### ISSUE TITLE
u2.connect时报错？

### ISSUE THREAD

**Issue by hongjojjay** [openatx/uiautomator2#614]
- 手机型号 
我们内部的android项目，android 8.0

- uiautomator2的版本号
2.12.0

- 测试代码
import uiautomator2 as u2
if __name__ == "__main__":
    d = u2.connect("fe80a8aa")
    print(d.info)

- 相关日志
[D 201106 15:07:42 __init__:600] kill process(ps): uiautomator
[D 201106 15:07:44 init:62] Download https://tool.appetizer.io/openatx/android-uiautomator-server/releases/download/2.3.1/app-uiautomator.apk
[D 201106 15:07:46 __init__:348] pm install /data/local/tmp/app-uiautomator.apk
[D 201106 15:07:50 init:62] Download https://tool.appetizer.io/openatx/android-uiautomator-server/releases/download/2.3.1/app-uiautomator-test.apk
[D 201106 15:07:50 __init__:348] pm install /data/local/tmp/app-uiautomator-test.apk
[D 201106 15:07:54 __init__:619] uiautomator-v2 is starting ... left: 40.0s
[D 201106 15:07:55 __init__:619] uiautomator-v2 is starting ... left: 39.0s
[D 201106 15:07:56 __init__:619] uiautomator-v2 is starting ... left: 37.9s
[D 201106 15:07:57 __init__:619] uiautomator-v2 is starting ... left: 36.9s
[D 201106 15:07:58 __init__:619] uiautomator-v2 is starting ... left: 35.8s
[D 201106 15:07:59 __init__:619] uiautomator-v2 is starting ... left: 34.8s
[D 201106 15:08:00 __init__:619] uiautomator-v2 is starting ... left: 33.8s
[D 201106 15:08:01 __init__:619] uiautomator-v2 is starting ... left: 32.7s
[D 201106 15:08:03 __init__:619] uiautomator-v2 is starting ... left: 31.7s
[D 201106 15:08:04 __init__:619] uiautomator-v2 is starting ... left: 30.7s
[D 201106 15:08:05 __init__:619] uiautomator-v2 is starting ... left: 29.6s
[D 201106 15:08:06 __init__:619] uiautomator-v2 is starting ... left: 28.6s
[D 201106 15:08:07 __init__:619] uiautomator-v2 is starting ... left: 27.5s
[D 201106 15:08:08 __init__:619] uiautomator-v2 is starting ... left: 26.5s
[D 201106 15:08:09 __init__:619] uiautomator-v2 is starting ... left: 25.5s
[D 201106 15:08:10 __init__:619] uiautomator-v2 is starting ... left: 24.5s
[D 201106 15:08:11 __init__:619] uiautomator-v2 is starting ... left: 23.4s
[D 201106 15:08:12 __init__:619] uiautomator-v2 is starting ... left: 22.4s
[D 201106 15:08:13 __init__:619] uiautomator-v2 is starting ... left: 21.3s
[D 201106 15:08:14 __init__:619] uiautomator-v2 is starting ... left: 20.3s
[D 201106 15:08:15 __init__:619] uiautomator-v2 is starting ... left: 19.3s
[D 201106 15:08:16 __init__:619] uiautomator-v2 is starting ... left: 18.2s
[D 201106 15:08:17 __init__:619] uiautomator-v2 is starting ... left: 17.2s
[D 201106 15:08:18 __init__:619] uiautomator-v2 is starting ... left: 16.1s
[D 201106 15:08:21 __init__:619] uiautomator-v2 is starting ... left: 13.1s
[D 201106 15:08:23 __init__:619] uiautomator-v2 is starting ... left: 11.1s
[D 201106 15:08:24 __init__:619] uiautomator-v2 is starting ... left: 10.0s
[D 201106 15:08:25 __init__:619] uiautomator-v2 is starting ... left: 9.0s
[D 201106 15:08:26 __init__:619] uiautomator-v2 is starting ... left: 7.9s
[D 201106 15:08:27 __init__:619] uiautomator-v2 is starting ... left: 6.9s
[D 201106 15:08:28 __init__:619] uiautomator-v2 is starting ... left: 5.9s
[D 201106 15:08:29 __init__:619] uiautomator-v2 is starting ... left: 4.8s
[D 201106 15:08:30 __init__:619] uiautomator-v2 is starting ... left: 3.8s
[D 201106 15:08:31 __init__:619] uiautomator-v2 is starting ... left: 2.7s
[D 201106 15:08:33 __init__:619] uiautomator-v2 is starting ... left: 1.7s
[D 201106 15:08:34 __init__:619] uiautomator-v2 is starting ... left: 0.6s
[I 201106 15:08:38 __init__:572] restart-uiautomator since "uiautomator2.GatewayError(gateway error, time used 0.0s)"
[D 201106 15:08:38 __init__:600] kill process(ps): uiautomator
[D 201106 15:08:39 __init__:654] grant permissions
[D 201106 15:08:42 __init__:619] uiautomator-v2 is starting ... left: 40.0s
[D 201106 15:08:43 __init__:619] uiautomator-v2 is starting ... left: 38.9s
[D 201106 15:08:44 __init__:619] uiautomator-v2 is starting ... left: 37.9s
[D 201106 15:08:45 __init__:619] uiautomator-v2 is starting ... left: 36.8s
[D 201106 15:08:46 __init__:619] uiautomator-v2 is starting ... left: 35.8s
[D 201106 15:08:47 __init__:619] uiautomator-v2 is starting ... left: 34.8s
[D 201106 15:08:48 __init__:619] uiautomator-v2 is starting ... left: 33.7s
[D 201106 15:08:49 __init__:619] uiautomator-v2 is starting ... left: 32.7s
[D 201106 15:08:50 __init__:619] uiautomator-v2 is starting ... left: 31.6s
[D 201106 15:08:51 __init__:619] uiautomator-v2 is starting ... left: 30.6s
[D 201106 15:08:52 __init__:619] uiautomator-v2 is starting ... left: 29.6s
[D 201106 15:08:53 __init__:619] uiautomator-v2 is starting ... left: 28.6s
[D 201106 15:08:54 __init__:619] uiautomator-v2 is starting ... left: 27.6s
[D 201106 15:08:55 __init__:619] uiautomator-v2 is starting ... left: 26.5s
[D 201106 15:08:56 __init__:619] uiautomator-v2 is starting ... left: 25.5s
[D 201106 15:08:57 __init__:619] uiautomator-v2 is starting ... left: 24.4s
[D 201106 15:08:58 __init__:619] uiautomator-v2 is starting ... left: 23.4s
[D 201106 15:08:59 __init__:619] uiautomator-v2 is starting ... left: 22.4s
[D 201106 15:09:00 __init__:619] uiautomator-v2 is starting ... left: 21.3s
[D 201106 15:09:01 __init__:619] uiautomator-v2 is starting ... left: 20.3s
[D 201106 15:09:02 __init__:619] uiautomator-v2 is starting ... left: 19.3s
[D 201106 15:09:03 __init__:619] uiautomator-v2 is starting ... left: 18.3s
[D 201106 15:09:05 __init__:619] uiautomator-v2 is starting ... left: 17.2s
[D 201106 15:09:06 __init__:619] uiautomator-v2 is starting ... left: 16.2s
[D 201106 15:09:07 __init__:619] uiautomator-v2 is starting ... left: 15.2s
[D 201106 15:09:10 __init__:619] uiautomator-v2 is starting ... left: 12.1s
[D 201106 15:09:12 __init__:619] uiautomator-v2 is starting ... left: 10.1s
[D 201106 15:09:13 __init__:619] uiautomator-v2 is starting ... left: 9.0s
[D 201106 15:09:14 __init__:619] uiautomator-v2 is starting ... left: 8.0s
[D 201106 15:09:15 __init__:619] uiautomator-v2 is starting ... left: 7.0s
[D 201106 15:09:16 __init__:619] uiautomator-v2 is starting ... left: 5.9s
[D 201106 15:09:17 __init__:619] uiautomator-v2 is starting ... left: 4.9s
[D 201106 15:09:18 __init__:619] uiautomator-v2 is starting ... left: 3.9s
[D 201106 15:09:19 __init__:619] uiautomator-v2 is starting ... left: 2.8s
[D 201106 15:09:20 __init__:619] uiautomator-v2 is starting ... left: 1.8s
[D 201106 15:09:21 __init__:619] uiautomator-v2 is starting ... left: 0.8s
Traceback (most recent call last):
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 479, in _jsonrpc_call
    (time.time() - request_start))
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/JZPython/untitled/uiautomator2test.py", line 9, in <module>
    print(d.info)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 404, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 436, in __call__
    http_timeout)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 446, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 591, in reset_uiautomator
    depth=depth + 1)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 591, in reset_uiautomator
    depth=depth + 1)
  File "D:\zst\androidtenvenv\lib\site-packages\uiautomator2\__init__.py", line 568, in reset_uiautomator
    "adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner",
OSError: [WinError adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner] uiautomator2.GatewayError(gateway error, time used 0.0s): 'https://github.com/openatx/uiautomator2/wiki/Common-issues'

Process finished with exit code 1

**Comment by mingyuan-xia** [comment]
logcat

**Comment by yazhli** [comment]
請問這個問題解決了嗎？怎麽解決的？

**Comment by codeskyblue** [comment]
看看是不是APK没装上。大概率是这个问题
