### ISSUE TITLE
device_info方法获取到的信息是出于什么原因做了一层缓存呢？

### ISSUE THREAD

**Issue by yangeren** [openatx/uiautomator2#616]
## device_info方法获取到的信息被缓存住了，无法使用此方法实时获取电池温度信息，总是只显示第一次获取到的值

- uiautomator2的版本号:Version: 2.12.0
- 操作方法：
1. 使用driver.device_info获取信息temperature字段值 ，然后使用adb shell dumpsys battery获取temperature值 
2. 操作手机 ，使用温度上升，重复第一步操作
3. 对比，device_info获取到的数据不会变化

- 相关日志
`{'acPowered': False,
 'usbPowered': True,
 'wirelessPowered': False,
 'status': 2,
 'health': 2,
 'present': True,
 'level': 72,
 'scale': 100,
 'voltage': 4085,
 'temperature': 300,
 'technology': 'Li-poly'}
`

**Comment by mingyuan-xia** [comment]
缓存是因为很多地方需要用到device_info如果每次都重新获取会有性能问题，需要刷新的地方可以直接刷新
https://github.com/openatx/uiautomator2/blob/master/uiautomator2/__init__.py#L836
