### ISSUE TITLE
Interacting with web view

### ISSUE THREAD

**Issue by stylesuxx** [openatx/uiautomator2#617]
I have problems interacting with a web view.

I can interact with my app, at some point I open a link which opens in the browser, now I want to interact with the elements within the browser, but it seems the only thing I can do is scroll the view. I have seen that there is code for werbview related functionality, but it does not seem to be implemented.

Are there any plans that this will be implemented any time soon?

**Comment by codeskyblue** [comment]
后期不打算支持了
