### ISSUE TITLE
TypeError: must be str, not int. 

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#62]
Traceback (most recent call last):
  File "E:/04_Project/Uiautomator2/testcase/InstallLogin.py", line 73, in <module>
    d(className="android.widget.LinearLayout", instance=25).click() 
  File "D:\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1193, in inner
    raise UiObjectNotFoundError({'code': -32002, 'message': E(self.selector.__str__())})
  File "D:\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1591, in __str__
    args.append(k + '=' + U(v))
TypeError: must be str, not int

 d(className="android.widget.LinearLayout", instance=25).click() 
类似这种的点击，会报错TypeError: must be str, not int
 d(className="android.widget.LinearLayout", instance=“25”).click() 
改为这种的，感觉还是很难点到的，是因为手机键盘弹出的原因么？

使用weditor，也是在点击一个输入框，弹出键盘时，页面一直处理load状态。

**Comment by codeskyblue** [comment]
已经处理过了，更新下代码 `pip install --pre -U uiautomator2`

**Comment by HeartIsBeat** [comment]
更新代码后是可以了，但是点击还是点击不到

```
11:32:53.833 $ curl -X POST -d 'b'{"jsonrpc": "2.0", "id": "55baa06a91bf520d3aa924efac6e4cb1", "method": "waitForExists", "params": [{"mask": 16777232, "childOrSibling": [], "childOrSiblingSelector": [], "className": "android.widget.LinearLayout", "instance": 25}, 20000]}'' 'http://ip:7912/session/16668:xxx/jsonrpc/0'
Traceback (most recent call last):
11:33:15.833 Response (22000 ms) >>>
  File "E:/04_Project/Uiautomator2/testcase/TestSearch2.py", line 74, in <module>
{"jsonrpc":"2.0","id":"55baa06a91bf520d3aa924efac6e4cb1","result":false}
<<< END
    d(className="android.widget.LinearLayout", instance=25).click() 
  File "D:\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1226, in inner
    raise UiObjectNotFoundError({'code': -32002, 'message': E(self.selector.__str__())})
uiautomator2.UiObjectNotFoundError: -32002 Server error: Unknown <Selector [className='android.widget.LinearLayout', instance=25]>
```
类似这种有弹出键盘的，就是点不到

**Comment by codeskyblue** [comment]
我们有自带的输入法的

**Comment by HeartIsBeat** [comment]
我们的键盘是，点击输入框自动弹出的。

d(className="android.widget.LinearLayout" 这个换了个resourceId="",instance=0 这种的就可以点击了。
