### ISSUE TITLE
只能获取桌面元素，而无法获取App界面元素

### ISSUE THREAD

**Issue by he902** [openatx/uiautomator2#620]
- 手机型号：努比亚Z17mini, 安卓6.0.1
- uiautomator2的版本号: 2.12.1.dev1

只能获取桌面元素，而无法获取App界面里的元素。不管是系统自带的App，还是新安装的App，都获取不到App界面元素。
当运行任意App界面后，只能获取到屏幕顶部状态栏里的元素（时间，信号，运营商名称等），其它桌面元素就又获取不到了（当关闭App后则可）。

d.dump_hierarchy() 也和上述现象一样。
d.info 显示 sdk 版本 23，是不是太低了？

**Comment by he902** [comment]
我从这个贴子得到提示，搞定了！
https://segmentfault.com/q/1010000013297477

settings put secure enabled_accessibility_services com.github/com.github.uiautomator

**Comment by Hedilict** [comment]
> 我从这个贴子得到提示，搞定了！
> https://segmentfault.com/q/1010000013297477
> 
> settings put secure enabled_accessibility_services com.github/com.github.uiautomator

我也遇到了相同的问题，能留下联系方式交流下么？
