### ISSUE TITLE
操作出错就报了一个 “0”

### ISSUE THREAD

**Issue by mrcaipeng** [openatx/uiautomator2#622]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
RedMi A8
- uiautomator2的版本号(`pip show uiautomator2`)
Version: 2.12.0
- 手机截图
- 相关日志

- 最好能附上可能复现问题的代码。
    view_lst = scrollable.child(className="android.widget.TextView", resourceId= resource_id)
        for item in view_lst:
            txt = item.get_text()
            current_lst.append(txt)
            if txt not in last_lst: # lst:
                lst.append(txt)
        time.sleep(0.5)
1. 在遍历控件（元素比较多，而且需要滑动屏幕）的时候，有时候会遇到错误码为 ‘0’ 没有错误信息的提示。

**Comment by mingyuan-xia** [comment]
错误信息呢？

**Comment by codeskyblue** [comment]
信息不全，暂时关闭
