### ISSUE TITLE
相对定位，使用exists判断时，不存在时报了NoneType' object has no attribute 'exists'

### ISSUE THREAD

**Issue by huanzhijin** [openatx/uiautomator2#624]
相对定位，使用exists判断时，不存在时报了NoneType' object has no attribute 'exists'，预期结果应该是返回False吧
存在时是返回正常的
![image](https://user-images.githubusercontent.com/15280640/100336057-a7566880-3010-11eb-8eb5-a653f57b17d7.png)

**Comment by arthurspa** [comment]
This is a duplicated of #621
