### ISSUE TITLE
建议将安装atx等相关依赖apk和so存储在项目

### ISSUE THREAD

**Issue by LikCodeLab** [openatx/uiautomator2#626]
在特殊第一次初始也无网情况下，项目将无法下载相关依赖apk到指定目录下
建议 将依赖apk存储在本项目中，减少第一次下载缓存。

**Comment by mingyuan-xia** [comment]
听不懂

**Comment by codeskyblue** [comment]
这个可以有，忘了处理这个问题了

**Comment by LukasCodeLab** [comment]
不一定要放在binary,可以开放一个apk相关依赖的路径方法，我觉得应该让这些apk随着项目走，而不是固定的位置，比如c/agent

**Comment by CallmeLins** [comment]
> 

这个新的feature现在实现了吗，测试的时候频繁刷机重新下载，国内的网络下载太慢了

**Comment by codeskyblue** [comment]
已经全部离线处理
