### ISSUE TITLE
在weditor上找到的控件信息使用ui2无法识别

### ISSUE THREAD

**Issue by wwzzaho** [openatx/uiautomator2#628]
手机界面内识别出来的层次有三个
第一个为手机本身的顶部状态栏
第二个为手机主界面
第三个为手机主界面上调用sdk生成的菜单栏

在测试过程中发现：
手机主界面内的信息是可以正常识别且操作的。
调用sdk生成的菜单栏、和手机顶部状态栏可以通过weditor找到控件信息、也可以通过xpath进行操作。但是使用resourceId或者text的方式时，却无法识别到。

dalao help，不知道有没有遇到同样情况的，请教怎么解决

![image](https://user-images.githubusercontent.com/24664155/102189044-07924900-3ef1-11eb-8630-5160171bd578.png)

**Comment by codeskyblue** [comment]
执行了一下，看起来还好。哎，2020年的问题啊，都4年了。
