### ISSUE TITLE
UIAutomator2: ATX-Agent 0.9.5: arch(['x86_64']) need to be supported yet, please report an issue in github

### ISSUE THREAD

**Issue by ganguachar** [openatx/uiautomator2#629]
We are having trouble installing the ATX-agent on test unit since it is not supported currently. The error flagged is as below:
"Install atx-agent 0.9.5
arch(['x86_64']) need to be supported yet, please report an issue in github"

**Comment by mingyuan-xia** [comment]
It's an emulator, and automation support is bad.
Use a real device instead

**Comment by ganguachar** [comment]
Thank you Mingyuan,

We are seeing this error with real device. Let me know if you need any information for the device. We are observing this issue only when we program the device with latest software. Earlier software we had absolutely no issue.
Appreciate your response.

Regards,
Gangu

**Comment by mingyuan-xia** [comment]
Is the device  x86-64 based ?

**Comment by ganguachar** [comment]
Hello Minguan,

Info for old Software Build :
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64,x86]
[ro.product.cpu.abilist32]: [x86]
[ro.product.cpu.abilist64]: [x86_64]
[ro.product.device]: [gminfo37]

Info for new Software Build:
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64]
[ro.product.cpu.abilist32]: []
[ro.product.cpu.abilist64]: [x86_64]
[ro.product.device]: [gminfo37]

Regards
Gangu

**Comment by ganguachar** [comment]
Hello Mingyuan,

I received information from software development team that the latest build has “recommended performance optimization - to not have 32 bit support”.

Looks like we there will be no support for 32bit apps going forward. Please let us know if you plan to support 64bit any time in future.

Appreciate your input.

Regards
Gangu

From: Gangu Virupakshappa
Sent: Monday, January 11, 2021 1:19 PM
To: 'openatx/uiautomator2' <reply@reply.github.com>; openatx/uiautomator2 <uiautomator2@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [openatx/uiautomator2] UIAutomator2: ATX-Agent 0.9.5: arch(['x86_64']) need to be supported yet, please report an issue in github (#629)

Hello Minguan,

Info for old Software Build :
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64,x86]
[ro.product.cpu.abilist32]: [x86]
[ro.product.cpu.abilist64]: [x86_64]
[ro.product.device]: [gminfo37]

Info for new Software Build:
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64]
[ro.product.cpu.abilist32]: []
[ro.product.cpu.abilist64]: [x86_64]
[ro.product.device]: [gminfo37]

Regards
Gangu

**Comment by mingyuan-xia** [comment]
I did not find the the device `gminfo37` on https://storage.googleapis.com/play_public/supported_devices.html 
The problem is not with 32bit or 64bit. x86 is the problem here.
atx-agent is not built for x86-based Android boxes. And we can not find such boxes off-the-shelf to test with.

**Comment by ganguachar** [comment]
Hello Mingyuan,

Appreciate your response.

ATX-Agent works well on the x86 builds. I have used this for almost 6 months.
We have issue with x86_64 build only.

The device we use may not be available in public for testing. However, I will try to find out which x86_64 device (from supported devices list) you can use for testing. I will get back to you on this. Thank you.

Regards
Gangu

**Comment by mingyuan-xia** [comment]
There is a amd64 build of atxagent that you can play with here: https://github.com/openatx/atx-agent/releases/tag/0.9.5

**Comment by ganguachar** [comment]
Hello Mingyuan,


We push the amd64 file using commands:

$ adb push atx-agent /data/local/tmp
$ adb shell chmod 755 /data/local/tmp/atx-agent


And then try to install with

python -m uiautomator2 init


We are getting error at

self.check_atx_agent_version()

Forward port fails


So, we installed 32-bit Agent with above method. For 32-bit agent the port forward is successful. After this we repeat for 64-bit and it seems successful.


Is there a way to check if ATX-Agent installed is 32-bit or 64-bit? What path does ATX Agent run from?


Appreciate your help.


regards

Gangu


________________________________
