### ISSUE TITLE
disable_popups not working

### ISSUE THREAD

**Issue by ishandutta2007** [openatx/uiautomator2#633]
It does nothing . Google's Autofilling popup is popping up on app launch
```
device_id="192.168.0.101:5559"
d = uiautomator2.connect(device_id)
print(d.info)
d.disable_popups()
sess = d.session("com.appname.droid.full")

```

> {'currentPackageName': 'com.hootsuite.droid.full', 'displayHeight': 1280, 'displayRotation': 0, 'displaySizeDpX': 424,  'displaySizeDpY': 753, 'displayWidth': 720, 'productName': 'P85Nxt', 'screenOn': True, 'sdkInt': 25, 'naturalOrientation': True}

**Comment by codeskyblue** [comment]
disable_popups移除了
