### ISSUE TITLE
怎么实现多点触控

### ISSUE THREAD

**Issue by hakaboom** [openatx/uiautomator2#637]
请问u2支持多点触控吗，或者怎么才能在u2里进行minitouch操作

**Comment by axinhouzilaoyue** [comment]
同问u2怎么使用多点触控，没找到Python的api

**Comment by mingyuan-xia** [comment]
device.minitouch可以直接操作minitouch

**Comment by ll906875341** [comment]
@mingyuan-xia 你好，device并没有minitouch类，只有touch类，但是touch类的down函数并不能实现多点触控，我尝试同时使用uiautomator2和minitorch，但是我失败了。请问一下可以给我提供一些思路吗，非常感谢。
