### ISSUE TITLE
请问控件的 visible-to-user 的属性是怎么获取的

### ISSUE THREAD

**Issue by KzDog** [openatx/uiautomator2#638]
我通过 adb shell uiautomator dump /data/local/tmp/tree.xml 获取的控件信息，和使用 uiautomator2 的 dump_hierarchy() 获取的控件信息相比，后者多出了一个 visible-to-user 属性，想知道该属性是怎么来的，谢谢

**Comment by mingyuan-xia** [comment]
accessibility service返回
