### ISSUE TITLE
这个报告怎么接入jenkins？

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#64]
python -u simplehttpserver.py
第一个默认11000端口，后面的端口随机。

这怎么接入jenkins，可以查看多个报告？

建议报告中加个.sh文件存放脚本“ python -u simplehttpserver.py”

**Comment by codeskyblue** [comment]
Jenkins自带文件服务器的

**Comment by HeartIsBeat** [comment]
o(╥﹏╥)o大神，不会啊
jenkins自带文件服务器怎么配置，怎么看htmlreport

我只知道有个工作空间和HTML Report的配置的方式。

**Comment by codeskyblue** [comment]
嗯嗯，你用那个HTML Report就够了

**Comment by HeartIsBeat** [comment]
那个htmlreport不是要run.bat才能打开页面么。

HTML Report都是直接指向index.html，这怎么配置？

**Comment by codeskyblue** [comment]
我们生成的报告也是index.html

**Comment by codeskyblue** [comment]
@HeartIsBeat 加油，你可以搞定的

**Comment by HeartIsBeat** [comment]
index.html本地直接双击打开不是不对嘛。

直接配到HTML Report不是跟双击打开一样嘛。

我换成了HTMLTestRunner生成报告方式了。

**Comment by codeskyblue** [comment]
双击打开的方式，不能加载本地的json，这是因为浏览器的安全限制。
但是直接配到HTML Report 可以，是因为jenkins就是一个文件服务器

**Comment by HeartIsBeat** [comment]
哇啊这样啊，灰常感谢你^_^！

**Comment by HeartIsBeat** [comment]
实践了一下，jenkins确实可以直接打开完整报告。
再次感谢，uiautomator2超级6！期待继续完善！
