### ISSUE TITLE
在手机上安装一个网络限速软件并启动后，uiautomator2会陷入无限循环重连的过程

### ISSUE THREAD

**Issue by Anry-Hu** [openatx/uiautomator2#641]
- 手机型号：红米 Note 3
- uiautomator2的版本号(`pip show uiautomator2`)：2.7.3

安装的软件：
app名称：手机网络限速软件
apk文件：http://www.2265.com/k/wangluoxiansujr/ 从这个网站下载：

- 相关日志
![捕获](https://user-images.githubusercontent.com/28347656/103625592-29be3a80-4f76-11eb-9adf-67437befead1.PNG)
代码报错显示：
[D 210105 16:43:21 __init__:868] uiautomator-v2 is starting ... left: 7.0s
[D 210105 16:43:26 __init__:868] uiautomator-v2 is starting ... left: 1.7s
[D 210105 16:43:36 __init__:774] restart-uiautomator since "UiAutomator stopped"
[D 210105 16:43:41 __init__:844] Device: Xiaomi, 1fb0141c
[D 210105 16:43:41 __init__:854] kill process(ps): uiautomator
[D 210105 16:43:44 __init__:826] grant permissions
[D 210105 16:43:46 __init__:868] uiautomator-v2 is starting ... left: 40.0s
[D 210105 16:43:48 __init__:868] uiautomator-v2 is starting ... left: 38.4s
[D 210105 16:43:51 __init__:868] uiautomator-v2 is starting ... left: 35.4s
[D 210105 16:43:57 __init__:868] uiautomator-v2 is starting ... left: 29.0s
[D 210105 16:44:00 __init__:868] uiautomator-v2 is starting ... left: 26.0s
[D 210105 16:44:03 __init__:868] uiautomator-v2 is starting ... left: 22.9s
[D 210105 16:44:06 __init__:868] uiautomator-v2 is starting ... left: 19.9s
[D 210105 16:44:09 __init__:868] uiautomator-v2 is starting ... left: 16.9s
[D 210105 16:44:17 __init__:868] uiautomator-v2 is starting ... left: 9.6s
[D 210105 16:44:20 __init__:868] uiautomator-v2 is starting ... left: 6.5s
[D 210105 16:44:23 __init__:868] uiautomator-v2 is starting ... left: 3.5s
[D 210105 16:44:26 __init__:868] uiautomator-v2 is starting ... left: 0.5s
[D 210105 16:44:41 __init__:774] restart-uiautomator since "UiAutomation not connected"
[D 210105 16:44:44 __init__:844] Device: Xiaomi, 1fb0141c
[D 210105 16:44:46 __init__:854] kill process(ps): uiautomator
[D 210105 16:44:47 __init__:868] uiautomator-v2 is starting ... left: 40.0s
[D 210105 16:44:50 __init__:868] uiautomator-v2 is starting ... left: 37.0s
[D 210105 16:44:53 __init__:868] uiautomator-v2 is starting ... left: 33.9s
[D 210105 16:44:58 __init__:868] uiautomator-v2 is starting ... left: 29.1s
[D 210105 16:45:01 __init__:868] uiautomator-v2 is starting ... left: 26.0s
[D 210105 16:45:04 __init__:868] uiautomator-v2 is starting ... left: 23.0s
[D 210105 16:45:07 __init__:868] uiautomator-v2 is starting ... left: 20.0s
[D 210105 16:45:10 __init__:868] uiautomator-v2 is starting ... left: 16.9s
[D 210105 16:45:13 __init__:868] uiautomator-v2 is starting ... left: 13.9s
[D 210105 16:45:16 __init__:868] uiautomator-v2 is starting ... left: 10.9s
[D 210105 16:45:19 __init__:868] uiautomator-v2 is starting ... left: 7.9s
[D 210105 16:45:22 __init__:868] uiautomator-v2 is starting ... left: 4.8s
[D 210105 16:45:25 __init__:868] uiautomator-v2 is starting ... left: 1.8s
[D 210105 16:45:32 __init__:774] restart-uiautomator since "UiAutomation not connected"
[D 210105 16:45:38 __init__:844] Device: Xiaomi, 1fb0141c
[D 210105 16:45:38 __init__:854] kill process(ps): uiautomator
[D 210105 16:45:39 __init__:826] grant permissions
[D 210105 16:45:42 __init__:868] uiautomator-v2 is starting ... left: 40.0s
[D 210105 16:45:46 __init__:868] uiautomator-v2 is starting ... left: 35.3s
[D 210105 16:45:49 __init__:868] uiautomator-v2 is starting ... left: 32.3s
[D 210105 16:45:52 __init__:868] uiautomator-v2 is starting ... left: 29.2s
[D 210105 16:45:56 __init__:868] uiautomator-v2 is starting ... left: 26.2s
[D 210105 16:45:59 __init__:868] uiautomator-v2 is starting ... left: 23.2s
[D 210105 16:46:02 __init__:868] uiautomator-v2 is starting ... left: 20.1s
[D 210105 16:46:08 __init__:868] uiautomator-v2 is starting ... left: 13.2s
[D 210105 16:46:12 __init__:868] uiautomator-v2 is starting ... left: 10.2s
[D 210105 16:46:20 __init__:868] uiautomator-v2 is starting ... left: 1.8s
[D 210105 16:46:40 __init__:774] restart-uiautomator since "UiAutomation not connected"
[D 210105 16:46:42 __init__:844] Device: Xiaomi, 1fb0141c
[D 210105 16:46:43 __init__:854] kill process(ps): uiautomator
手机网络限速软件开启限速后，uiautomator2会不断地执行connect

**Comment by taylortaurus** [comment]
> * 手机型号：红米 Note 3
> * uiautomator2的版本号(`pip show uiautomator2`)：2.7.3
> 
> 安装的软件：
> app名称：手机网络限速软件
> apk文件：http://www.2265.com/k/wangluoxiansujr/ 从这个网站下载：
> 
> * 相关日志
>   ![捕获](https://user-images.githubusercontent.com/28347656/103625592-29be3a80-4f76-11eb-9adf-67437befead1.PNG)
>   代码报错显示：
>   [D 210105 16:43:21 **init**:868] uiautomator-v2 is starting ... left: 7.0s
>   [D 210105 16:43:26 **init**:868] uiautomator-v2 is starting ... left: 1.7s
>   [D 210105 16:43:36 **init**:774] restart-uiautomator since "UiAutomator stopped"
>   [D 210105 16:43:41 **init**:844] Device: Xiaomi, 1fb0141c
>   [D 210105 16:43:41 **init**:854] kill process(ps): uiautomator
>   [D 210105 16:43:44 **init**:826] grant permissions
>   [D 210105 16:43:46 **init**:868] uiautomator-v2 is starting ... left: 40.0s
>   [D 210105 16:43:48 **init**:868] uiautomator-v2 is starting ... left: 38.4s
>   [D 210105 16:43:51 **init**:868] uiautomator-v2 is starting ... left: 35.4s
>   [D 210105 16:43:57 **init**:868] uiautomator-v2 is starting ... left: 29.0s
>   [D 210105 16:44:00 **init**:868] uiautomator-v2 is starting ... left: 26.0s
>   [D 210105 16:44:03 **init**:868] uiautomator-v2 is starting ... left: 22.9s
>   [D 210105 16:44:06 **init**:868] uiautomator-v2 is starting ... left: 19.9s
>   [D 210105 16:44:09 **init**:868] uiautomator-v2 is starting ... left: 16.9s
>   [D 210105 16:44:17 **init**:868] uiautomator-v2 is starting ... left: 9.6s
>   [D 210105 16:44:20 **init**:868] uiautomator-v2 is starting ... left: 6.5s
>   [D 210105 16:44:23 **init**:868] uiautomator-v2 is starting ... left: 3.5s
>   [D 210105 16:44:26 **init**:868] uiautomator-v2 is starting ... left: 0.5s
>   [D 210105 16:44:41 **init**:774] restart-uiautomator since "UiAutomation not connected"
>   [D 210105 16:44:44 **init**:844] Device: Xiaomi, 1fb0141c
>   [D 210105 16:44:46 **init**:854] kill process(ps): uiautomator
>   [D 210105 16:44:47 **init**:868] uiautomator-v2 is starting ... left: 40.0s
>   [D 210105 16:44:50 **init**:868] uiautomator-v2 is starting ... left: 37.0s
>   [D 210105 16:44:53 **init**:868] uiautomator-v2 is starting ... left: 33.9s
>   [D 210105 16:44:58 **init**:868] uiautomator-v2 is starting ... left: 29.1s
>   [D 210105 16:45:01 **init**:868] uiautomator-v2 is starting ... left: 26.0s
>   [D 210105 16:45:04 **init**:868] uiautomator-v2 is starting ... left: 23.0s
>   [D 210105 16:45:07 **init**:868] uiautomator-v2 is starting ... left: 20.0s
>   [D 210105 16:45:10 **init**:868] uiautomator-v2 is starting ... left: 16.9s
>   [D 210105 16:45:13 **init**:868] uiautomator-v2 is starting ... left: 13.9s
>   [D 210105 16:45:16 **init**:868] uiautomator-v2 is starting ... left: 10.9s
>   [D 210105 16:45:19 **init**:868] uiautomator-v2 is starting ... left: 7.9s
>   [D 210105 16:45:22 **init**:868] uiautomator-v2 is starting ... left: 4.8s
>   [D 210105 16:45:25 **init**:868] uiautomator-v2 is starting ... left: 1.8s
>   [D 210105 16:45:32 **init**:774] restart-uiautomator since "UiAutomation not connected"
>   [D 210105 16:45:38 **init**:844] Device: Xiaomi, 1fb0141c
>   [D 210105 16:45:38 **init**:854] kill process(ps): uiautomator
>   [D 210105 16:45:39 **init**:826] grant permissions
>   [D 210105 16:45:42 **init**:868] uiautomator-v2 is starting ... left: 40.0s
>   [D 210105 16:45:46 **init**:868] uiautomator-v2 is starting ... left: 35.3s
>   [D 210105 16:45:49 **init**:868] uiautomator-v2 is starting ... left: 32.3s
>   [D 210105 16:45:52 **init**:868] uiautomator-v2 is starting ... left: 29.2s
>   [D 210105 16:45:56 **init**:868] uiautomator-v2 is starting ... left: 26.2s
>   [D 210105 16:45:59 **init**:868] uiautomator-v2 is starting ... left: 23.2s
>   [D 210105 16:46:02 **init**:868] uiautomator-v2 is starting ... left: 20.1s
>   [D 210105 16:46:08 **init**:868] uiautomator-v2 is starting ... left: 13.2s
>   [D 210105 16:46:12 **init**:868] uiautomator-v2 is starting ... left: 10.2s
>   [D 210105 16:46:20 **init**:868] uiautomator-v2 is starting ... left: 1.8s
>   [D 210105 16:46:40 **init**:774] restart-uiautomator since "UiAutomation not connected"
>   [D 210105 16:46:42 **init**:844] Device: Xiaomi, 1fb0141c
>   [D 210105 16:46:43 **init**:854] kill process(ps): uiautomator
>   手机网络限速软件开启限速后，uiautomator2会不断地执行connect

弱网情况还有自动化的必要吗？

**Comment by mingyuan-xia** [comment]
不要限速u2
