### ISSUE TITLE
android 10上通过adb命令授权后台访问剪贴板

### ISSUE THREAD

**Issue by gojuukaze** [openatx/uiautomator2#642]
目前android 10无法使用getClipboard，搜了一圈发现发现有两个app( clipto，Clip Stack)是通过adb授予 SYSTEM_ALERT_WINDOW , READ_LOGS 两个权限实现的（相关讨论 https://github.com/clipto-pro/Android/issues/11 ）。

建议看看能否解决android 10访问剪贴板的问题

**Comment by codeskyblue** [comment]
已解决。升级一下就行
