### ISSUE TITLE
查找元素时报错比较多 uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError>

### ISSUE THREAD

**Issue by lookbulesky** [openatx/uiautomator2#644]
- 手机型号  'brand': 'GIONEE', 'model': 'GIONEE M7' 'version': '7.1.1' 'version': '7.1.1'  在阿里YunOs手机上也经常碰到
- uiautomator2的版本号(`pip show uiautomator2`)   Name: uiautomator2  Version: 2.12.1
- 手机截图
![image](https://user-images.githubusercontent.com/32353869/104705953-7a434e00-5755-11eb-8595-058360cdf9a9.png)

**Comment by AnyiAi** [comment]
我也遇到这个问题了，通过遍历列表可以发现有的时候可以获取到所有元素，有的时候会少几个。

**Comment by taylortaurus** [comment]
> * 手机型号  'brand': 'GIONEE', 'model': 'GIONEE M7' 'version': '7.1.1' 'version': '7.1.1'  在阿里YunOs手机上也经常碰到
> * uiautomator2的版本号(`pip show uiautomator2`)   Name: uiautomator2  Version: 2.12.1
> * 手机截图
>   ![image](https://user-images.githubusercontent.com/32353869/104705953-7a434e00-5755-11eb-8595-058360cdf9a9.png)

换个性能强一点的手机试试呢。

**Comment by taylortaurus** [comment]
> 这个Bug解决了么？

应该是没有，我偶尔还是有问题，但是不频繁了。

**Comment by DDDDanny** [comment]
> > 这个Bug解决了么？
> 
> 应该是没有，我偶尔还是有问题，但是不频繁了。

这就有点难受了呀

**Comment by DDDDanny** [comment]
> > 这个Bug解决了么？
> 
> 应该是没有，我偶尔还是有问题，但是不频繁了。

我现在是在操作数很长流程中，增加了重启U2，目前看来效果还行

**Comment by lookbulesky** [comment]
还没解决掉，请问下你是怎么样增加重启的？












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openatx/uiautomator2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openatx/uiautomator2] 查找元素时报错比较多 uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError&gt; (#644)





   
这个Bug解决了么？
  
应该是没有，我偶尔还是有问题，但是不频繁了。
  
我现在是在操作数很长流程中，增加了重启U2，目前看来效果还行

**Comment by lookbulesky** [comment]
还没有解决










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openatx/uiautomator2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openatx/uiautomator2] 查找元素时报错比较多 uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError&gt; (#644)





  
这个Bug解决了么？
  
应该是没有，我偶尔还是有问题，但是不频繁了。

**Comment by DDDDanny** [comment]
> 还没解决掉，请问下你是怎么样增加重启的？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "openatx/uiautomator2" ***@***.***&gt;; 发送时间:&nbsp;2021年5月19日(星期三) 下午5:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [openatx/uiautomator2] 查找元素时报错比较多 uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError&gt; (#644) 这个Bug解决了么？ 应该是没有，我偶尔还是有问题，但是不频繁了。 我现在是在操作数很长流程中，增加了重启U2，目前看来效果还行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是先把长流程的用例拆成多个，在用例后置调的uiautomator.stop()，因为它有守护进程，它会自启动。
现在我这里的表现还行，但我总感觉治标不治本。

**Comment by codeskyblue** [comment]
底层框架升级了一下，再试试
