### ISSUE TITLE
一加手机 OnePlus8T uiautomator2 Python 自动化ATX会停止并且重启

### ISSUE THREAD

**Issue by Louis24** [openatx/uiautomator2#649]
**手机型号**
一加8T 
OnePlus8T

**安卓version**
11

**系统版本**
Hydrogen OS 11.0.5.6KB05

**uiautomator2 version**
`pip show uiautomator2`
2.12.1

**APK version**
`print(u2.__atx_agent_version__)`
0.9.5
`print(u2.__apk_version__)`
2.3.1

### 代码
`import uiautomator2 as u2

d = u2.connect()

def main():
    for i in range(999):
        # 庆典广场
        # d.click(0.611 * h, 0.930 * w)
        # d.click(0.5 * h, 0.893 * w)

        # 转轮抽奖
        # d.click(0.462 * h, 0.555 * w)
        # d.click(0.5 * h, 0.893 * w)
        # d.click(0.5 * h, 0.893 * w)

        # 竞技币
        # d.click(1800, 600)
        # d.click(1600, 1000)

        # 竞技场宝物
        d.click(1229, 871)
        d.click(1193, 949)
        d.click(1557, 871)
        d.click(1193, 949)
        d.click(2053, 871)
        d.click(1193, 949)

        # 3v3卡牌
        # d.click(969, 959)
        # d.click(1185, 793)
        # d.click(1185, 793)
        # d.click(1185, 793)
        # d.click(1185, 793)
        # d.click(1185, 793)
        # d.click(1185, 793)

        # 宝物分解
        # for i in range(3):
        #     for j in range(4):
        #         d.click(1663 + j * 214, 363 + i * 214)
        # d.swipe(1985, 977, 1985, 365, 1)

if __name__ == '__main__':
    main()`

### 问题描述
我之前在小米手机用的好好的结果换了新1加手机后（已root），每次运行python程序都会等10几秒才能执行点击滑动操作，然后过几个循环又停止了，

**Comment by codeskyblue** [comment]
更新再试试
