### ISSUE TITLE
swipe_ext()方法有bug

### ISSUE THREAD

**Issue by ssfanli** [openatx/uiautomator2#650]
# 现象
如下这种情况，滑动区域卡片从底部弹出，此时直接调用swipe_ext(up, box=(x1, y1, x2, y2))方法有bug
![image](https://user-images.githubusercontent.com/53210634/106006441-2f7beb80-60f0-11eb-952e-800b4f7d4935.png)
源码`SwipeExt`中`center = width//2, height//2`这样取值有问题
应该是`center = lx + width//2,  ly + height//2`

## 版本
u2：2.12.1

**Comment by codeskyblue** [comment]
Thanks, fixed in 2.12.2
