### ISSUE TITLE
swipe方法，传入浮点数坐标1.0时候，出现问题

### ISSUE THREAD

**Issue by gffguo** [openatx/uiautomator2#652]
https://github.com/openatx/uiautomator2/blob/d0043e0b1ed27c28e502d770dfe06dfe1a5e5713/uiautomator2/__init__.py#L919，当我传入 0.5，0.5，0.5，1.0时候，理论是应该向下滑动屏幕，实际结果还是向上滑动屏幕，我认为是他这里判断，没有判断是1的情况，或许应该写成小于等于

**Comment by codeskyblue** [comment]
现在已经有不少代码写的像素1的时候，作为起始点，所以还不能改成 <=

**Comment by gffguo** [comment]
原来是这样啊，好的
