### ISSUE TITLE
uiautomator 无限kill 和starting

### ISSUE THREAD

**Issue by xhzth70911** [openatx/uiautomator2#654]
- 手机型号:Redmi Note 7
- uiautomator2的版本号:2.12.2
- python :3.6.5
电脑睡眠以后重新打开或者USB线拔下来再连接电脑以后，
先执行python -m uiautomator2 init，执行完毕以后
再执行
-import uiautomator2 as u2
d = u2.connect(device)
d.click(10, 20)
[D 210207 15:22:29 __init__:600] kill process(ps): uiautomator
[D 210207 15:22:30 __init__:619] uiautomator-v2 is starting ... left: 40.0s
[D 210207 15:22:31 __init__:619] uiautomator-v2 is starting ... left: 39.0s
第一次和第二次连接就会一直无限重启

**Comment by ishandutta2007** [comment]
我面临同样的问题

**Comment by mingyuan-xia** [comment]
atxagent log and logcat log
