### ISSUE TITLE
support vscode editor?

### ISSUE THREAD

**Issue by TinyZzh** [openatx/uiautomator2#662]
RT. 
has any plan support vscode editor?

**Comment by taylortaurus** [comment]
好奇怎么个支持法？现在是不行吗？

> RT.
> has any plan support vscode editor?

**Comment by TinyZzh** [comment]
for example, ui2 GUI ide just like `aritest ide`.

**Comment by taylortaurus** [comment]
pycharm不香吗？

TinyZ ***@***.***>于2021年3月22日 周一13:57写道：

**Comment by codeskyblue** [comment]
@TinyZzh https://github.com/alibaba/web-editor
