### ISSUE TITLE
对uiautomator-server做了定制化修改，如何操作？

### ISSUE THREAD

**Issue by power76** [openatx/uiautomator2#663]
我对uiautomator-server做了一些定制化的修改，增加了一些功能，同时需要修改uiautomator2的python文件来访问这些功能，请问该如何操作？

**Comment by mingyuan-xia** [comment]
1. build uiautomator-server -> 两个APK，安装，替换原来的
2. python uiautomator2 通过jsonrpc协议访问你修改的东西
