### ISSUE TITLE
python3 -m uiautomator2 init能成功，直接运行程序失败

### ISSUE THREAD

**Issue by 5368** [openatx/uiautomator2#669]
昨天用的好好的，今个程序不运行了...
手机：
{"udid":"A02YACQ9QE9MF-68:3e:34:ff:48:77-M1_E","version":"7.0","serial":"A02YACQ9QE9MF","brand":"Meizu","model":"M1 E","hwaddr":"68:3e:34:ff:48:77","sdk":24,"agentVersion":"0.9.6","display":{"width":1080,"height":1920},"battery":{"acPowered":false,"usbPowered":true,"wirelessPowered":false,"status":2,"health":2,"present":true,"level":90,"scale":100,"voltage":4300,"temperature":270,"technology":"Li-ion"},"memory":{"total":2856456,"around":"3 GB"},"cpu":{"cores":2,"hardware":"MT6755V/CM"},"arch":"","owner":null,"presenceChangedAt":"0001-01-01T00:00:00Z","usingBeganAt":"0001-01-01T00:00:00Z","product":null,"provider":null}
版本：
jet@debian:~$ python3 -m uiautomator2 version
uiautomator2 version: 2.13.2

init：
`jet@debian:~$ python3 -m uiautomator2 init
[I 210407 19:16:15 init:154] uiautomator2 version: 2.13.2
[I 210407 19:16:15 init:347] Install minicap, minitouch
[D 210407 19:16:15 init:59] Use cached assets: /home/jet/.uiautomator2/cache/minitouch-f7a806902f/minitouch
[D 210407 19:16:15 init:231] Push to /data/local/tmp/minitouch:0755
[D 210407 19:16:15 init:59] Use cached assets: /home/jet/.uiautomator2/cache/minicap.so-2d140e498d/minicap.so
[D 210407 19:16:15 init:231] Push to /data/local/tmp/minicap.so:0755
[D 210407 19:16:15 init:59] Use cached assets: /home/jet/.uiautomator2/cache/minicap-4ad740a772/minicap
[D 210407 19:16:15 init:231] Push to /data/local/tmp/minicap:0755
[D 210407 19:16:16 init:249] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2021, 4, 7, 19, 15, 56), 'last_update_time': datetime.datetime(2021, 4, 7, 19, 15, 56), 'signature': '8376b3fb'}
[D 210407 19:16:16 init:250] apk-debug-test package-info: None
[I 210407 19:16:16 init:360] Install com.github.uiautomator, com.github.uiautomator.test 2.3.1
[D 210407 19:16:16 init:161] Shell: ('pm', 'uninstall', 'com.github.uiautomator')
[D 210407 19:16:18 init:161] Shell: ('pm', 'uninstall', 'com.github.uiautomator.test')
[D 210407 19:16:19 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator.apk-81d5349503/app-uiautomator.apk
[D 210407 19:16:19 init:231] Push to /data/local/tmp/app-uiautomator.apk:0644
[D 210407 19:16:19 init:161] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator.apk')
[I 210407 19:16:24 init:331] - app-uiautomator.apk installed
[D 210407 19:16:24 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator-test.apk-a0b8958cc1/app-uiautomator-test.apk
[D 210407 19:16:24 init:231] Push to /data/local/tmp/app-uiautomator-test.apk:0644
[D 210407 19:16:25 init:161] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator-test.apk')
[I 210407 19:16:27 init:331] - app-uiautomator-test.apk installed
[D 210407 19:16:27 init:289] Real version: [0, 9, 6], Expect version: [0, 9, 6]
[D 210407 19:16:27 init:161] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 210407 19:16:28 init:372] Check atx-agent version
[D 210407 19:16:28 init:385] Forward: local:tcp:56783 -> remote:tcp:7912
[D 210407 19:16:28 init:388] atx-agent version 0.9.6
Successfully init AdbDevice(serial=A02YACQ9QE9MF)
`
`jet@debian:~$ python3 test.py 
[D 210407 19:23:48 __init__:600] kill process(ps): uiautomator
[D 210407 19:23:54 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator.apk-81d5349503/app-uiautomator.apk
[D 210407 19:23:54 __init__:348] pm install /data/local/tmp/app-uiautomator.apk
[D 210407 19:24:00 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator-test.apk-a0b8958cc1/app-uiautomator-test.apk
[D 210407 19:24:00 __init__:348] pm install /data/local/tmp/app-uiautomator-test.apk
[D 210407 19:24:02 __init__:617] uiautomator-v2 is starting ... left: 40.0s
[D 210407 19:24:03 __init__:617] uiautomator-v2 is starting ... left: 39.0s
[D 210407 19:24:04 __init__:617] uiautomator-v2 is starting ... left: 38.0s
[D 210407 19:24:05 __init__:617] uiautomator-v2 is starting ... left: 36.9s
[D 210407 19:24:06 __init__:617] uiautomator-v2 is starting ... left: 35.9s
[I 210407 19:24:07 __init__:572] restart-uiautomator since "uiautomator2.GatewayError(gateway error, time used 0.0s)"
[D 210407 19:24:07 __init__:600] kill process(ps): uiautomator
[D 210407 19:24:14 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator.apk-81d5349503/app-uiautomator.apk
[D 210407 19:24:14 __init__:348] pm install /data/local/tmp/app-uiautomator.apk
[D 210407 19:24:21 init:59] Use cached assets: /home/jet/.uiautomator2/cache/app-uiautomator-test.apk-a0b8958cc1/app-uiautomator-test.apk
[D 210407 19:24:21 __init__:348] pm install /data/local/tmp/app-uiautomator-test.apk
[D 210407 19:24:22 __init__:658] grant permissions
[D 210407 19:24:28 __init__:617] uiautomator-v2 is starting ... left: 40.0s
[D 210407 19:24:29 __init__:617] uiautomator-v2 is starting ... left: 39.0s
[D 210407 19:24:30 __init__:617] uiautomator-v2 is starting ... left: 38.0s
[D 210407 19:24:31 __init__:617] uiautomator-v2 is starting ... left: 36.9s
[D 210407 19:24:32 __init__:617] uiautomator-v2 is starting ... left: 35.9s
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 477, in _jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(d.info)
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 404, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 435, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 446, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 590, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 590, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
  File "/usr/local/lib/python3.8/dist-packages/uiautomator2/__init__.py", line 564, in reset_uiautomator
    raise EnvironmentError(
OSError: [Errno Uiautomator started failed.] uiautomator2.GatewayError(gateway error, time used 0.0s): 'https://github.com/openatx/uiautomator2/wiki/Common-issues'

`

**Comment by mingyuan-xia** [comment]
需要logcat
