### ISSUE TITLE
d.press()功能异常

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#675]
版本：2.12.3
描述：此前使用d.press()功能正常，后来更新了u2版本，功能异常了。我尝试去除server后，功能正常。查看附件图片的异常。

![123](https://user-images.githubusercontent.com/8575159/115004347-4a811f00-9ed9-11eb-9611-e943bb8c4e83.jpg)

**Comment by mingyuan-xia** [comment]
related: https://github.com/openatx/uiautomator2/issues/566
