### ISSUE TITLE
xpath  没有 child()这个方法了

### ISSUE THREAD

**Issue by lyg4795** [openatx/uiautomator2#677]
uiautomator2          2.12.0
icons=d.xpath('//android.widget.FrameLayout[3]').child()
提示没有child()和parent()这个函数
但是文档里面还有这种用法

![YDXO8V{WGMS9$9OEM0E)LMH](https://user-images.githubusercontent.com/33307906/115697181-e7d6ca00-a395-11eb-83ff-d0ca5b67267f.png)

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/commit/dfa51d66da81558c3a7d34161c05e95364b803ec
