### ISSUE TITLE
d.screenshot() 不能正确到抓取图片

### ISSUE THREAD

**Issue by ayongcydew** [openatx/uiautomator2#678]
设备的版本：
- Name: uiautomator2
Version: 2.15.0
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: six, requests, whichcraft, logzero, progress, retry, adbutils, Deprecated, Pillow, lxml, cached-property, packaging
Required-by: weditor

错误日志:
listening on http://10.25.207.182:17310
[I 210429 14:46:32 web:2239] 304 GET / (::1) 10.84ms
[I 210429 14:46:33 web:2239] 101 GET /ws/v1/python (::1) 11.77ms
[I 210429 14:46:33 shell:172] create process pid: 44246
[I 210429 14:46:33 web:2239] 304 GET /api/v1/version (::1) 2.51ms
[I 210429 14:46:34 web:2239] 200 POST /api/v1/connect (::1) 26.75ms
[I 210429 14:46:35 page:204] Serial: android:192.168.56.102:5555
[W 210429 14:46:35 api:40] [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x7fbf6f0fb8b0>, retrying in 0.5 seconds...
[W 210429 14:46:36 api:40] [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x7fbf6f6063b0>, retrying in 0.6 seconds...
[W 210429 14:46:37 api:40] [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x7fbf6f6063b0>, retrying in 0.7 seconds...
[W 210429 14:46:37 api:40] [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x7fbf6f6063b0>, retrying in 0.7999999999999999 seconds...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 874, in screenshot
    return Image.open(buff).convert("RGB")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fbf6f6063b0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/weditor/web/handlers/page.py", line 208, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/weditor/web/device.py", line 33, in screenshot
    return self._d.screenshot()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uiautomator2/__init__.py", line 880, in screenshot
    raise IOError("PIL.Image.open IOError", ex)
OSError: [Errno PIL.Image.open IOError] cannot identify image file <_io.BytesIO object at 0x7fbf6f6063b0>
[W 210429 14:46:38 web:2239] 430 GET /api/v1/devices/android%3A192.168.56.102%3A5555/screenshot (::1) 3165.18ms

Debug 过程:
在测试代码的时候，我们发现使用weditor链接模拟器的screenshot，部分页面会报错：
我用debug的代码，发现报错的页面，http请求没有获取到图片到信息，“ b‘’ ”是什么图片都没有获取到
d = u2.connect("192.168.56.102:5555")
r = d.http.get("/screenshot/0", timeout=10)
print(r.content)

python3 test.py
http://localhost:57093
b''
Process finished with exit code 0

但是使用真机做debug的时候，该页面是可以抓取到的。

https://user-images.githubusercontent.com/29299241/116518589-02172780-a903-11eb-95f0-b8a11f287b24.mov

麻烦看看具体是什么原因导致手机到atx-agent不能抓取正确到图片，谢谢！

**Comment by codeskyblue** [comment]
模拟器截图应该用的是 screencap命令接的图，你可以先用命令行测试一下
$ adb shell
$ screencap -p > p.png

**Comment by ayongcydew** [comment]
$ adb shell screencap -p /sdcard/Pictures/normal.png
$ adb shell screencap -p /sdcard/Pictures/black.png 
我贴了刚刚用screencap -p命令的截图，正常页面的截图是ok的。但是另一个页面大小为0k。
<img width="490" alt="Screen Shot 2021-04-29 at 11 15 20 PM" src="https://user-images.githubusercontent.com/29299241/116575227-095d2600-a941-11eb-9cd2-2bdaa8d8b155.png">

**Comment by codeskyblue** [comment]
感觉也有可能是这个界面禁止截图。（抱歉issue回复的这么慢）

**Comment by mingyuan-xia** [comment]
你可以试试0kb页面是否能uiautomator dump XML，如果不行，说明是App主动禁止该界面的截图。已知系统有些界面是禁止截图，比如锁屏解锁界面，一些App的支付界面（通过设置Window的一个flag）
