### ISSUE TITLE
指定元素ID进行长按无效

### ISSUE THREAD

**Issue by ancining** [openatx/uiautomator2#68]
如果我使用d(resourceId='XXXX').long_click()进行长按的话效果是点击，并没有长按，但使用坐标（屏幕百分比）d.long_click(0.558,0.478)进行长按的话是有效的

**Comment by codeskyblue** [comment]
新给long_click增加了一个duration参数

试试这种方法
```python
d(resourceId="XXX").long_click(2.0) # 3 seconds
```
