### ISSUE TITLE
d.screenshot() 横屏截图问题

### ISSUE THREAD

**Issue by xiaqinga** [openatx/uiautomator2#680]
您好手机横屏截图的话、出来的图是竖的 而且只有1半显示、有啥处理方法吗

**Comment by jiajia172000** [comment]
我也遇到同样的问题，截屏时如果是横屏显示，只会截取左半部分，并且截取的图片下半部分是黑的。但是如果安装旧版本，截图会是调用adb截图，图片正常，就是很慢。

**Comment by jiajia172000** [comment]
暂时找到一种解决办法。电脑安装uiaotomator的2.13.0版本，手机恢复出厂设置，然后连接电脑初始化atx，安装的是atx 0.9.5版本，然后手机横屏显示，d.screenshot()截图，就可以正常。

**Comment by codeskyblue** [comment]
最好提供一下手机型号，Android版本。这个原因主要是获取旋转失败导致的

**Comment by xiaqinga** [comment]
![QQ图片20210513134227](https://user-images.githubusercontent.com/18299045/118083257-2558d100-b3f1-11eb-8dbb-2d45e2c75f05.jpg)
这是我的手机型号
晚上我回去用另一个手机试试

**Comment by xiaqinga** [comment]
> 电脑安装uiaotomator的2.13.0版本，手机恢复出厂设置，然后连接电脑初始化atx，安装的是atx 0.9.5版本，然后手机横屏显示，d.screenshot（）截图，就可以正常。

3Q 我试试

**Comment by EvilDD** [comment]
一加8t 遇到此问题

**Comment by jiajia172000** [comment]
已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。

**Comment by i20548879** [comment]
> 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。

那直接降低minicap.so版本可以吗

**Comment by GlodenBoy** [comment]
> 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。

这个atx 该怎么处理？麻烦能说下atx 旋转的源码大概在哪吗

**Comment by i20548879** [comment]
> > 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。
> 
> 这个atx 该怎么处理？麻烦能说下atx 旋转的源码大概在哪吗



> > 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。
> 
> 这个atx 该怎么处理？麻烦能说下atx 旋转的源码大概在哪吗

我把降级autouimator到2.13.0之后就行了，不过atx得清理一下，然后截图速度也变慢了

**Comment by GlodenBoy** [comment]
> > > 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。
> > 
> > 
> > 这个atx 该怎么处理？麻烦能说下atx 旋转的源码大概在哪吗
> 
> > > 已经搞明白了。minicap原项目不再维护，作者fork了新项目，加入了对Android 11系统，sdk 30的支持，atxagent 0.10版本也加入了对此的支持，但因为minicap.so中已实现了截图旋转，atx在此基础上再旋转，就造成截图只有一半的问题。另外，Android 10及以下系统没有此问题，因为旧版本minicap.so中没有旋转。
> > 
> > 
> > 这个atx 该怎么处理？麻烦能说下atx 旋转的源码大概在哪吗
> 
> 我把降级autouimator到2.13.0之后就行了，不过atx得清理一下，然后截图速度也变慢了

这样直接换版本解决 一刀切不太好把，这样差了 不少版本，后面版本没有不兼容的更新吗，

**Comment by gavinjhliu** [comment]
把对应版本的minicap.so推送到手机上data/local/tmp上可以解决，参考https://cloud.tencent.com/developer/article/1893616，so下载地址https://github.com/varundtsfi/Android12Support_withso

**Comment by i20548879** [comment]
您好，我已收到邮件，我会仔细阅读后及时回复，祝生活顺心！

**Comment by fendoucg2019** [comment]
这个bug是open状态，看起来还没解决 @codeskyblue ，目前这个需求看起来比较强烈

**Comment by i20548879** [comment]
您好，我已收到邮件，我会仔细阅读后及时回复，祝生活顺心！

**Comment by akaX1** [comment]
这个算是比较严重的bug了

**Comment by i20548879** [comment]
您好，我已收到邮件，我会仔细阅读后及时回复，祝生活顺心！

**Comment by akaX1** [comment]
> https://github.com/varundtsfi/Android12Support_withso

调完之后好像默认截图是1080p的，怎么样自定义分辨率呢（我手机是480p）

**Comment by i20548879** [comment]
您好，我已收到邮件，我会仔细阅读后及时回复，祝生活顺心！
