### ISSUE TITLE
求救！截屏如何调整质量

### ISSUE THREAD

**Issue by wangtesting** [openatx/uiautomator2#682]
最新版本
    image = d.screenshot()
    image.save("{}.jpg".format(title))

情况：
     手机本身截图，可达到1m的大小，清晰度也好，使用airtest的截屏方式设置最高后，清晰度也不错，能达到600k
而uiautomator2的截图从源码也没看到能该质量的地方。。只是获取了屏幕的分辨率宽高，进行截图，但是清晰度不符合预期，仅有100k-200k左右，特来询问一下。。。 

目的：
    追求图片质量，不追求速度。

标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

**Comment by wangtesting** [comment]
已解决，加quality=95 即可

**Comment by akaX1** [comment]
> 已解决，加quality=95 即可

是在save（）中添加，还是在screenshot()中添加，我试过在screenshot(format='opencv'，quality=100)中添加，结果报错，图片放大会有锯齿，是压缩过的图片
