### ISSUE TITLE
频繁截图导致EGL mtrack疑似内存泄漏问题

### ISSUE THREAD

**Issue by jiajia172000** [openatx/uiautomator2#684]
我在测试时发现，华为荣耀NOTE8手机（4G内存），uiautomator2的版本号 2.13.0。在长时间循环调用d.screenshot()后（约每秒一次，调用一小时），手机内存会基本占满，手机明显卡顿。
调用adb shell dumpsys meminfo后，发现 EGL mtrack占用了2,309,408K。初步怀疑minicap 截图后不释放内存。目前只能重启手机解决。
恳请解决下。

**Comment by mingyuan-xia** [comment]
感谢专业技术信息，minicap问题修复周期非常长，比较被动的workaround是用atxagent间隔性地重启minicap看看是否能消除内存泄漏，如有尝试请在这里反馈结果，谢谢

**Comment by jiajia172000** [comment]
初步测试结果：在复现上述问题后，adb shell 登录手机，用kill 杀minicap后，EGL mtrack内存占用没有变化，kill 杀atx-agent后，EGL mtrack内存占用也没有变化。初步考虑为系统渲染内存占用超标。但不知道怎么释放。恳请指导。

**Comment by mingyuan-xia** [comment]
`dumpsys meminfo com.android.systemui` 可以加包名排查是哪个包
能否看下 `com.github.uiautomator` 和 `com.github.uiautomator.test`
如果这两个没有问题，再看下其他进程

**Comment by jiajia172000** [comment]
不好意思这么久才测试。占用EGL mtrack的是android.hardware.graphics.allocator@2.0-service，大约占用2.2G内存。com.github.uiautomator占用小。

**Comment by jiajia172000** [comment]
该问题在nokia iqoo等手机上测试均未复现。可能与华为系统有关。

**Comment by mingyuan-xia** [comment]
搜了一圈 minicap自己18年也报过这个问题
https://github.com/openstf/minicap/issues/135
xda也报过一个 也是华为的 https://forum.xda-developers.com/t/android-system-taking-all-memory.3870805/
初步断定是allocator的内存泄漏 应该多见于一些华为机型 华为机型的新rom patch应该fix了这个问题

**Comment by jiajia172000** [comment]
感谢指出。
