### ISSUE TITLE
UISelector textStartsWith generate a bug

### ISSUE THREAD

**Issue by mastrolube** [openatx/uiautomator2#689]
Hello codeskyblue, I've noticed that the UISelector `textStartsWith=` generates a bug..

In this case the object returns `exists: False` but the count is 1 (so it exists).

I made some test with that code:
```
          print(f"Text will start with: {username}")
          post_description = self.device.find(
              resourceId=ResourceID.ROW_FEED_COMMENT_TEXTVIEW_LAYOUT,
          )
          print(f"Text: {post_description.get_text()}")
          print(f"Exists: {post_description.exists()}, count: {post_description.count_items()}")
          post_test1 = self.device.find(
              resourceId=ResourceID.ROW_FEED_COMMENT_TEXTVIEW_LAYOUT,
              textStartsWith=username,
          )
          print(f"Exists: {post_test1.exists()}, count: {post_test1.count_items()}")
```
And this is the result:
```
# the string we will look for in the UISelector
Text will start with: pastorizia_gym_club

# the text that comes from the obj found without using the UISelector
Text: pastorizia_gym_club Dal nostro gruppo di Giuseppe 
Link store in bio ��👀👀… more

# the return of the find without UISelector
Exists: True, count: 1 

# the return of the find with the UISelector
Exists: False, count: 1 
```
As you can see the text actually starts with the username.
![immagine](https://user-images.githubusercontent.com/52335835/121781670-38082680-cba6-11eb-881d-7d1939e07c32.png)

I don't know what generates this issue, maybe the content of the text?
Thanks!

**Comment by mastrolube** [comment]
Ok @codeskyblue I found out the problem by testing with few texts.
Scenario1: the one above, you have a **multiple-line** text. That fails
Scenario2: tried with text with emoji in single line, no problems
Scenario3: the scenario1 text but without the `\n` (**single-line** text) WORKS.
![immagine](https://user-images.githubusercontent.com/52335835/121782305-2e33f280-cba9-11eb-9def-47114ad31c1d.png)
You can get text and bounds from these objects but if you try, for example, to click it fails:
```
-32002 Client error: <> data: Selector [resourceId='com.instagram.android:id/row_feed_comment_textview_layout', textStartsWith='pastorizia_gym_club'], method: None
```

I also tried with other UISelector in the past but if I didn't remember wrong they have the same problem.

Let me know :)
Bye

**Comment by thlengane** [comment]
Could be the same bug as this.

[https://github.com/openatx/uiautomator2/issues/360](url)

**Comment by codeskyblue** [comment]
the [androidx.test.uiautomator](https://developer.android.com/jetpack/androidx/releases/test-uiautomator) has been updated to 2.3.0, so I guess it should fixed now. reopen if still exists
