### ISSUE TITLE
Could not find a version that satisfies the requirement uiautomator2 (from versions: ) No matching distribution found for uiautomator2

### ISSUE THREAD

**Issue by HeartIsBeat** [openatx/uiautomator2#69]
mac下安装
pip install -U --pre uiautomator2

报错Could not find a version that satisfies the requirement uiautomator2 (from versions: ) No matching distribution found for uiautomator2
![image](https://user-images.githubusercontent.com/20472976/37814976-de155dd0-2ea7-11e8-997f-99d9a07d3a96.png)

**Comment by HeartIsBeat** [comment]
git clone https://github.com/openatx/uiautomator2
   sudo pip install -e uiautomator2
有个mac换成这个安装成功了，还有个mac一样的问题，还没成功。

**Comment by codeskyblue** [comment]
你这个是网络问题呀

**Comment by HeartIsBeat** [comment]
o(╥﹏╥)o试了10来遍都这样，普通网页还是能打开的。

**Comment by codeskyblue** [comment]
试试这个

```bash
pip install --pre -U uiautomator2 -i https://pypi.doubanio.com/simple
```

**Comment by HeartIsBeat** [comment]
灰常感谢，同事试了可以了。
