### ISSUE TITLE
Clicking on "nth" parameters & Start Dual Apps

### ISSUE THREAD

**Issue by alx-xlx** [openatx/uiautomator2#694]
My goal is to click on the first picture and perform task.

The problem is that there are two nodes in which all variables have similar values, except for `content-desc` and `bounds`. Since I am operating on a Gallery app I wouldn't be able to get hold of the content-desc`

I am trying to select and click on the "nth" occurence of `class` with a specific value.

![](https://i.imgur.com/RR6pfJZ.png)

![](https://i.imgur.com/Tlj1g9f.png)

How do I do that ?

And I would also like help on starting dual apps, it seems as dual apps have same package name, so it opens the original apps

**Comment by kristiker** [comment]
[n] for _selector objects and .all()[n] for xpath.XPathSelector
