### ISSUE TITLE
执行d.app_start("com.aaa.bbbbb")后，手机上没有正常打开应用

### ISSUE THREAD

**Issue by yanghuo662** [openatx/uiautomator2#72]
执行d.app_start("com.aaa.bbbbb")后，手机上没有正常打开应用
提示：leaks in com.aaa.bbbbb

试了一下其他应用都是打开正常的
如何把应用预先打开，是能够正常操作控件的，就是启动不了，奇怪

**Comment by codeskyblue** [comment]
方便把应用发过来一份吗

**Comment by yanghuo662** [comment]
好的，你的邮箱是？

**Comment by codeskyblue** [comment]
codeskyblue@gmail.com  这个应用可以公开吗？

**Comment by yanghuo662** [comment]
@codeskyblue 目前还不行

**Comment by yanghuo662** [comment]
@codeskyblue 那个应用安装ok吗，是不是因为这个应用有内存泄露的问题

**Comment by codeskyblue** [comment]
负责解析apk的go库是一个日本哥们写的，我得有空跟他讨论下

**Comment by yanghuo662** [comment]
嗯，报leakcanary 的空指针异常

**Comment by codeskyblue** [comment]
突然意思到一开始理解错方向了。app_start调用的是monkey命令启动的应用。
使用 `d.session("your-app-package")` 这种方法可以就好使了
