### ISSUE TITLE
macos 11.1安装appetizer白屏

### ISSUE THREAD

**Issue by dead0island** [openatx/uiautomator2#726]
macos 11.1安装appetizer打开后是白屏，虽然好像不应该提在这里，但我给contact@appetizer.io发邮件被退回了，想了解下是停止维护了吗
<img width="1392" alt="截屏2021-08-02 下午8 39 25" src="https://user-images.githubusercontent.com/83203086/127867056-84487b3e-5f75-4ba8-a992-d7b9daaa1570.png">
<img width="698" alt="截屏2021-08-02 下午8 44 51" src="https://user-images.githubusercontent.com/83203086/127867066-76cabc24-a3c5-4224-a8c8-2eb50ead3798.png">

以下为在应用目录里启动可执行文件的报错
`➜  ~ /Applications/Appetizer.app/Contents/MacOS/Appetizer
Error: async hook stack has become corrupted (actual: 9, expected: 0)
 1: 0x107e0d4b4 node::options_parser::DebugOptionsParser::DebugOptionsParser() [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x107d42110 node::InternalCallbackScope::Close() [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x107d41cbe node::InternalCallbackScope::~InternalCallbackScope() [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x107d6d1b9 node::RemoveEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x107d6d3c1 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x107d59352 node::InternalCallbackScope::Close() [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x107e7c154 uv_check_stop [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x107e774fb uv_run [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x104d0e37b v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x104d5505b v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x104db6422 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x104d5505b v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x104d6f4af v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x104d6f968 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x104e13f0a v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x104e171ca v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x104e1382f v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x7fff20415a0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
19: 0x7fff20415974 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
20: 0x7fff204156ef __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
21: 0x7fff20414121 __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
22: 0x7fff204136ce CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
23: 0x7fff211a0fa1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] [/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation]
24: 0x104e1440d v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x104e1334e v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x104d91315 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x107c5fba6 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x104c00ca9 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x105ff99ad v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
30: 0x104bffed4 v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
31: 0x102fa6d94 AtomMain [/Applications/Appetizer.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
32: 0x102f9bf10  [/Applications/Appetizer.app/Contents/Frameworks/Appetizer Helper.app/Contents/MacOS/Appetizer Helper]
33: 0x7fff20338621 start [/usr/lib/system/libdyld.dylib]`

**Comment by mingyuan-xia** [comment]
官网下载最新版本
