### ISSUE TITLE
输入文本内容后，控件往上移动，导致定位不到

### ISSUE THREAD

**Issue by 492456131** [openatx/uiautomator2#727]
- 手机型号：mumu模拟器--2.4.15.2
- uiautomator2的版本号：uiautomator2-------2.14.1
- 解析截图：
![image](https://user-images.githubusercontent.com/16437314/128617805-cd918984-67ec-4c08-9c73-165d0e774b7f.png)

没有调出底部输入法选择时，页面控件可以正常识别，但输入内容后，当前页面浮窗会往上移动，导致使用xpath定位后无法点击到OK按钮

**Comment by mingyuan-xia** [comment]
xpath定位就是不是绝对像素位置
