### ISSUE TITLE
使用USB无法连接设备

### ISSUE THREAD

**Issue by yanghuo662** [openatx/uiautomator2#73]
报错如下：
subprocess.CalledProcessError: Command 'adb -s 3353dd74 forward --list' returned non-zero exit status 1.

代码：
    d = u2.connect_usb('3353dd74')
    d.app_start("com.xdja.video.xypolice")

**Comment by codeskyblue** [comment]
运行
```
adb -s 3353dd74 forward --list
```
提示什么呢？

**Comment by yanghuo662** [comment]
什么都没有

D:\>adb -s 3353dd74 forward --list

D:\>adb -s 3353dd74 forward --list

D:\>

**Comment by codeskyblue** [comment]
对了，提供下adb的版本
`adb version`

**Comment by yanghuo662** [comment]
1.0.32

**Comment by yanghuo662** [comment]
1.0.32

**Comment by sail0755** [comment]
求问怎么解决呢？我也遇到了同样的问题

**Comment by codeskyblue** [comment]
备注下解决方案：
1. 怀疑可能是电脑存在多个adb

解决方法，先通过PATH查找到adb的路径，使用全路径调用adb  参考库 <https://github.com/pydanny/whichcraft>

**Comment by codeskyblue** [comment]
@sail0755 @yanghuo662 升级uiautomator2到最新版 `pip install --pre -U uiautomator` 然后再测试下看是否正常。
