### ISSUE TITLE
还是遇到模拟器截图黑屏的问题了

### ISSUE THREAD

**Issue by XDSwang** [openatx/uiautomator2#735]
- 我找到文档说不要安装minicap,没看懂怎么拦截让他不安装？
- 如果每次运行自动安装，不是每次都要停止么?
- 为什么初始化的时候不判断一下？

**Comment by XDSwang** [comment]
我现在删除安装路径下的minicap可以正常截图，如果每次初始化都要安装就要删除麻烦了

**Comment by codeskyblue** [comment]
现在模拟器应该是自动不安装 minicap了呀。你是什么模拟器？
