### ISSUE TITLE
询问： 支持 纯 flutter 页面吗

### ISSUE THREAD

**Issue by JsonYuu** [openatx/uiautomator2#739]
如题

**Comment by ZhaoGuan** [comment]
好像现在flutter官方的 driver 好像也都不能直接dump出页面信息  我现在是靠安卓原生的信息加上(这个换行符是真烦人) 图像识别做的 当然 图像识别 直接抄了 airtest源码

**Comment by AllenLuosong** [comment]
针对 flutter 的UI自动化找到这么一个解决方案，可以参考下 https://testerhome.com/topics/25388

**Comment by JsonYuu** [comment]
> 好像现在flutter官方的 driver 好像也都不能直接dump出页面信息 我现在是靠安卓原生的信息加上(这个换行符是真烦人) 图像识别做的 当然 图像识别 直接抄了 airtest源码

我这是 Android +Flutter  混合工程，也可以嘛？
【安卓原生的信息】 这个 啥意思啊？

**Comment by ZhaoGuan** [comment]
> > > > 好像现在flutter官方的 driver 好像也都不能直接dump出页面信息 我现在是靠安卓原生的信息加上(这个换行符是真烦人) 图像识别做的 当然 图像识别 直接抄了 airtest源码
> > > 
> > > 
> > > 我这是 Android +Flutter 混合工程，也可以嘛？
> > > 【安卓原生的信息】 这个 啥意思啊？
> > 
> > 
> > 如果你是因为抓页面信息抓不到 可以看 上面说的那个文章 然后 正常能拿到元素了 就可以正常用原生信息做定位操作了 但是因为没有id我这边都是依靠 content-desc 属性来定位 元素的 全路径定位会因为 layout 结构随机的问题定位不准
> 
> 确实，我刚刚看了，flutter 页面里面只要不是 图片，文字的话，content-desc 都是 有值的。
> 
> airtest 的 ocr 是怎么用的？或者说 使用场景是？
我是作为补充使用的 有个地方抓不到 元素结构我就用 airtest的方法来点击了
