### ISSUE TITLE
.watcher判断是否在锁屏，但不能滑动，只能点击按钮，有什么好的解决方案

### ISSUE THREAD

**Issue by cuba3** [openatx/uiautomator2#74]
d.watcher('slidingUnlock').when(resourceId='com.android.systemui:id/camera_button')\
    .swipe(540,1000,540,500)

无法使用swipe
希望后期版本加入条件判断支持滑动

**Comment by codeskyblue** [comment]
原生不支持呀

**Comment by cuba3** [comment]
d.press("home")
time.sleep(3)
if d(resourceId='com.android.systemui:id/camera_button').info['contentDescription'] == '相机':
    print('已找到锁屏相机按钮，执行滑动解锁操作')
    d.swipe(540,1900,540,1000)

解决demo，放到文档可以给别人做参考，if可以换成循环监听
