### ISSUE TITLE
截图大小异常

### ISSUE THREAD

**Issue by uplk** [openatx/uiautomator2#746]
问题：调用截图接口后，图片文件尺寸和手机一样，但是手机内容截图缩小了很多。
Name: uiautomator2
Version: 2.16.7

手机：华为mate 20 pro 分辨率 3120*1440

![0 0_3EP0219A07000649](https://user-images.githubusercontent.com/59159115/131948234-894bf491-e441-409b-ac9a-0a5c1952a700.png)

![image](https://user-images.githubusercontent.com/59159115/131948437-f6e8cf1e-0442-4e47-b76f-5db7f6240e59.png)

源代码：self.use.screenshot(path+str(event_count)+'_'+self.device_serial+'.png')

**Comment by codeskyblue** [comment]
这个在系统的分辨率设置里面，调成最大就可以了

**Comment by codeskyblue** [comment]
已经移除minicap，改成了screencap截图
