### ISSUE TITLE
dump_hierarchy 和 adb shell uiautomator dump 获取到的页面结构不一样

### ISSUE THREAD

**Issue by abeelan** [openatx/uiautomator2#748]
### 问题

页面上部分元素在 weditor 上获取不到，然后通过 dump_hierarchy() 打印出页面结构，也没找打这个元素；

执行 `adb shell uiautomator dump /sdcard/ui.xml`，在 `ui.xml` 文件内发现这个元素是存在的。

**请问，为什么两种方式获取到的页面结构会出现不同呢？有什么办法能定位到这个元素**

![image](https://user-images.githubusercontent.com/34361264/132163351-5d9009a2-5785-48de-b79f-1675761102b5.png)

> Name: uiautomator2
> Version: 2.12.2
> Android 10

**Comment by nicococococ** [comment]
uiautomator 真的是拉胯,adb uiautomator 获取到的dump也经常会缺东西

**Comment by codeskyblue** [comment]
没有特别完美的技术，只能是多个技术同时去用
