### ISSUE TITLE
mx4 pro uiautomator2 apk 删除后无法在重新安装，使用init命令仍然是success

### ISSUE THREAD

**Issue by 789dry** [openatx/uiautomator2#75]

**Comment by codeskyblue** [comment]
能不能详细点

**Comment by 789dry** [comment]
这个可能不是bug，详情描述如下：
》》使用命令python -m uiautomator2 init会自动安装本库所需要的设备端程序：uiautomator-server 、atx-agent、openstf/minicap、openstf/minitouch
这一步之后如果手动卸载了uiautomator-server这个apk，然后再次执行python -m uiautomator2 init，发现uiautomator-server这个apk不会自动安装了，即使卸载uiautomator2之后重装uiautomator这个apk也不会自动安装,而其他设备端程序安装正常。
注：使用的mx4 pro

**Comment by 5368** [comment]
我也遇到过类似情况：
手机：魅蓝ｅ１，已经init过，手机重启后的二次init
我是在init 时手机有提示安装uiautomator2 apk允许还是禁止，我点了禁止
手机上原来的uiautomator2图标没了，再也装不上了
＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
最后通过使用uiautomator[xiaocong]初始化后，又用uiautomator2　init才算搞定

**Comment by ponponon** [comment]
> 最后通过使用uiautomator[xiaocong]初始化后

这是什么意思？怎么操作?

**Comment by codeskyblue** [comment]
不需要初始化了
