### ISSUE TITLE
screenrecord录制视频时，视频录制无法停止

### ISSUE THREAD

**Issue by yqf0524** [openatx/uiautomator2#761]
- 手机型号：Android 9
- uiautomator2的版本号：2.16.7
- 手机截图
![image](https://user-images.githubusercontent.com/57915890/134853036-f8ae4a8f-b6ab-41c1-b654-fb10ca5cebd3.png)
![image](https://user-images.githubusercontent.com/57915890/134853069-630481bf-0aa8-4a91-ac05-33f71dce2f17.png)
- 问题描述：
  使用以下命令：
  d.screenrecord()
  sleep(10)
  d.screenrecord.stop()
  视频录制操作无法停止。如图所示，视频时长不可见，视频无法打开，等待一段时间视频大小增加。关闭python代码，视频录制停止，视频能够打开观看。可能的问题是什么？

**Comment by codeskyblue** [comment]
录屏的话试试  scrcpy这个项目吧，感觉比我写的好多了
