### ISSUE TITLE
模拟点击的速度问题

### ISSUE THREAD

**Issue by QianfengClarkShen** [openatx/uiautomator2#765]
【这不是bug，只是一个问题】

请问我如果想实现多个click，应当如何取消掉click之间的间隔？当前我的one plus Nord N10用UAI2进行80个点击需要20秒左右，但是用应用商店的连点小程序可以做到2秒钟执行完80个点击。请问有没有什么方法指定一串输入，然后让设备顺序执行它呢？

**Comment by codeskyblue** [comment]
如果要追求特别快的速度可以参考一下 minitouch这个项目 https://github.com/openatx/minitouch

**Comment by QianfengClarkShen** [comment]
Hi,

你们这个项目应该还是private的状态吧？我点进去是404:-)

**Comment by mingyuan-xia** [comment]
https://github.com/openstf/minitouch
