### ISSUE TITLE
【提议】增加将脚本打包成apk的功能

### ISSUE THREAD

**Issue by Lucienxhh** [openatx/uiautomator2#767]
比如我通过uiautomator2写了一个自动化的脚本，现在我想将该脚本普及为安卓apk，让其他人不了解代码的人安装使用。

**Comment by mingyuan-xia** [comment]
直接用Java写

**Comment by axepudding** [comment]
> 直接用Java写

请问一下，这个“直接用Java写”能不能有更详细一点的提示呢。谢谢
