### ISSUE TITLE
weditor 可识别到clickable，uiautomator2 识别不了

### ISSUE THREAD

**Issue by Qnner** [openatx/uiautomator2#774]
u2 version: 2.16.10
weditor version: 0.64

![image](https://user-images.githubusercontent.com/32847418/141401669-2446e5f2-fe8c-46a6-aea3-f63f8a40fd5b.png)

**Comment by Qnner** [comment]
![企业微信截图_16366865566124](https://user-images.githubusercontent.com/32847418/141402679-5be229bf-6b74-4816-939a-908136886bf0.png)

确认是bug一枚

**Comment by codeskyblue** [comment]
fixed
