### ISSUE TITLE
matching both conditions 

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#778]
I have this:
self.device(description='profile', index=4)

But for some reason it matches me this:
`<node index="3" text="" resource-id="" class="android.widget.Button" package="com.instagram.android" content-desc="Profile" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" visible-to-user="true" bounds="[608,48][704,160]" />`
 
Which have index 3.
exists() return True but count return 0.

Isn't it that both description and index need to be true ? is count need to be tested with exists ?

**Comment by codeskyblue** [comment]
复现方法：
```python
d(resourceId='android:id/icon', index=1).exists
```

**Comment by codeskyblue** [comment]
The android BySelector has no query method for index, so it is useless when pass index when use exist method.

https://developer.android.com/reference/androidx/test/uiautomator/By

**Comment by codeskyblue** [comment]
Change to https://developer.android.com/reference/androidx/test/uiautomator/UiSelector
will be fixed in 3.2.1

**Comment by codeskyblue** [comment]
index not match problem not reproduced

**Comment by codeskyblue** [comment]
BySelector与UiSelector各有其优缺点

- BySelector增加了对多屏的支持，但是缺少index
- UiSelector有index，但是缺少多屏支持。

**Comment by instasck** [comment]
so there was a problem and it is now fixed on 3.21. ok
