### ISSUE TITLE
把整个项目打包为一个exe文件后，怎么使用init呢，可以手动安装吗？

### ISSUE THREAD

**Issue by Hiyagg** [openatx/uiautomator2#78]
把我自己的程序, uiautomator2等库打包成一个exe可执行文件，在没有安装python环境的电脑里使用
前面的可以做到，但是初始化这一步怎么做，可以用adb命令手动安装那些手机需要的服务吗？

**Comment by codeskyblue** [comment]
欢迎加入atx+uiautomator2，群号码：499563266

群里有离线初始化工具，go语言写的
