### ISSUE TITLE
Will uiautomator2 support run on android devices?

### ISSUE THREAD

**Issue by caibingcheng** [openatx/uiautomator2#781]
As title, can uiautomator2 run on android devices?

I had wrote a uiautomator2 app and it works well on PC, but I want to run it on android devices thus the developers can use it anywhere. But ran failed, and get the output:
No devices detected PermissionError(1, 'Operation not permitted')

**Comment by mingyuan-xia** [comment]
use Google's uiautomator APIs and instrumentation tests directly
