### ISSUE TITLE
"unity SurfaceView" will choke u2

### ISSUE THREAD

**Issue by alx-xlx** [openatx/uiautomator2#796]
I recently found out that there is something that was blocking me from accessing xml of an android page using `d.dump_hierarchy()`

Here is the [apps link](https://play.google.com/store/apps/details?id=com.puzzlenation.dpcrosswords) if anyone wants to test it out.

The only app related field I could find was this:

`<node index="0" text="" resource-id="com.puzzlenation.dpcrosswords:id/unitySurfaceView" class="android.view.View" package="com.puzzlenation.dpcrosswords" content-desc="Game view" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[0,0][1080,1872]" />`

any solutions ?

**Comment by mingyuan-xia** [comment]
expected behavior on SurfaceView(s)
Android uiautomator API limitations
