### ISSUE TITLE
请问可以捕获游戏内的元素树吗

### ISSUE THREAD

**Issue by WenWu-Liu** [openatx/uiautomator2#804]
- 手机型号
![lADPJxDjw48EO3DNBQDNAkA_576_1280 jpg_720x720q90g](https://user-images.githubusercontent.com/88125617/159219222-7d5fa9dd-c53e-4221-99e2-c5f5cee0528d.jpg)

- uiautomator2的版本号(`pip show uiautomator2`)
Version: 2.16.14
- 手机截图
![4bd624db00f4d2af477d25c89ae3b0e8b4f34b3a2823000b785fd5764dc67bbdQzpcVXNlcnNcbGl1d3cyMTA4MTcwMVxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjQyODU2NzM5NF92MlxJbWFnZUZpbGVzXDE2NDc4NDc2ODE2NjBfQUY3RTlENUUtRUQ4RS00ODI5LUFEMEUtM0VDNjNBOTFBQzYyLnBuZw==](https://user-images.githubusercontent.com/88125617/159219560-64cff4d8-e897-4006-a62a-f8a9f708ebcc.png)

**Comment by WenWu-Liu** [comment]
目前有很多游戏SDK登录完成后，或者进入游戏后就捕获不了里面的控件了，有什么好的办法可以实现吗？最坏的打算只能通过截图来识别了

**Comment by codeskyblue** [comment]
游戏的界面都是用OPENGL画出来的，这个拿不到，除非用SDK的方法侵入。

**Comment by WenWu-Liu** [comment]
好吧，谢谢大佬
