### ISSUE TITLE
XPathLite的值在不同机子上不同

### ISSUE THREAD

**Issue by xjlin** [openatx/uiautomator2#806]
本人在个人电脑上获取微信的输入框xpath路径为
//*[@resource-id="com.tencent.mm:id/kit"]
但是在另一台电脑上获取的路径为
//*[@resource-id="com.tencent.mm:id/iki"]
uiautomator版本一致，请问会是什么原因导致这种情况呢。
*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue将自动被机器人打上`Invalid`标签并且自动关闭！！。

- mi10S
- 2.16.13
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

**Comment by hong-0220** [comment]
请问这个问题解决了吗

**Comment by codeskyblue** [comment]
别用resourceId就行，有的app的resourceId就是经常变化
