### ISSUE TITLE
Want stealth

### ISSUE THREAD

**Issue by instasck** [openatx/uiautomator2#808]
![image](https://user-images.githubusercontent.com/43851500/165805529-28678ffc-3a4a-448b-87e7-912fdcf8cd93.png)

Any app can detect the existence of ATX / uiauto.

Can we avoid it by giving a random name each time we install the app ?

**Comment by alx-xlx** [comment]
this is a very much needed feature, I think users should have access to set the package name for both these apps

**Comment by instasck** [comment]
I am willing to donate 100$ for that one.
A random name each installation.

**Comment by codeskyblue** [comment]
Still do not understand? Why do you need to use a random name?

**Comment by instasck** [comment]
Some of the use for this tool is not for testing homemade apps but also for third party.
They can detect the existence of those apps and block the work

**Comment by mingyuan-xia** [comment]
This is not an intended use case of this project
