### ISSUE TITLE
'Device' object has no attribute 'freeze_rotation'

### ISSUE THREAD

**Issue by Enerwen** [openatx/uiautomator2#809]
https://github.com/openatx/uiautomator2#screen-related 部分包含了Freeze/Un-freeze rotation的功能
但是调用的时候，报错没有这个函数

- 手机型号 ：OPPO RENO 7 5G
- uiautomator2的版本号：2.16.14
- 手机截图 无
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志) 

- 最好能附上可能复现问题的代码。
import uiautomator2 as u2
 d = u2.connect()
 d.freeze_rotation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Device' object has no attribute 'freeze_rotation'

**Comment by crackayus09** [comment]
For now, I am using below as a workaround.
`d.jsonrpc.freezeRotation()`

**Comment by codeskyblue** [comment]
d.jsonrpc.freezeRotation(True)

**Comment by codeskyblue** [comment]
fixed in 2.16.17
