### ISSUE TITLE
The documentation (read me) incorrectly specifies the method for stopping watch_context

### ISSUE THREAD

**Issue by Dskx54** [openatx/uiautomator2#812]
```
ctx = d.watch_context()
ctx.when("设置").click()
ctx.wait_stable() # 等待界面不在有弹窗了

ctx.close()
```

Instead of the "close" method, the "stop" method should be specified

otherwise, you may get an error

`AttributeError: 'WatchContext' object has no attribute 'close'
`

**Comment by mingyuan-xia** [comment]
a correction PR is welcomed
