### ISSUE TITLE
关于Could not detect idle state的问题

### ISSUE THREAD

**Issue by swordsoky** [openatx/uiautomator2#818]
手机型号：原生AndroidS
uiautomator2的版本号：2.16.17
问题描述：
高通的Camera应用，从AndroidR移植值到AndroidS后，Camera主界面的所有获取UI元素信息的动作都会高概率
出现Could not detect idle state，导致无法正确识别。
从网上查询说是需要等待界面idle才可以正常dump，此界面是相机的取景框界面，除了刷新取景框，应该没有动画，但不确定是不是取景框刷新导致。
此应用在AndroidR上是正常的，请问有什么办法规避？ 

从LogCat返回的UIAutomatorStub进程log如下：
_06-21 19:41:28.395 30179 32749 D UIAutomatorStub: URI: /jsonrpc/0, Method: POST, params, {NanoHttpd.QUERY_STRING=null}, files: {postData={"jsonrpc": "2.0", "id": "c67db2d236008945a4ddfff1e412eb6d", "method": "exist", "params": [{"mask": 1, "childOrSibling": [], "childOrSiblingSelector": [], "text": "Video"}]}}
	行 230023: 06-21 19:41:28.397 30179 32749 W QueryController: Could not detect idle state.
	行 230034: 06-21 19:41:28.439 30179 32749 W ByMatcher: Node returned null child: android.view.accessibility.AccessibilityNodeInfo@14e8208; boundsInParent: Rect(0, 0 - 720, 1650); boundsInScreen: Rect(0, 0 - 720, 1650); packageName: org.codeaurora.snapcam; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: org.codeaurora.snapcam:id/camera_capture_root; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null]
	行 230035: 06-21 19:41:28.440 30179 32749 W ByMatcher: Skipping null child (4 of 9)
	行 230037: 06-21 19:41:28.453 30179 32749 W ByMatcher: Node returned null child: android.view.accessibility.AccessibilityNodeInfo@14e8208; boundsInParent: Rect(0, 0 - 720, 1650); boundsInScreen: Rect(0, 0 - 720, 1650); packageName: org.codeaurora.snapcam; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: org.codeaurora.snapcam:id/camera_capture_root; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null]
	行 230038: 06-21 19:41:28.454 30179 32749 W ByMatcher: Skipping null child (4 of 9)
	行 230148: 06-21 19:41:28.993 30179 32749 D UIAutomatorStub: URI: /jsonrpc/0, Method: POST, params, {NanoHttpd.QUERY_STRING=null}, files: {postData={"jsonrpc": "2.0", "id": "cf865b6983fbf6cd78a563200f991ea7", "method": "exist", "params": [{"mask": 1, "childOrSibling": [], "childOrSiblingSelector": [], "text": "Video"}]}}
	行 230150: 06-21 19:41:28.995 30179 32749 W QueryController: Could not detect idle state._

**Comment by swordsoky** [comment]
工具应用调用了UiAutomation.java 类的如上public void waitForIdle](long idleTimeoutMillis, long globalTimeoutMillis)接口，但是我们打印下来，一直是idleTimeoutMillis: 500 globalTimeoutMillis 0，所有必然会打印Could not detect idle state

**Comment by codeskyblue** [comment]
打印出来Could not detect idle state，正常。
