### ISSUE TITLE
ByMatcher: Node returned null child，导致获取当前UI信息失败

### ISSUE THREAD

**Issue by swordsoky** [openatx/uiautomator2#819]
手机型号：原生AndroidS
uiautomator2的版本号：2.16.17
问题描述：
DUMP界面时出现如下异常提示，导致获取当前UI信息失败
请问此提示的匹配是自己写的？ 还是调用了系统的接口？ 
W ByMatcher: Node returned null child: android.view.accessibility.AccessibilityNodeInfo@11732b; boundsInParent: Rect(0, 0 - 720, 1650); boundsInScreen: Rect(0, 0 - 720, 1650); packageName: org.codeaurora.snapcam; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; stateDescription: null; contentDescription: null; tooltipText: null; viewIdResName: org.codeaurora.snapcam:id/camera_capture_root; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: false; visible: true; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null]
07-04 16:02:46.402  3437 22055 W ByMatcher: Skipping null child (4 of 9)

**Comment by codeskyblue** [comment]
UiAutomator2依赖库已升级，重新测试一下。先关掉了
