### ISSUE TITLE
'requests' has no attribute 'ReadTimeout' ERROR

### ISSUE THREAD

**Issue by alx-xlx** [openatx/uiautomator2#824]
<img width="479" alt="cjOlUVVIZS" src="https://user-images.githubusercontent.com/42188371/183133343-54eaff2a-80b5-44f1-b6f3-c7c5116ce212.png">

I am getting this `AttributeError: module 'requests' has no attribute 'ReadTimeout'` ERROR

it just appeared now, I can't run uiautomator2, please help
what is the problem ?

**Comment by codeskyblue** [comment]
try
pip3 install -U requests
may be help

**Comment by alx-xlx** [comment]
that helped :)
but then I was getting some sort of `adbutil` error, but it has disappeared few days ago on its own
