### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 'FAIL'

### ISSUE THREAD

**Issue by wennuandehuali** [openatx/uiautomator2#825]
08-09 17:53:01     d.press("enter")
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 1159, in press
08-09 17:53:01     return self.jsonrpc.pressKey(key)
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 475, in __call__
08-09 17:53:01     return self.server._jsonrpc_retry_call(self.method, params,
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 482, in _jsonrpc_retry_call
08-09 17:53:01     return self._jsonrpc_call(*args, **kwargs)
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 508, in _jsonrpc_call
08-09 17:53:01     res = self.http.post("/jsonrpc/0",
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
08-09 17:53:01     return self.request("POST", url, data=data, json=json, **kwargs)
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 202, in request
08-09 17:53:01     url = self.__client.path2url(url)
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 301, in path2url
08-09 17:53:01     return urlparse.urljoin(self._get_atx_agent_url(), path)
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/uiautomator2/__init__.py", line 282, in _get_atx_agent_url
08-09 17:53:01     lport = self._adb_device.forward_port(
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/adbutils/_device.py", line 236, in forward_port
08-09 17:53:01     for f in self.forward_list():
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/adbutils/_device.py", line 245, in forward_list
08-09 17:53:01     content = c.read_string_block()
08-09 17:53:01   File "/home/user/.local/lib/python3.9/site-packages/adbutils/_adb.py", line 118, in read_string_block
08-09 17:53:01     size = int(length, 16)
08-09 17:53:01 ValueError: invalid literal for int() with base 16: 'FAIL'

**Comment by wennuandehuali** [comment]
调用d.press("enter")  报错  ValueError: invalid literal for int() with base 16: 'FAIL'

**Comment by codeskyblue** [comment]
adb forward --list
这个命令返回什么？

**Comment by wennuandehuali** [comment]
192.168.1.30:5555 tcp:47681 tcp:7912
192.168.1.30:5555 tcp:54515 tcp:7912
192.168.1.30:5555 tcp:54951 tcp:7912
192.168.1.30:5555 tcp:48181 tcp:7912
192.168.1.30:5555 tcp:40363 tcp:7912
192.168.1.30:5555 tcp:39425 tcp:7912
192.168.1.30:5555 tcp:34723 tcp:7912
192.168.1.30:5555 tcp:50053 tcp:7912
192.168.1.30:5555 tcp:35835 tcp:7912
192.168.1.30:5555 tcp:53159 tcp:7912
192.168.1.30:5555 tcp:40587 tcp:7912
192.168.1.30:5555 tcp:58995 tcp:7912
192.168.1.30:5555 tcp:42843 tcp:7912
192.168.1.30:5555 tcp:32995 tcp:7912
192.168.1.30:5555 tcp:41015 tcp:7912
192.168.1.30:5555 tcp:47755 tcp:7912
192.168.1.30:5555 tcp:51737 tcp:7912
192.168.1.30:5555 tcp:39371 tcp:7912
192.168.1.30:5555 tcp:58861 tcp:7912
192.168.1.30:5555 tcp:57447 tcp:7912
192.168.1.30:5555 tcp:34495 tcp:7912
192.168.1.30:5555 tcp:51179 tcp:7912
192.168.1.30:5555 tcp:49505 tcp:7912
192.168.1.30:5555 tcp:41551 tcp:7912
192.168.1.30:5555 tcp:48609 tcp:7912
192.168.1.30:5555 tcp:50597 tcp:7912
192.168.1.30:5555 tcp:58047 tcp:7912
192.168.1.30:5555 tcp:49803 tcp:7912
192.168.1.30:5555 tcp:43629 tcp:7912
192.168.1.30:5555 tcp:47359 tcp:7912
192.168.1.30:5555 tcp:44377 tcp:7912
192.168.1.30:5555 tcp:47441 tcp:7912
192.168.1.30:5555 tcp:43491 tcp:7912
192.168.1.30:5555 tcp:37647 tcp:7912
192.168.1.30:5555 tcp:43263 tcp:7912
192.168.1.30:5555 tcp:37437 tcp:7912
192.168.1.30:5555 tcp:47829 tcp:7912
192.168.1.30:5555 tcp:41817 tcp:7912
192.168.1.30:5555 tcp:41263 tcp:7912
192.168.1.30:5555 tcp:58979 tcp:7912
192.168.1.30:5555 tcp:51479 tcp:7912
192.168.1.30:5555 tcp:55983 tcp:7912
192.168.1.30:5555 tcp:49149 tcp:7912
192.168.1.30:5555 tcp:36653 tcp:7912
192.168.1.30:5555 tcp:33631 tcp:7912
192.168.1.30:5555 tcp:53351 tcp:7912
192.168.1.30:5555 tcp:47571 tcp:7912
192.168.1.30:5555 tcp:50981 tcp:7912
192.168.1.30:5555 tcp:56161 tcp:7912
192.168.1.30:5555 tcp:35663 tcp:7912
192.168.1.30:5555 tcp:53019 tcp:7912
192.168.1.30:5555 tcp:49073 tcp:7912
192.168.1.30:5555 tcp:36003 tcp:7912
192.168.1.30:5555 tcp:51297 tcp:7912
192.168.1.30:5555 tcp:46761 tcp:7912
192.168.1.30:5555 tcp:37795 tcp:7912
192.168.1.30:5555 tcp:47223 tcp:7912
192.168.1.30:5555 tcp:37653 tcp:7912
192.168.1.30:5555 tcp:32895 tcp:7912
192.168.1.30:5555 tcp:38969 tcp:7912
192.168.1.30:5555 tcp:38437 tcp:7912
192.168.1.30:5555 tcp:33917 tcp:7912
192.168.1.30:5555 tcp:39161 tcp:7912
192.168.1.30:5555 tcp:57747 tcp:7912
192.168.1.30:5555 tcp:51703 tcp:7912
192.168.1.30:5555 tcp:32897 tcp:7912
192.168.1.30:5555 tcp:53317 tcp:7912
192.168.1.30:5555 tcp:55385 tcp:7912
192.168.1.30:5555 tcp:48465 tcp:7912
192.168.1.30:5555 tcp:54997 tcp:7912
192.168.1.30:5555 tcp:49465 tcp:7912
192.168.1.30:5555 tcp:35575 tcp:7912
192.168.1.30:5555 tcp:36819 tcp:7912
192.168.1.30:5555 tcp:51975 tcp:7912
192.168.1.30:5555 tcp:53295 tcp:7912
192.168.1.30:5555 tcp:44691 tcp:7912
192.168.1.30:5555 tcp:42435 tcp:7912
192.168.1.30:5555 tcp:49897 tcp:7912
192.168.1.30:5555 tcp:41167 tcp:7912
192.168.1.30:5555 tcp:44813 tcp:7912
192.168.1.30:5555 tcp:52957 tcp:7912
192.168.1.30:5555 tcp:56283 tcp:7912
192.168.1.30:5555 tcp:39759 tcp:7912
192.168.1.30:5555 tcp:43059 tcp:7912
192.168.1.30:5555 tcp:49729 tcp:7912
192.168.1.30:5555 tcp:45425 tcp:7912
192.168.1.30:5555 tcp:34751 tcp:7912
192.168.1.30:5555 tcp:45061 tcp:7912
192.168.1.30:5555 tcp:42509 tcp:7912
192.168.1.30:5555 tcp:57893 tcp:7912
192.168.1.30:5555 tcp:59589 tcp:7912
192.168.1.30:5555 tcp:57169 tcp:7912
192.168.1.30:5555 tcp:51833 tcp:7912
192.168.1.30:5555 tcp:38501 tcp:7912
192.168.1.30:5555 tcp:48267 tcp:7912
192.168.1.30:5555 tcp:57693 tcp:7912
192.168.1.30:5555 tcp:47683 tcp:7912
192.168.1.30:5555 tcp:44723 tcp:7912
192.168.1.30:5555 tcp:48213 tcp:7912
192.168.1.30:5555 tcp:41125 tcp:7912
192.168.1.30:5555 tcp:48801 tcp:7912
192.168.1.30:5555 tcp:33697 tcp:7912
192.168.1.30:5555 tcp:44083 tcp:7912
192.168.1.30:5555 tcp:36431 tcp:7912
192.168.1.30:5555 tcp:58815 tcp:7912
192.168.1.30:5555 tcp:57745 tcp:7912
192.168.1.30:5555 tcp:42305 tcp:7912
192.168.1.30:5555 tcp:32991 tcp:7912
192.168.1.30:5555 tcp:56789 tcp:7912
192.168.1.30:5555 tcp:60121 tcp:7912
192.168.1.30:5555 tcp:55739 tcp:7912
192.168.1.30:5555 tcp:42575 tcp:7912
192.168.1.30:5555 tcp:36129 tcp:7912
192.168.1.30:5555 tcp:60575 tcp:7912
192.168.1.30:5555 tcp:60849 tcp:7912
192.168.1.30:5555 tcp:45313 tcp:7912
192.168.1.30:5555 tcp:35093 tcp:7912
192.168.1.30:5555 tcp:52989 tcp:7912
192.168.1.30:5555 tcp:56897 tcp:7912
192.168.1.30:5555 tcp:37029 tcp:7912
192.168.1.30:5555 tcp:55489 tcp:7912
192.168.1.30:5555 tcp:53281 tcp:7912
192.168.1.30:5555 tcp:54161 tcp:7912
192.168.1.30:5555 tcp:60143 tcp:7912
192.168.1.30:5555 tcp:39071 tcp:7912
192.168.1.30:5555 tcp:46771 tcp:7912
192.168.1.30:5555 tcp:42079 tcp:7912
192.168.1.30:5555 tcp:49967 tcp:7912
192.168.1.30:5555 tcp:34743 tcp:7912
192.168.1.30:5555 tcp:42173 tcp:7912
192.168.1.30:5555 tcp:47435 tcp:7912
192.168.1.30:5555 tcp:35325 tcp:7912
192.168.1.30:5555 tcp:54569 tcp:7912
192.168.1.30:5555 tcp:50409 tcp:7912
192.168.1.30:5555 tcp:54901 tcp:7912
192.168.1.30:5555 tcp:48705 tcp:7912
192.168.1.30:5555 tcp:57475 tcp:7912
192.168.1.30:5555 tcp:49243 tcp:7912
192.168.1.30:5555 tcp:38017 tcp:7912
192.168.1.30:5555 tcp:56505 tcp:7912
192.168.1.30:5555 tcp:48171 tcp:7912
192.168.1.30:5555 tcp:59827 tcp:7912
192.168.1.30:5555 tcp:49679 tcp:7912
192.168.1.30:5555 tcp:40545 tcp:7912
192.168.1.30:5555 tcp:55999 tcp:7912
192.168.1.30:5555 tcp:60669 tcp:7912
192.168.1.30:5555 tcp:51901 tcp:7912
192.168.1.30:5555 tcp:46925 tcp:7912
192.168.1.30:5555 tcp:46155 tcp:7912
192.168.1.30:5555 tcp:37613 tcp:7912
192.168.1.30:5555 tcp:32993 tcp:7912
192.168.1.30:5555 tcp:59341 tcp:7912
192.168.1.30:5555 tcp:41953 tcp:7912
192.168.1.30:5555 tcp:41915 tcp:7912
192.168.1.30:5555 tcp:52385 tcp:7912
192.168.1.30:5555 tcp:42337 tcp:7912
192.168.1.30:5555 tcp:35419 tcp:7912
192.168.1.30:5555 tcp:40861 tcp:7912
192.168.1.30:5555 tcp:40023 tcp:7912
192.168.1.30:5555 tcp:41813 tcp:7912
192.168.1.30:5555 tcp:34933 tcp:7912
192.168.1.30:5555 tcp:46269 tcp:7912
192.168.1.30:5555 tcp:47659 tcp:7912
192.168.1.30:5555 tcp:58905 tcp:7912
192.168.1.30:5555 tcp:37207 tcp:7912
192.168.1.30:5555 tcp:52375 tcp:7912
192.168.1.30:5555 tcp:42629 tcp:7912
192.168.1.30:5555 tcp:46641 tcp:7912
192.168.1.30:5555 tcp:42265 tcp:7912
192.168.1.30:5555 tcp:32851 tcp:7912
192.168.1.30:5555 tcp:34139 tcp:7912
192.168.1.30:5555 tcp:37825 tcp:7912
192.168.1.30:5555 tcp:43535 tcp:7912
192.168.1.30:5555 tcp:56603 tcp:7912
192.168.1.30:5555 tcp:53289 tcp:7912
192.168.1.30:5555 tcp:36347 tcp:7912
192.168.1.30:5555 tcp:33491 tcp:7912
192.168.1.30:5555 tcp:57873 tcp:7912
192.168.1.30:5555 tcp:39073 tcp:7912
192.168.1.30:5555 tcp:52231 tcp:7912
192.168.1.30:5555 tcp:52651 tcp:7912
192.168.1.30:5555 tcp:47699 tcp:7912
192.168.1.30:5555 tcp:48541 tcp:7912
192.168.1.30:5555 tcp:54365 tcp:7912
192.168.1.30:5555 tcp:41891 tcp:7912
192.168.1.30:5555 tcp:38555 tcp:7912
192.168.1.30:5555 tcp:60357 tcp:7912
192.168.1.30:5555 tcp:53595 tcp:7912
192.168.1.30:5555 tcp:41743 tcp:7912
192.168.1.30:5555 tcp:55067 tcp:7912
192.168.1.30:5555 tcp:37851 tcp:7912
192.168.1.30:5555 tcp:37835 tcp:7912
192.168.1.30:5555 tcp:59489 tcp:7912
192.168.1.30:5555 tcp:35081 tcp:7912
192.168.1.30:5555 tcp:41691 tcp:7912
192.168.1.30:5555 tcp:44633 tcp:7912
192.168.1.30:5555 tcp:54699 tcp:7912
192.168.1.30:5555 tcp:35153 tcp:7912
192.168.1.30:5555 tcp:56641 tcp:7912
192.168.1.30:5555 tcp:42747 tcp:7912
192.168.1.30:5555 tcp:55571 tcp:7912
192.168.1.30:5555 tcp:57003 tcp:7912
192.168.1.30:5555 tcp:50605 tcp:7912
192.168.1.30:5555 tcp:33061 tcp:7912
192.168.1.30:5555 tcp:36859 tcp:7912
192.168.1.30:5555 tcp:48167 tcp:7912
192.168.1.30:5555 tcp:41909 tcp:7912
192.168.1.30:5555 tcp:36547 tcp:7912
192.168.1.30:5555 tcp:58983 tcp:7912
192.168.1.30:5555 tcp:49875 tcp:7912
192.168.1.30:5555 tcp:39225 tcp:7912
192.168.1.30:5555 tcp:45487 tcp:7912
192.168.1.30:5555 tcp:40751 tcp:7912
192.168.1.30:5555 tcp:46845 tcp:7912
192.168.1.30:5555 tcp:54463 tcp:7912
192.168.1.30:5555 tcp:44353 tcp:7912
192.168.1.30:5555 tcp:45339 tcp:7912
192.168.1.30:5555 tcp:45109 tcp:7912
192.168.1.30:5555 tcp:56163 tcp:7912
192.168.1.30:5555 tcp:53425 tcp:7912
192.168.1.30:5555 tcp:55213 tcp:7912
192.168.1.30:5555 tcp:53233 tcp:7912
192.168.1.30:5555 tcp:43545 tcp:7912
192.168.1.30:5555 tcp:48377 tcp:7912
192.168.1.30:5555 tcp:53195 tcp:7912
192.168.1.30:5555 tcp:38985 tcp:7912
192.168.1.30:5555 tcp:41305 tcp:7912
192.168.1.30:5555 tcp:48115 tcp:7912
192.168.1.30:5555 tcp:38319 tcp:7912
192.168.1.30:5555 tcp:39819 tcp:7912
192.168.1.30:5555 tcp:54783 tcp:7912
192.168.1.30:5555 tcp:39355 tcp:7912
192.168.1.30:5555 tcp:57333 tcp:7912
192.168.1.30:5555 tcp:58055 tcp:7912
192.168.1.30:5555 tcp:49791 tcp:7912
192.168.1.30:5555 tcp:35187 tcp:7912
192.168.1.30:5555 tcp:51707 tcp:7912
192.168.1.30:5555 tcp:55197 tcp:7912
192.168.1.30:5555 tcp:58889 tcp:7912
192.168.1.30:5555 tcp:37963 tcp:7912
192.168.1.30:5555 tcp:41349 tcp:7912
192.168.1.30:5555 tcp:34419 tcp:7912
192.168.1.30:5555 tcp:58609 tcp:7912
192.168.1.30:5555 tcp:44849 tcp:7912
192.168.1.30:5555 tcp:50277 tcp:7912
192.168.1.30:5555 tcp:45453 tcp:7912
192.168.1.30:5555 tcp:59841 tcp:7912
192.168.1.30:5555 tcp:46243 tcp:7912
192.168.1.30:5555 tcp:54421 tcp:7912
192.168.1.30:5555 tcp:43009 tcp:7912
192.168.1.30:5555 tcp:50069 tcp:7912
192.168.1.30:5555 tcp:48323 tcp:7912
192.168.1.30:5555 tcp:47239 tcp:7912
192.168.1.30:5555 tcp:56993 tcp:7912
192.168.1.30:5555 tcp:51079 tcp:7912
192.168.1.30:5555 tcp:42301 tcp:7912
192.168.1.30:5555 tcp:45683 tcp:7912
192.168.1.30:5555 tcp:51311 tcp:7912
192.168.1.30:5555 tcp:43191 tcp:7912
192.168.1.30:5555 tcp:59831 tcp:7912
192.168.1.30:5555 tcp:35373 tcp:7912
192.168.1.30:5555 tcp:48867 tcp:7912
192.168.1.30:5555 tcp:46881 tcp:7912
192.168.1.30:5555 tcp:54939 tcp:7912
192.168.1.30:5555 tcp:40891 tcp:7912
192.168.1.30:5555 tcp:49773 tcp:7912
192.168.1.30:5555 tcp:53373 tcp:7912
192.168.1.30:5555 tcp:40703 tcp:7912
192.168.1.30:5555 tcp:55691 tcp:7912
192.168.1.30:5555 tcp:60703 tcp:7912
192.168.1.30:5555 tcp:47945 tcp:7912
192.168.1.30:5555 tcp:54061 tcp:7912
192.168.1.30:5555 tcp:45165 tcp:7912
192.168.1.30:5555 tcp:52917 tcp:7912
192.168.1.30:5555 tcp:59727 tcp:7912
192.168.1.30:5555 tcp:53533 tcp:7912
192.168.1.30:5555 tcp:40479 tcp:7912
192.168.1.30:5555 tcp:44453 tcp:7912
192.168.1.30:5555 tcp:54495 tcp:7912
192.168.1.30:5555 tcp:40261 tcp:7912
192.168.1.30:5555 tcp:38223 tcp:7912
192.168.1.30:5555 tcp:35421 tcp:7912
192.168.1.30:5555 tcp:53095 tcp:7912

**Comment by wennuandehuali** [comment]
请问下 这个  大概是 什么 问题导致的

**Comment by wennuandehuali** [comment]
> adb forward --list 这个命令返回什么？

如上哈

**Comment by wennuandehuali** [comment]
有啥办法可以 规避吗

**Comment by TangSir61** [comment]
c_activity = device.u2_d.app_current()['activity']
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator2\__init__.py", line 1345, in app_current
    m = _focusedRE.search(self.shell(['dumpsys', 'window', 'windows'])[0])
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator2\__init__.py", line 433, in shell
    ret = self.http.post("/shell", data=data, timeout=timeout+10)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator2\__init__.py", line 202, in request
    url = self.__client.path2url(url)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator2\__init__.py", line 306, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\uiautomator2\__init__.py", line 287, in _get_atx_agent_url
    lport = self._adb_device.forward_port(
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\adbutils\__init__.py", line 597, in forward_port
    for f in self.forward_list():
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\adbutils\__init__.py", line 381, in forward_list
    content = c.read_string_block()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\site-packages\adbutils\__init__.py", line 153, in read_string_block
    size = int(length, 16)
ValueError: invalid literal for int() with base 16: 'FAIL'

**Comment by TangSir61** [comment]
同问题

**Comment by sadmenmenmen** [comment]
同问题，必须重启电脑。。。

**Comment by sadmenmenmen** [comment]
File "E:\tianqin_test\device_control.py", line 26, in __init__
    self.device.uiautomator.start()
  File "C:\python37\lib\site-packages\uiautomator2\__init__.py", line 565, in uiautomator
    return _Service("uiautomator", self)
  File "C:\python37\lib\site-packages\uiautomator2\__init__.py", line 156, in __init__
    self.service_url = self.u2obj.path2url("/services/" + name)
  File "C:\python37\lib\site-packages\uiautomator2\__init__.py", line 301, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "C:\python37\lib\site-packages\uiautomator2\__init__.py", line 283, in _get_atx_agent_url
    7912)  # this method is so fast, only take 0.2ms
  File "C:\python37\lib\site-packages\adbutils\_device.py", line 252, in forward_port
    for f in self.forward_list():
  File "C:\python37\lib\site-packages\adbutils\_device.py", line 261, in forward_list
    content = c.read_string_block()
  File "C:\python37\lib\site-packages\adbutils\_adb.py", line 119, in read_string_block
    size = int(length, 16)
ValueError: invalid literal for int() with base 16: 'FAIL'

**Comment by codeskyblue** [comment]
我觉的现在应该好了，先关了，有问题再reopen
