### ISSUE TITLE
截图不全

### ISSUE THREAD

**Issue by suqingyue738** [openatx/uiautomator2#828]
'display': {'width': 1080, 'height': 2220}
![image](https://user-images.githubusercontent.com/12101941/185049437-f202fdb7-7ef0-4e8d-9219-96b25537a97b.png)
![image](https://user-images.githubusercontent.com/12101941/185049634-48005fcc-edd5-48e9-830a-f4d5783cea85.png)
截图不全，估计是只考虑到1080p？

**Comment by codeskyblue** [comment]
已修改为screencap截图
