### ISSUE TITLE
Pinch not working on some full screen game screens

### ISSUE THREAD

**Issue by MDasky1** [openatx/uiautomator2#831]
Trying to use the selector to pinch or zoom a full screen app on bluestacks. When I hit the arrow keys on Bluestacks to do a pinch or zoom, it shows big white dots like there was a tap on the screen, then the motion for the pinch or zoom. UIAutomator2 does not have the big white dots, only the motion indicators. I think this may be a reason the app is not seeing the pinch or zoom. It could also be the way the app is coded because it works in other apps. Is there a way we can apply a pinch or zoom to the application instead of trying to find the correct selector for it?

**Comment by codeskyblue** [comment]
try the lastest uiautomator2 >= 3.2.0, close for now, reopen it if still exist

use d.guesture is also fine
