### ISSUE TITLE
在s20手机运行8小时后，uiautormator2操作失效，执行check命令后恢复正常

### ISSUE THREAD

**Issue by bodian520** [openatx/uiautomator2#833]
- 手机型号：三星 s20
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
之前没有出现过这样的情况，最近一周出现：
在s20手机运行8小时后，uiautormator2操作失效，无法进行点击等操作，同时使用adb点击正常；
执行python3  -m uiautomator2 --serial RFCNC0S1WQR check命令
重新启动应用后，恢复正常 
该情况已经连续三天出现
请问是什么原因，有没有彻底的解决办法？

**Comment by ymzpccz** [comment]
我也遇到同样的问题
