### ISSUE TITLE
如何在平台上移出设备

### ISSUE THREAD

**Issue by NextOneWxf** [openatx/uiautomator2#84]
如何在平台上移出设备

**Comment by codeskyblue** [comment]
关掉atx-agent

**Comment by NextOneWxf** [comment]
你指的是哪种？ 1. 打开点击 “停止ATXAGENT” 2.打开点击 “QUIT” 3.将 uiautomator2 APP退出

**Comment by codeskyblue** [comment]
停止atx-agent就可以了。

**Comment by codeskyblue** [comment]
@NextOneWxf 删除数据这个功能并没有做，现在只有直接操作数据库了
```
r.db("atxserver").table("devices").get($UDID).delete()
```

或者暴力一点把所有离线的都删除了

```js
r.db("atxserver").table("devices").filter({present: false}).delete()
```

![image](https://user-images.githubusercontent.com/3281689/39033094-f8f298b4-44a2-11e8-8e4c-9487d05fa365.png)

**Comment by NextOneWxf** [comment]
好的，谢谢
