### ISSUE TITLE
app权限申请时浮层定位不到

### ISSUE THREAD

**Issue by scrawman** [openatx/uiautomator2#841]
![image](https://user-images.githubusercontent.com/58428097/200166863-344273fd-ef02-4128-9239-e88cd9d486c5.png)
如上图，贝壳找房app在申请权限时会告知用户权限的使用目的（摄像头权限使用说明），但是这个浮层被手机自带的权限申请覆盖了，导致uiautomator识别不到，请问有办法解决吗？
手机机型：小米11

**Comment by codeskyblue** [comment]
没什么好办法，用OCR更方便
