### ISSUE TITLE
无法、错误获得 当前 activity 的问题

### ISSUE THREAD

**Issue by GentLiu** [openatx/uiautomator2#843]
使用 d.app_current()["activity"] 获取的activity名称为错误的，跟踪发现是由于 dumpsys activity 命令超时导致的，

一个返回的例子是：
TASK 10063:com.android.camera.CameraActivity id=814 userId=0
  ACTIVITY com.hmdglobal.app.camera/com.android.camera.CameraActivity 589e99e pid=8859
    Failure while dumping the activity: java.io.IOException: Timeout

TASK 10045:com.google.android.apps.wallpaper id=821 userId=0
  ACTIVITY com.google.android.apps.wallpaper/.picker.CategoryPickerActivity d1c6bab pid=12994

*** SERVICE 'activity' DUMP TIMEOUT (10000ms) EXPIRED ***

*** SERVICE 'activity' DUMP TIMEOUT (10000ms) EXPIRED ***

因此我的解决方法是增加超时到 60 秒：
Line 1356 : output, _ = self.shell(['dumpsys', '-t', '60', 'activity', 'activities'])

Line 1366: output, _ = self.shell(['dumpsys', '-t', '60', 'activity', 'top'])

**Comment by gleke** [comment]
修改那个文件？

**Comment by codeskyblue** [comment]
duplicated
