### ISSUE TITLE
单引号引起的selector问题

### ISSUE THREAD

**Issue by DavinShire** [openatx/uiautomator2#847]
- 手机型号 : 荣耀. 型号未知
- 
- uiautomator2的版本号(`pip show uiautomator2`)
- Name: uiautomator2
Version: 2.16.18
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\python38-10\lib\site-packages
Requires: adbutils, cached-property, Deprecated, filelock, logzero, lxml, packaging, Pillow, progress, requests, retry, six, whichcraft
Required-by: weditor

以下两条代码:

d(resourceId="com.hihonor.camera:id/shutter_button").click()
d(resourceId='com.hihonor.camera:id/shutter_button').click()
双引号能触发点击, 但单引号会索引不到

[window_dump.txt](https://github.com/openatx/uiautomator2/files/10074455/window_dump.txt)

**Comment by codeskyblue** [comment]
strange
