### ISSUE TITLE
如何在pc端终止手机上运行的脚本？

### ISSUE THREAD

**Issue by lin3547** [openatx/uiautomator2#851]
执行一个无限循环调用的脚本，发现从电脑端的CMD中止脚本时，手机上的脚本依然在运行，是否有什么方案可以在pc端强制中止所有手机上运行的脚本？

- 手机型号   32款手机同时调用，包括华为、小米、vivo、魅族、摩托罗拉等多款较新的型号
- uiautomator2的版本号(`pip show uiautomator2`)   v2.16.19

**Comment by codeskyblue** [comment]
现在会停了

**Comment by lin3547** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
