### ISSUE TITLE
499563266加群不了

### ISSUE THREAD

**Issue by gleke** [openatx/uiautomator2#855]
好不容易找到组织，但499563266加群不了，麻烦群主高抬贵手。

**Comment by codeskyblue** [comment]
群号没错呀，提示什么错误呀

**Comment by gleke** [comment]
没有人审核？qq:237401117，麻烦加一下,谢谢！

**Comment by codeskyblue** [comment]
改了一下，自动加群规则。回答正确问题就行了。

**Comment by fish-ball** [comment]
2000 人群都满了~~求拉啊，最近在研读代码，希望交流一下后面好提PR，谢谢！
