### ISSUE TITLE
开关类型的元素，打开和关闭元素属性都一样，如何区分？（暂时不想使用图像识别，怕不稳定）

### ISSUE THREAD

**Issue by ssfanli** [openatx/uiautomator2#861]
RT
<img width="373" alt="image" src="https://user-images.githubusercontent.com/53210634/209310068-88d6a8b2-b643-482e-901d-5aa861e9e0a8.png">

打开前后属性都是一样的
打开前
---
* checkable	false
* clickable	true
* enabled	true
* focusable	true
* focused	false
* scrollable	false
* longClickable	false
* password	false
* selected	false

打开后
---
 checkable	false
* clickable	true
* enabled	true
* focusable	true
* focused	false
* scrollable	false
* longClickable	false
* password	false
* selected	false

**Comment by dk457587** [comment]
可以看一下 'checked' 屬性是否由false轉為true

**Comment by ssfanli** [comment]
> 

我看了下，打开前后所有属性都一样

**Comment by ssfanli** [comment]
> 可以看一下 'checked' 屬性是否由false轉為true

我看了下，打开前后所有属性都一样

**Comment by VeerSun** [comment]
提供一个思路：
step1：
开关开启和关闭时，分别dump一份hierarchy
xml = d.dump_hierarchy()
step2：
用文档比对工具找到这两份dump的差异内容
step3：
来判断差异内容来确认是开启还是关闭状态
d().info["xxx"]

备注：Weditor网页界面显示的控件信息是一部分而已，就像你上面贴的恰好是完全不变的内容

**Comment by codeskyblue** [comment]
xpath中的.info里面增加了checked属性，再试试吧，我目前已经复现不出来了
