### ISSUE TITLE
进入 小程序或h5 页面检测不到组件

### ISSUE THREAD

**Issue by PJ-One** [openatx/uiautomator2#868]
- 手机型号：Galaxy note8 ，HONOOR V20
- uiautomator2的版本：Version: 2.16.19
- 
![image](https://user-images.githubusercontent.com/97378785/215727344-b6fa5b10-49ab-4263-be28-252e6de1f43e.png)

- 相关日志：日志就是找不到元素，用python -m weditor定位找不到，如图
![image](https://user-images.githubusercontent.com/97378785/215728350-ac969e60-b861-4c92-949f-c40a6b669710.png)

- 我现在这里不检测，用坐标点击进行的
![image](https://user-images.githubusercontent.com/97378785/215728736-88c0cccb-6562-43d6-9e66-66fcd382ed4b.png)

这种检测不是元素的情况，多数出现在h5页面，
请问有伙伴是否遇到？怎么解决的呢？谢谢答复

**Comment by wangxin-trec** [comment]
uiautomator2适合的是原生的android控件，网页的的话我觉得可以用模拟位置点击的方法吧

**Comment by DDDDanny** [comment]
楼上说的没错，u2确实更适合原生控件，但是现在h5页面铺天盖地，就很尴尬。
我也经常遇到元素拿不到的问题，我现在是结合图片识别和OCR来做的，你也可以试试看
