### ISSUE TITLE
支持或者可以增加在渲染的图片上增加描点能力么？比如输入一些命令可以把一些点坐标描到渲染的图片上

### ISSUE THREAD

**Issue by zzuguet2015** [openatx/uiautomator2#869]
支持或者可以增加在渲染的图片上增加描点么？比如：输入一些命令可以把一些指定的点坐标描到渲染出来的图片上

**Comment by wangxin-trec** [comment]
import uiautomator2.ext.htmlreport as u2htmlreport
htmlReport.patch_click()
