### ISSUE TITLE
使用push函数时 raise IOError("push", "%s -> %s" % (src, dst), r.text)

### ISSUE THREAD

**Issue by Mr-Doyle** [openatx/uiautomator2#873]
- 手机型号 小米6
- uiautomator2的版本号2.16.22
当我尝试把电脑文件传送到手机时会报错，
OSError: [Errno push] PCfilepath/11.PNG -> XIAOMIFilepath: 'open XIAOMIFilepath/11.PNG: no such file or directory\n'
代码：
d.push(PCfilepath + '/' + filename, XIAOMIFilepath),其中filename即文件的名字，上面报错 报告里的"11.PNG"

**Comment by codeskyblue** [comment]
should fixed now
