### ISSUE TITLE
HTTPConnectionPool(host='127.0.0.1', port=54167): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f02d41c1b10>: Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by arghyamukherjee007** [openatx/uiautomator2#874]
Ui Automator version - 2.16.0
Pytest version - 6.1.0
python version - 3.7.16
adbutil version - 0.11.0
while connecting with uiautomator getting error

`HTTPConnectionPool(host='127.0.0.1', port=54167): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f02d41c1b10>: Failed to establish a new connection: [Errno 111] Connection refused'))`

As part of workaround , 

- uninstalled uiautomator and adbutil and verified with pip list and pip3 list and make sure uiautomator not installed
and then installed freshly still same issue.
- uninstalled python , pytest and adbutil and installed freshly , still same issue.
- disconnect and reconnect and established the connection , still same issue

It is suppose to hit port 43179 , but instead hitting 54167

please help with workarounds.

**Comment by sc231997** [comment]
Try version 2.16.22

**Comment by arghyamukherjee007** [comment]
@sc231997 the happening for all version even with 2.16.22
it is suppose to hit port 43179 but hitting wrong port causing the failure

**Comment by arghyamukherjee007** [comment]
@sc231997 do you know from where this wrong port triggering?

**Comment by vbpatel73** [comment]
@sc231997 I am getting the same error when using aws device farm. how to fix it or workaround?

**Comment by sc231997** [comment]
@vbpatel73 what version you are using of UI Automator and what is the arch of the underlying hardware (arm, x86 etc)?

**Comment by vbpatel73** [comment]
> @vbpatel73 what version you are using of UI Automator and what is the arch of the underlying hardware (arm, x86 etc)?

i used 2.16.22for uiautomator and hardware i do not know as it is aws device farm
