### ISSUE TITLE
屏幕录制

### ISSUE THREAD

**Issue by elileo1** [openatx/uiautomator2#883]
手机型号： 华为 mate 30 pro
系统 harmonyOS 3.0.0
uiautomator2版本号： 2.16.23

d.screenrecord("out.mp4")
time.sleep(2)
d.screenrecord.stop()

没生成视频， 也没报任何错误

**Comment by 475420186** [comment]
小米11Pro，系统MIUI12.5
uiautomator2版本号：2.16.6
同样的代码，没有报错

**Comment by dwtrace** [comment]
手机型号： 华为 P40 pro
系统 harmonyOS 3.0.0
uiautomator2版本号： 2.16.23

d.screenrecord("out.mp4")
time.sleep(2)
d.screenrecord.stop()

没生成视频， 也没报任何错误

**Comment by 986379041** [comment]
我觉得需要执行两步操作：
1电脑依赖库：pip3 install -U "uiautomator2[image]" -i https://pypi.doubanio.com/simple
2手机环境初始化：python -m uiautomator2 init

**Comment by csushiye** [comment]
红米note13 pro,miui 14.0.1，安卓13
uiautomator2 version: 2.16.25
同样的代码，没有报错，但不会生成视频文件，但安卓11版本的vivo手机可以，是不是和安卓的版本有关

**Comment by codeskyblue** [comment]
直接用scrcpy录屏吧

**Comment by codeskyblue** [comment]
后面移除了，issue关闭
