### ISSUE TITLE
AtxAgent---无法提供服务，非am instrnment

### ISSUE THREAD

**Issue by tody-yang** [openatx/uiautomator2#885]
- android os 12
- uiautomator2的版本号(uiautomator2 version: 2.16.23, )

![5f2114554be67f72c800187b9c91e0a6](https://user-images.githubusercontent.com/13848709/232665889-7d6b5b51-2158-474a-98f7-d252e51a0869.jpg)

log:
[D 230418 11:34:59 watcher:92] [pid:27332] watch check
[W 230418 11:34:59 __init__:218] [pid:27332] atx-agent has something wrong, auto recovering
[D 230418 11:34:59 __init__:317] [pid:27332] [2750000305] device 2750000305 is online
[I 230418 11:35:00 init:156] uiautomator2 version: 2.16.23
[D 230418 11:35:00 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 230418 11:35:01 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 230418 11:35:01 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 230418 11:35:01 init:350] Check atx-agent version
[D 230418 11:35:01 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:01 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:02 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:02 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:03 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:03 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:04 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:04 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:05 init:359] Forward: local:tcp:49389 -> remote:tcp:7912
[D 230418 11:35:06 init:359] Forward: local:tcp:49389 -> remote:tcp:7912

代码：os.system("adb shell")
        os.system("chmod 777 /data/local/tmp/atx-agent")
        os.system("data/local/tmp/atx-agent version")
        os.system("/data/local/tmp/atx-agent server -d")
        os.system("/data/local/tmp/atx-agent server --nouia -d --addr 127.0.0.1:7912")
        ConnectDevice.dev.healthcheck()

agent.log:

ATX有安装，请大神看一看，帮忙解决下

atx-agent.log日志如下：
[atx-agent.log](https://github.com/openatx/uiautomator2/files/11258251/atx-agent.log)

atx-agent.daemon日志如下：

[atx-agent.daemon.log](https://github.com/openatx/uiautomator2/files/11258260/atx-agent.daemon.log)

**Comment by tody-yang** [comment]
@mingyuan-xia @codeskyblue 两位大神，帮忙看下

**Comment by s0ing** [comment]
多重启几次小汽车就好了

**Comment by s0ing** [comment]
![image](https://user-images.githubusercontent.com/33510187/234160063-92431175-93d8-4c44-a90c-15b540e790eb.png)
一直点 点到重启

**Comment by tody-yang** [comment]
不是重启的问题，是rom的权限问题，已解决

**Comment by tody-yang** [comment]
不是重启的问题，是rom的权限问题，已解决

**Comment by coisini6** [comment]
> 不是重启的问题，是rom的权限问题，已解决

这个怎么解决的呢，求解
