### ISSUE TITLE
是否能实现long_press() keycode 的功能

### ISSUE THREAD

**Issue by zzm-note** [openatx/uiautomator2#889]
- 手机型号：No
- uiautomator2的版本号：2.16.23
- 手机截图：No
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

背景：Android TV上模拟遥控器长按OK键，无法实现。而且该元素用long_click()是无效的。

**Comment by codeskyblue** [comment]
可以先用 adb shell input keyevent --longpress VOLUME_UP 代替
