### ISSUE TITLE
swipe方法是否支持 pt,mm,cm, inch,dp和sp等单位？目前看应该是按照像素来的，是否考虑增加其他单位？

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#89]
目前测试性能过程中，测试指标有个300mm/s的速度滑动，这个构造采用的swipe方法，但是每次都要将像素换算一下，是否可以直接支持单位？免去了换算的过程？

**Comment by codeskyblue** [comment]
你有没有个换算表

**Comment by flyfire100** [comment]
打印详细方式： 
adb shell dumpsys window displays 
执行结果： 
Dump time : 2016骞?2鏈?0鏃?涓婂崍10:43:00 
WINDOW MANAGER DISPLAY CONTENTS (dumpsys window displays) 
Display: mDisplayId=0 
init=960x540 240dpi cur=960x540 app=897x540 rng=540x502-897x850 
deferred=false layoutNeeded=false 
mStacks[0]0 



获取出来dpi然后根据dpi算出相应的关系

**Comment by codeskyblue** [comment]
等有空我再看看

**Comment by mingyuan-xia** [comment]
非常用需求，考虑到手机主要是px和dp，cm等特种需求不准备通过框架支持，建议使用上层抽象，好比Android的DisplayMetrics这种转换后使用框架操作，欢迎PR
