### ISSUE TITLE
uiautomator2有配置文件吗？如何通过修改配置文件让uiautomator2使用不同的adb服务

### ISSUE THREAD

**Issue by moliangdongdongdong** [openatx/uiautomator2#894]
1、手机型号：荣耀畅玩儿30
2、Android版本号：11
3、uiautomator2版本号：Version: 2.16.23
4、
<img width="974" alt="bc714d6b7153919ebf5198a4774ac6f" src="https://github.com/openatx/uiautomator2/assets/59324142/3bd5d953-3560-4257-8ae2-3770796e81a0">

**Comment by codeskyblue** [comment]
可以通过设置环境变量
ANDROID_ADB_SERVER_PORT
