### ISSUE TITLE
运行一段时间后，可以正常启动app，也能截屏看到正常界面，但通过dump_hierarchy只获得一个node节点

### ISSUE THREAD

**Issue by yangdejian** [openatx/uiautomator2#895]
我的程序是打开app，测试一些元素检测和点击事件，稳定运行一段时间后，突然无法获取到界面元素（当然也就无法点击）。电脑重启后故障依旧。手机暂时未进行重启（因手机在公司，待明天重启后再测试）。

- 手机型号：华为 DUK-AL20
- uiautomator2的版本号(`pip show uiautomator2`)： 2.16.23
- 手机截图
![home3](https://github.com/openatx/uiautomator2/assets/19420974/3f9395f5-afe4-470d-9ba3-fa758787ce4b)

- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
没有异常，无法获取界面元素。使用dump得到：
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy rotation="0">
  <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[0,0][1080,1920]" />
</hierarchy>

- 最好能附上可能复现问题的代码。
xml = d.dump_hierarchy()
print(xml)

**Comment by yangdejian** [comment]
补充：打开任何APP，使用d.dump_hierarchy()得到的都是：
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy rotation="0">
  <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="android" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" visible-to-user="true" bounds="[0,0][1080,1920]" />
</hierarchy>`

**Comment by yangdejian** [comment]
来到公司发现是ATX的UIAutomator服务停止了，在手机上开启解决了。不知道是否可以通过python来开启

**Comment by HiSYF** [comment]
解决了吗 我也遇到这个问题
