### ISSUE TITLE
UiAutomator2 crashes on some screen

### ISSUE THREAD

**Issue by AqmDevelopmentTeam** [openatx/uiautomator2#899]
Uiautomator2 crashes on some screen while running script, but the same is executed without any issue using Appium.

We have found that version of uiautomator2 which Appium uses is 4.21.1 and OpenATX's Uiautomator2 version is 2.16.1 which is very old.

**Can we have an updated Uiautomator2 version??**

How can we solve this crashing issue?  

Please help.

**Comment by codeskyblue** [comment]
pip install -U uiautomator2
