### ISSUE TITLE
自定义控件好像无法获取属性

### ISSUE THREAD

**Issue by yygqhyk** [openatx/uiautomator2#905]
- 手机型号
各种模拟器，目前是华为 mate50pro
- uiautomator2的版本号(`pip show uiautomator2`)
 2.16.23

好像如果目标控件是用户继承某个控件，然后自定义的控件，比如view.view，那么无法获取其中的文本数据了
请问这种情况是无法解决还是后续会开发
感谢

**Comment by codeskyblue** [comment]
后续会看看，先关掉了，跟其他的issue有重复
