### ISSUE TITLE
无法采用wifi方式连接手机

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#91]
我用的华为手机，采用USB方式执行完python -m uiautomator2 init后，拔下USB线
然后使用浏览器访问$DEVICE_URL/version
报错，说是连接失败
然后插上USB线，去后台查看，发现监听端口没有启动，如下
HWCOL:/ # netstat -anp | grep 7912
tcp6       1      0 ::ffff:127.0.0.1:47166  ::ffff:127.0.0.1:7912   CLOSE_WAIT  6691/com.github.uiautomator
tcp6       1      0 ::ffff:127.0.0.1:47169  ::ffff:127.0.0.1:7912   CLOSE_WAIT  6691/com.github.uiautomator
tcp6       1      0 ::ffff:127.0.0.1:47182  ::ffff:127.0.0.1:7912   CLOSE_WAIT  6691/com.github.uiautomator
tcp6       1      0 ::ffff:127.0.0.1:47168  ::ffff:127.0.0.1:7912   CLOSE_WAIT  6691/com.github.uiautomator
tcp6       1      0 ::ffff:127.0.0.1:47180  ::ffff:127.0.0.1:7912   CLOSE_WAIT  6691/com.github.uiautomator
HWCOL:/ #

然后执行adb shell /data/local/tmp/atx-agent -d，不断开USB线
然后再用浏览器访问$DEVICE_URL/version
发现可以出现版本信息

请处理

**Comment by codeskyblue** [comment]
手机型号提供下，估计是特定设备特定问题

**Comment by flyfire100** [comment]
应该不是，我测试了下安卓7.0的是可以的，安卓8.0的好像不行，不知道为啥，同样的操作方法，你可以找一台安卓8.0的机器试试

**Comment by flyfire100** [comment]
通过这种方式解决的，https://testerhome.com/topics/13311
