### ISSUE TITLE
AttributeError: 'Device' object has no attribute '_filelock'

### ISSUE THREAD

**Issue by LeelKumar** [openatx/uiautomator2#914]
1. 
![image](https://github.com/openatx/uiautomator2/assets/39989944/1fbb9f90-797f-4a03-b267-eb602cbe35c8)

2.
![image](https://github.com/openatx/uiautomator2/assets/39989944/bfaa08ee-fafd-4b44-bf71-3d44e10ed983)

-> device.press("home") 
->  jsonrpc.pressKey("home")
-> _jsonrpc_retry_call
-> timeout/server error
-> reset_uiautomator
      - try's to access paranet class attribute _filelock which is not instantiated. Because of  serial_or_url maps  to  
        http://xxx.xxx.xxx.xxx:xxxx and return without declaring _filelock

**Comment by MDasky1** [comment]
Just was working with this error. Are you using pyminitouch by chance? If so, don't use the latest version of uiautomator2 2.16.25, downgrade to 2.16.22. That made everything work better for me.

**Comment by LeelKumar** [comment]
> Just was working with this error. Are you using pyminitouch by chance? If so, don't use the latest version of uiautomator2 2.16.25, downgrade to 2.16.22. That made everything work better for me.

not using pyminitouch, but let me try using latest version(s). Thank you
