### ISSUE TITLE
如何获取对象的父节点？

### ISSUE THREAD

**Issue by 1800959** [openatx/uiautomator2#92]
因为要查找对象的父节点的兄弟节点的子节点
目前只有child和sibling

**Comment by flyfire100** [comment]
试试相对位置呢？
relative positioning

Also we can use the relative positioning methods to get the view: left, right, top, bottom.

d(A).left(B), selects B on the left side of A.
d(A).right(B), selects B on the right side of A.
d(A).up(B), selects B above A.
d(A).down(B), selects B under A.

**Comment by codeskyblue** [comment]
可以用用xpath来弄，比如 `d.xpath('//*[@text="Settings"]/..').click()`

**Comment by 1800959** [comment]
谢谢
