### ISSUE TITLE
Failed to connect 127.0.0.1:7912 Memu

### ISSUE THREAD

**Issue by borisprosto** [openatx/uiautomator2#922]
Failed to connect 127.0.0.1:7912
This error I see in the ATX application, which I installed uiautomator on the Memu emulator.

Please advise on how to fix it? Because of this error, I can't enable uiautomator on the emulator.

<img width="436" alt="MEmu_j7JO2jsqNo" src="https://github.com/openatx/uiautomator2/assets/128670972/dacf33ef-a9f0-44c2-9c5d-109573b95c38">

**Comment by Sergey-sply** [comment]
Did u solved it? I hame same problem :(

**Comment by codeskyblue** [comment]
Just use code to d.connect ，this button is useless

**Comment by Sergey-sply** [comment]
> Just use code to d.connect ，this button is useless

Its not working 
When im trying to connect to d,  I get an error saying that the connection has failed.

**Comment by codeskyblue** [comment]
Is you adb shell working?

**Comment by Sergey-sply** [comment]
> Is you adb shell working?

Yes, when i connect to the emulator on which android 7 all works fine. I have problem on android 9v.

**Comment by codeskyblue** [comment]
fixed
