### ISSUE TITLE
设备连接成功，但执行操作时，提示gateway error和 invalid version

### ISSUE THREAD

**Issue by shaoerkuai** [openatx/uiautomator2#924]
![image](https://github.com/openatx/uiautomator2/assets/117460332/e09c4351-59aa-43e8-bdb0-54905f69994e)
![image](https://github.com/openatx/uiautomator2/assets/117460332/dfa80968-f5aa-4d33-a1d8-2aa9d4a917f1)

- uiautomator2的版本号(`pip show uiautomator2`)
- Name: uiautomator2
Version: 2.16.25                                                 
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\program files\python38\lib\site-packages
Requires: adbutils, cached-property, Deprecated, filelock, logzero, lxml, packaging, Pillow, progress, requests, retry, six, whichcraft
Required-by: weditor

自研设备，非手机

**Comment by qingqingcaoyuanlin** [comment]
用2.16.25存在此问题，用2.16.21正常，2.16.25的packaging是23.2，2.16.21的packaging是20.9

**Comment by codeskyblue** [comment]
fixed
