### ISSUE TITLE
代码提示错误：Invalid version: ''

### ISSUE THREAD

**Issue by dreamer70521** [openatx/uiautomator2#929]
版本：uiautomator2==2.16.25

错误提示：Invalid version: ''

错误定位：__init__.py文件第733行返回None，导致第744行参数为空，执行packaging.version.parse("")的时候会报这个错误

**Comment by dreamer70521** [comment]
找到了解决方案：packaging的版本是23.2会报这个错误，换成20.9可以正常运行

**Comment by codeskyblue** [comment]
fixed

**Comment by vinhomesoceanpark** [comment]
I am also suffering from this condition. I have downgraded the packaging to 21.3 or downgraded uiautomator2 but the problem still persists. Hope you check it out
