### ISSUE TITLE
## 请问是否支持多设备并行测试？

### ISSUE THREAD

**Issue by yumao123** [openatx/uiautomator2#93]
## 请问是否支持多设备并行测试？
是否支持脚本一次运行，多台机器分开跑？
推荐的方法是哪些？

**Comment by codeskyblue** [comment]
开多线程，每台设备分别跑

**Comment by flyfire100** [comment]
import os,time
import uiautomator2 as u2
from multiprocessing import Process,Queue

def get_devices_serials():
    devices_list = []
    fd = os.popen("adb devices")
    devices_list_src = fd.readlines()
    fd.close()
    for device in devices_list_src:
        if "device\n" in device:
            device = device.replace("\tdevice\n","")
            devices_list.append(device)
    return devices_list
    
def worker( serial ):
    os.system("python -m uiautomator2 init  --serial %s"%serial)
    d = u2.connect(serial)
    print(d.info)
    #这里可以添加自己要执行的脚本
    
if __name__ == "__main__":
    process_list = []
    serial_list = get_devices_serials()
    for index in range( len(serial_list) ):
        p = Process( target=worker, args=( serial_list[index],  ) )
        p.start()
        process_list.append(p)
    for p in process_list:
        p.join()
    print("all task done!")

**Comment by flyfire100** [comment]
```python
import os,time
import uiautomator2 as u2
from multiprocessing import Process,Queue

def get_devices_serials():
    devices_list = []
    fd = os.popen("adb devices")
    devices_list_src = fd.readlines()
    fd.close()
    for device in devices_list_src:
        if "device\n" in device:
            device = device.replace("\tdevice\n","")
            devices_list.append(device)
    return devices_list
    
def worker( serial ):
    os.system("python -m uiautomator2 init  --serial %s"%serial)
    d = u2.connect(serial)
    print(d.info)
    #这里可以添加自己要执行的脚本
    
if __name__ == "__main__":
    process_list = []
    serial_list = get_devices_serials()
    for index in range( len(serial_list) ):
        p = Process( target=worker, args=( serial_list[index],  ) )
        p.start()
        process_list.append(p)
    for p in process_list:
        p.join()
    print("all task done!")
```

**Comment by flyfire100** [comment]
这个issue可以关闭了吧？

**Comment by yumao123** [comment]
谢谢

**Comment by oujibahei** [comment]
似乎并不能实现多设备连接 print的所有设备都是第一个connect上的

**Comment by codeskyblue** [comment]
@oujubahei 历史问题，已经修复了

**Comment by wangshuwen1107** [comment]
u2.connect()使用过一次之后再调用不能改变返回的值，也遇到了相同问题，有解决吗

**Comment by codeskyblue** [comment]
@wangshuwen1107 说详细点
