### ISSUE TITLE
dump_hierarchy显示的元素不完整

### ISSUE THREAD

**Issue by kitezzzGrim** [openatx/uiautomator2#930]
- 手机型号 小米11
- uiautomator2的版本号: 2.16.25

代码如下
import uiautomator2 as u2
import time
d = u2.connect()
hierarchy_info = d.dump_hierarchy()
print(hierarchy_info)

测试页面如下
<img width="441" alt="Snipaste_2023-12-22_17-59-43" src="https://github.com/openatx/uiautomator2/assets/32265931/b9b877de-6e24-43ee-acda-89c9082a059d">

此时的dump_hierarchy()输出只有一部分，没有下面的人格测试MBTI、抑郁测试症状啥的
<img width="1715" alt="Snipaste_2023-12-22_18-06-12" src="https://github.com/openatx/uiautomator2/assets/32265931/69bf665a-4c2c-41cc-911a-e1b80c58c11f">

<img width="1150" alt="image" src="https://github.com/openatx/uiautomator2/assets/32265931/c87a63fe-f173-4414-ae3b-447470a9e8de">
只有最上面的充电、WLAN元素啥的，这个是获取不到中间小程序的元素么

**Comment by kitezzzGrim** [comment]
补充 我发现应该是 uiautomator dump 提示killed
<img width="269" alt="image" src="https://github.com/openatx/uiautomator2/assets/32265931/1a2b7cda-2f14-40e7-b0d1-28054694879c">

**Comment by SeansuHappy** [comment]
我在很久之前就发现了这个问题，但是很遗憾没有解决；目前我现在的解决方案是 是用微信7.0.7版本的客户端，这个版本是可以完美抓取到公众号列表的所有元素

**Comment by codeskyblue** [comment]
这个群里的网友说可以在android加个webenhanced flag解决，如果可以的话，估计很快就能解决

**Comment by codeskyblue** [comment]
已增加，目前看起来还好。华为P40，微信最新版本
![image](https://github.com/openatx/uiautomator2/assets/3281689/2d73a08b-22a6-43a9-80c6-8c010c2c66ac)

**Comment by CCbird** [comment]
> 已增加，目前看起来还好。华为P40，微信最新版本 ![image](https://private-user-images.githubusercontent.com/3281689/330262258-2d73a08b-22a6-43a9-80c6-8c010c2c66ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzE0MjMsIm5iZiI6MTczNTAzMTEyMywicGF0aCI6Ii8zMjgxNjg5LzMzMDI2MjI1OC0yZDczYTA4Yi0yMmE2LTQzYTktODBjNi04YzAxMGMyYzY2YWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMDkwNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE4MDEwNGJlNGEzZDM5MTUwNDY2NjVkYjVhMzdjODQ3YzAwMDhkMGY3MmIxNzk3NmQxZWY0NDA1Mjg2ZmE4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iaBTVl9pPXQpREGyknRsP0wG2fk_0WlLzuGoT4DvHGM)

你好 请问webenhanced flag如何添加呢
