### ISSUE TITLE
Can't connect inside a docker container

### ISSUE THREAD

**Issue by DillerDurak** [openatx/uiautomator2#931]
While connecting to a device I get ConnectionRefusedError (image 1), though in docker-compose file I added extra_hosts and enviroment (image 2). Also I can get list of connected devices from the container using adb devices and do another adb things such as shell and stuff. Why I can't do same things in uiautomator2 (version 2.16.14)?  
![image](https://github.com/openatx/uiautomator2/assets/99507034/334ac9cd-d068-4755-b294-280b3e21bc63)
![image](https://github.com/openatx/uiautomator2/assets/99507034/31e2d068-3ddb-402d-8def-dc8317205f2b)

**Comment by codeskyblue** [comment]
try to change ANDROID_ADB_SERVER_ADDRESS to ANDROID_ADB_SERVER_HOST
