### ISSUE TITLE
能否帮助做下对安卓10剪切板的支持

### ISSUE THREAD

**Issue by zaimatest** [openatx/uiautomator2#933]
安卓10无法获取剪切板内容，能否做下对安卓10的适配和支持，非常感谢

- 安卓10手机
- uiautomator2 V2.16.25

**Comment by caofengbin** [comment]
安卓10之后应该是系统层面做了限制，非当前获取焦点的应用，拿不到剪切板的内容：https://developer.android.com/about/versions/10/privacy/changes?hl=zh-cn#clipboard-data

**Comment by codeskyblue** [comment]
目前用的自定义输入法做的剪贴板获取支持。文档有写  从3.1.0开始增加的
