### ISSUE TITLE
多线程adb很容易卡死

### ISSUE THREAD

**Issue by blueslilili** [openatx/uiautomator2#937]
python写了个多线程的脚本进行自动化测试（while循环，不断执行adb脚本），一台PC（windows）通过uiautomator2以wifi连接多台真机，一个线程连接一台设备，运行一段时间后，adb就会卡死，cmd输入adb devices或者adb kill-server都没响应，查看任务管理器，只有一个adb.exe进程，强制杀掉adb进程后，程序又可以正常运行了，过一会又卡死。

有什么办法可以解决？区分端口起多个adb.exe进程，一个线程用一个adb进程，貌似可以解决，但是uiautomator2默认连接的5037端口，这种方式实现不了

**Comment by hl-shi** [comment]
老铁最后怎么解决的

**Comment by blueslilili** [comment]
连接的时候加上端口：5555

suifengpiaoguo ***@***.***>于2024年10月9日 周三14:56写道：
