### ISSUE TITLE
MacOS M2芯片UIAutomator2无法init

### ISSUE THREAD

**Issue by zhaoxu-zhang** [openatx/uiautomator2#939]
无法在M2芯片的模拟器上启动UIAutomator2

UIAutomator2版本: 2.16.13
模拟器: Pixel 6; system image: android-28/google_apis/arm64-v8a

问题：在uiatomator2 init的过程中，发现atx-agent无法启动。经debug，发现当运行`atx-agent server -d`的时候，模拟器就死机了，程序也没有任何输出。

以为是atx-agent不支持armv8的架构，但感觉不应该。求问有人遇到过同样的问题吗？如何解决？

**Comment by codeskyblue** [comment]
试试 uiautomator 3.x.x 我测试了一下本地的模拟器，M1启动的。看起来问题应该不大。有问题再重新open好了
