### ISSUE TITLE
目前测试应用的性能时有一个帧频，是否可以将这个功能加入到我们的项目中？

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#94]
大神，是否可以加入下FPS的统计功能？下面是我看的一个FPS的统计方法
https://testerhome.com/topics/4775

我刚开始接触APP测试，以前是搞服务端软件的测试，感觉APP测试的监控工具比较少

以前测试常用nmon，但是在手机上好多资源都无法监控了，是否可以加入一些监控的功能？

比如CPU、内存、FPS、功耗等

功耗仪十几万
机械臂几十万

不是小公司能承受的呀

**Comment by codeskyblue** [comment]
你说的是测试帧率吧，确实想做，不过最近实在抽不出时间。

**Comment by mingyuan-xia** [comment]
这个自动化框架无关，采集FPS有GT, DoramonKit, AndroidGodEye, Appetizer
