### ISSUE TITLE
uiautomator2/assets/app-uiautomator.apk' not found

### ISSUE THREAD

**Issue by lbdann2** [openatx/uiautomator2#940]
OSError: file 'C:/Users/User/AppData/Local/Temp/_MEI291642/uiautomator2/assets/app-uiautomator.apk' not found
[31280] Failed to execute script 'autozaliv' due to unhandled exception!
Whats wrong?

**Comment by lbdann2** [comment]
https://ibb.org.ru/1/ILPO1D
https://ibb.org.ru/1/ILPASQ

**Comment by alialerwi** [comment]
go to assert folder in C:\Python39\Lib\site-packages\uiautomator2\assets and convert ,sh to .bat and run it to download them here is the file just copy it to that folder and run it 

here is how i converted it 
@echo off
set APK_VERSION=2.3.3
curl -L "https://github.com/openatx/android-uiautomator-server/releases/download/%APK_VERSION%/app-uiautomator.apk" --output "app-uiautomator.apk"
curl -L "https://github.com/openatx/android-uiautomator-server/releases/download/%APK_VERSION%/app-uiautomator-test.apk" --output "app-uiautomator-test.apk"

**Comment by codeskyblue** [comment]
已修复，升级到3.0.3以上就行。目前的最新版本是3.0.4

**Comment by alexitooh** [comment]
tengo el mismo problemas en todas las versiones, pero el problema es cuando esta compilado a .exe solo ahi sucede

https://prnt.sc/NhiZ15y0wGuG

**Comment by codeskyblue** [comment]
@alexitooh which version u are using

**Comment by nedsion** [comment]
got same issue with 3.0.8
but only got while i build in .exe
