### ISSUE TITLE
(开头的xpath识别错误

### ISSUE THREAD

**Issue by zykeee** [openatx/uiautomator2#941]
使用括号开头的xpath`(//android.widget.ImageView)[2]`用来匹配第n个match的元素时
会被当作自定义的字符串匹配语法处理

- 手机型号：任意
- uiautomator2的版本号：2.16.25
- 手机截图：无
- 相关日志：`uiautomator2.exceptions.XPathElementNotFoundError: ["//*[@text='(//android.widget.ImageView)[2]' or @content-desc='(//android.widget.ImageView)[2]' or @resource-id='(//android.widget.ImageView)[2]']"]`
- 附上可能复现问题的代码：`d.xpath("(//android.widget.ImageView)[2]").get(1)`

**Comment by codeskyblue** [comment]
前面加个/试试

**Comment by zykeee** [comment]
加/会被当作Invalid expression处理
