### ISSUE TITLE
通过sibling获取的文本不会自动更新

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#954]
使用sibling获取文本，中途文本变化，再进行获取，获取到的文本内容是旧的，不是最新，需要执行一次d.dump_hierarchy()才能获取到最新的文本。
- uiautomator2的版本号：Version: 2.16.23
- text控件文本内容是变化的，d(text='abc').sibling(resourceId="xxx“).get_text()多次执行，获取的文本都是不变的，
- 需要先执行d.dump_hierarchy()，再执行d(text='abc').sibling(resourceId="xxx“).get_text()才能获取到最新的文本。
-

**Comment by codeskyblue** [comment]
请更换 uiautomator2 3.2.0再尝试一下
