### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version

### ISSUE THREAD

**Issue by vinhomesoceanpark** [openatx/uiautomator2#960]
I'm quite tired of this situation. I tried downgrading the package to the one shown in the picture but the problem still persists. 

One strange thing is when I use weditor to connect first. Run the code and click on the coordinates , and the code in the terminal will not error anymore.

Hope you check it out
![3](https://github.com/openatx/uiautomator2/assets/48808550/3c01f5b1-847c-43a8-be87-8c49b0c3ec33)
![Screenshot 2024-04-28 115811](https://github.com/openatx/uiautomator2/assets/48808550/d71a032d-3271-4b2a-9fe8-ff43554e9771)
![2](https://github.com/openatx/uiautomator2/assets/48808550/cc61f15a-1505-4d3a-b51c-c9157cb2b628)

**Comment by codeskyblue** [comment]
how about update uiautomator2 version to 3.0.9
this version removed packaging lib and a lot of  other useless lib

**Comment by vinhomesoceanpark** [comment]
yes i have trying use 3.0.9. So it still have error about packaging too. You can see at my picture here :(
![xx](https://github.com/openatx/uiautomator2/assets/48808550/2ac55fed-c6cf-4871-a5fb-5b3ec421ded6)

**Comment by codeskyblue** [comment]
@vinhomesoceanpark This is because there two python installed on your computer(python39, python12), remove python39 will make it right
