### ISSUE TITLE
无法查看页面元素结构

### ISSUE THREAD

**Issue by itltf512116** [openatx/uiautomator2#962]
问题描述：
 接入手机后，使用uiauto.dev查看页面元素，只有第一次进入页面时可以查看，后退页面之后再重新进入，无法查看页面结构

操作步骤：拼多多，点击多多视频，然后左上角进个人中心，点个人中心，创作者中心，进带货视频中心，然后就到了出问题的这个页面了
- 手机型号 荣耀X20 Android12
- uiautomator2的版本号 3.0.8
-  uiauto.dev version 0.3.1

请问这个是哪里的问题呢？另外我自己编译了android-uiautomator-server的安卓代码，发现只有再展示下图时，每次进入这个页面都可以显示正确的页面结构，但是一旦下图的显示是正常时，就会复现上面的问题--无法显示页面结构
![52e256a72960de78816fd8653180d490](https://github.com/openatx/uiautomator2/assets/3404388/1a85b36d-bd7b-4924-989a-61cdbc5edf2a)

**Comment by codeskyblue** [comment]
还有别的界面吗？你这个我进不去啊
