### ISSUE TITLE
最新版本3.0.9使用d(text='xxx').click()无法找到元素，旧版本没问题

### ISSUE THREAD

**Issue by Xiaojun0822** [openatx/uiautomator2#963]
旧版本运行:
![Image_1714306405254.jpg](https://github.com/openatx/uiautomator2/assets/33214307/99cebff8-b2c8-4f7c-8267-5fcbe212e774)

新版本运行:
![Image_1714306407346.jpg](https://github.com/openatx/uiautomator2/assets/33214307/d864467b-05ff-49fb-9041-34138b5e5fe4)

**Comment by Zeros2619** [comment]
新版本移除了atx-agent，有较大改动，还不稳定，建议先用旧版本

**Comment by codeskyblue** [comment]
fixed
