### ISSUE TITLE
HTTPConnectionPool Read timed out

### ISSUE THREAD

**Issue by Apple-Flavor** [openatx/uiautomator2#97]
d.healthcheck() 返回True
python -m uiautomator2 init 也成功
但是，运行测试就报错：
HTTPConnectionPool(host='127.0.0.1', port=50129): Read timed out. (read timeout=60)

apk启动之后的有一行蓝字显示0.0.0.0,我记得之前显示的127.0.0.1吧？是不是这个的问题？

**Comment by codeskyblue** [comment]
运行的什么代码 什么手机，其他的手机是否正常
