### ISSUE TITLE
screen_on()和screen_off()运行后设备无反应

### ISSUE THREAD

**Issue by Xiaojun0822** [openatx/uiautomator2#970]
- 手机型号：作业帮学习平板（android12）
- uiautomator2的版本号(`pip show uiautomator2`)：3.0.13
- 手机截图
![image](https://github.com/openatx/uiautomator2/assets/33214307/2c084e94-4848-4692-991d-5a75fd87ba6d)

- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
换成 3.0.14+试试，这个应该是因为关联的 Uiautomation  not connected 导致的
