### ISSUE TITLE
d.dump_hierarchy()无法获取到数据

### ISSUE THREAD

**Issue by Xiaojun0822** [openatx/uiautomator2#971]
- 手机型号：作业帮学习平板（android12）
- uiautomator2的版本号(`pip show uiautomator2`)：3.0.13
- 手机截图
![image](https://github.com/openatx/uiautomator2/assets/33214307/80c9a66f-a0f4-450b-8b8f-b7438f88fcb5)

- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
已修复，请测试一下最新版本
