### ISSUE TITLE
运行import uiautomator2 as u2  d = u2.connect() # connect to device print(d.info)命令 执行connect()后报错: FileNotFoundError: [Errno 2] No such file or directory: '\\uiautomator2\\uiautomator2\\assets\\version.txt'

### ISSUE THREAD

**Issue by lhxunmeng** [openatx/uiautomator2#973]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue将自动被机器人打上`Invalid`标签并且自动关闭！！。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
先运行一下make sync

**Comment by codeskyblue** [comment]
see <https://github.com/openatx/uiautomator2/blob/master/DEVELOP.md> for more details
