### ISSUE TITLE
d(resourceId=str) Server error: android.support.test.uiautomator.StaleObjectException

### ISSUE THREAD

**Issue by Apple-Flavor** [openatx/uiautomator2#98]
这个str是不是太长的话，也不行？ 其他控件都好好的，可以点击。有一个控件的resourceId很长，比如：
com.tudou.musicplayer:id/music_info_music_name_txtdd  click/wait/get_text等事件要花费好长时间不返回，有时候read timeout或者Server error: android.support.test.uiautomator.StaleObjectException

**Comment by Apple-Flavor** [comment]
对这个音乐界面的所有的动作执行的都很慢，甚至出现HTTPConnectionPool(host='127.0.0.1', port=59151): Read timed out. (read timeout=60)的错误。请问这个和app有关系么，其他的app界面都正常的。

**Comment by codeskyblue** [comment]
比较类似这个问题 https://github.com/openatx/uiautomator2/issues/41
