### ISSUE TITLE
u2出现频闪，紧急~~

### ISSUE THREAD

**Issue by shirleylikefish** [openatx/uiautomator2#981]
- 手机型号：安卓版本是10
- uiautomator2的版本号：2.16.25
- ![image](https://github.com/openatx/uiautomator2/assets/170719109/b6eac7b4-9b71-48d6-b5f2-c0ce636c426b)
https://github.com/openatx/uiautomator2/assets/170719109/1712c1f8-f531-486d-969d-6627a778fdac
- 相关日志(Python控制台
出现频闪时控制台输出以下图片中的内容：
WARNING  retry.api:api.py:40 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 0.5 seconds...
![image](https://github.com/openatx/uiautomator2/assets/170719109/ffa84802-219a-4a7e-b30e-563f477a2c76)

错误信息, adb logcat完整信息, atxagent.log日志)
uiautomator2.exceptions.UiAutomationNotConnectedError: ({'code': -32001, 'message': 'java.lang.IllegalStateException', 'data': 'java.lang.IllegalStateException: UiAutomation not connected!\n\tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)\n\tat android.app.UiAutomation.waitForIdle(UiAutomation.java:769)\n\tat androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)\n\tat androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)\n\tat androidx.test.uiautomator.UiDevice.waitForIdle(UiDevice.java:621)\n\tat androidx.test.uiautomator.UiDevice.getWindowRoots(UiDevice.java:1096)\n\tat androidx.test.uiautomator.UiDevice.hasObject(UiDevice.java:137)\n\tat androidx.test.uiautomator.Until$2.apply(Until.java:55)\n\tat androidx.test.uiautomator.Until$2.apply(Until.java:52)\n\tat androidx.test.uiautomator.WaitMixin.wait(WaitMixin.java:40)\n\tat androidx.test.uiautomator.WaitMixin.wait(WaitMixin.java:34)\n\tat androidx.test.uiautomator.UiDevice.wait(UiDevice.java:174)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.waitForExists(AutomatorServiceImpl.java:1055)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:919)\n'}, 'waitForExists')

出现次数很频繁

**Comment by codeskyblue** [comment]
升级一下呗

**Comment by shirleylikefish** [comment]
升级了闪的更频繁了，没有跑脚本都在闪

**Comment by codeskyblue** [comment]
正常会闪两下，不过不影响正常运行的

**Comment by shirleylikefish** [comment]
影响执行过程：开始频闪时前台的安卓包切换到了u2，当前的频闪的界面把原来的安卓包界面替换覆盖了，脚本就找不到元素，报错了

**Comment by codeskyblue** [comment]
脚本找不到元素，不带重试的吗？

**Comment by shirleylikefish** [comment]
这个闪屏是修不了吗？上一年用也没有出现，最近几个月出现了。

**Comment by codeskyblue** [comment]
@shirleylikefish 你要不截图看看？或者提供一些日志之类的

**Comment by codeskyblue** [comment]
加一下qq群吧，可以把视频贴出来 @shirleylikefish

**Comment by codeskyblue** [comment]
issue我先关掉了
