### ISSUE TITLE
 不同手机适配的问题

### ISSUE THREAD

**Issue by lishaozheng** [openatx/uiautomator2#984]
![企业微信截图_17168107482150](https://github.com/openatx/uiautomator2/assets/82505377/47dae64d-4d0a-4142-8a58-9835dd0ebadb)

不同手机适配的问题，resourceId不一样，层级也不一样，有什么办法解决吗？

**Comment by lishaozheng** [comment]
![image](https://github.com/openatx/uiautomator2/assets/82505377/5e8b0343-8040-4b3a-b1bf-72ee4102090a)

**Comment by codeskyblue** [comment]
抖音就这样，别用resourceId了
