### ISSUE TITLE
Feature to configure the ADB port in uiautomator2. Users can now specify a custom port, providing more flexibility.

### ISSUE THREAD

**Issue by Diogo-py** [openatx/uiautomator2#988]
Changes:

Added an option to set a custom ADB port.

Example:
For instance, the ADB server typically starts on the default port 5037. However, by using adb -P 5038, it's possible to start a new server on port 5038 (or any other available port). I want to be able to connect to a device that is on adb port 5038

**Comment by codeskyblue** [comment]
Check adbutils for more details. The adbutils is support change port by env var

**Comment by Diogo-py** [comment]
I achieved. :)
