### ISSUE TITLE
element.info 获取的resourceName始终为None，但标签的实际resource-id不是None

### ISSUE THREAD

**Issue by feichuanshuo** [openatx/uiautomator2#991]
我在雷电模拟器上，对印象笔记进行标签属性的获取是遇到该问题

**Comment by codeskyblue** [comment]
3.2.0上测试了一下，看起来很正常
<img width="711" alt="image" src="https://github.com/user-attachments/assets/ce36a47c-bc50-4045-a84f-f3579858c87f">
