### ISSUE TITLE
Local server not started, start with  $ python -m weditor

### ISSUE THREAD

**Issue by Hillswang** [openatx/uiautomator2#993]
<img width="816" alt="企业微信截图_17189351693350" src="https://github.com/openatx/uiautomator2/assets/145125510/ffd97265-8f4e-48b4-a78d-2554bbb3b3fb">
<img width="935" alt="企业微信截图_17189351412410" src="https://github.com/openatx/uiautomator2/assets/145125510/1b441db3-22de-4411-bcff-6cd54eb02cf8">

weditor == 0.6.4
python == 3.8

**Comment by codeskyblue** [comment]
try https://uiauto.dev
