### ISSUE TITLE
d.xpath("//android.widget.SeekBar").attr获取的content-desc的信息为空

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#994]
- uiautomator2的版本号:3.1.0
通过xpath获取Seekbar的信息，在UIAuto.dev能够显示content-desc的信息（参考下方截图），但是使用
print(d.xpath("//android.widget.SeekBar").attrib)获取content-desc的信息为空

`{'index': '5', 'text': '', 'resource-id': 'com.xxxxxxx:id/screen_saver_timeout_slider', 'package': 'com.xxxx', 'content-desc': '', 'checkable': 'false', 'checked': 'false', 'clickable': 'true', 'enabled': 'true', 'focusable': 'true', 'focused': 'false', 'scrollable': 'false', 'long-clickable': 'false', 'password': 'false', 'selected': 'false', 'visible-to-user': 'true', 'bounds': '[566,253][1308,331]', 'drawing-order': '5', 'hint': ''}

`

![image](https://github.com/openatx/uiautomator2/assets/8575159/1287e128-dc7d-43fb-a46d-9cc45fcabb3d)

**Comment by qingqingcaoyuanlin** [comment]
d.xpath("//*[@content-desc='Value, 120']").swipe("right")进行操作是正常的

**Comment by Maksimwww** [comment]
** trustwallet.com**

**Comment by codeskyblue** [comment]
你看看是不是有两个seekbar
