### ISSUE TITLE
跑用例时遇到错误adbutils.errors.AdbError: cannot bind listener: Too many open files

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#998]
跑用例时通过adb connect {IP}方式连接adb，在跑多个用例后，概率行遇到adb server挂了，查看异常日志提示
adbutils.errors.AdbError: cannot bind listener: Too many open files
看着像是使用了很多端口，有点像是内存泄漏的感觉。
- uiautomator2的版本号3.1.0
- adb版本1.0.41
![image](https://github.com/openatx/uiautomator2/assets/8575159/6564c6a2-c36b-47aa-aa7b-d6bb753c556b)

**Comment by codeskyblue** [comment]
这个改一下openfiles的上限应该就可以

**Comment by zytwell** [comment]
@codeskyblue marlin:/ $ ulimit -n 
32768
